### ISSUE TITLE
Automatical sync to mall all offline available is broken

### ISSUE THREAD

**Issue by landscape69** [noinnion/greader#100]
The automaticaly syncing of all and making all offline available is broken.

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
