### ISSUE TITLE
Video isn't visible when I play from CNN

### ISSUE THREAD

**Issue by docarbe** [noinnion/greader#101]
Hi, I have a nexus 9 with latest os (marshmallow). I've got CNN as a feed and when I try and watch video from CNN, I get sound but no visible video. Is there a plug in or other means that I need to install  in gReader pro to see video?

Thanks for your help.

**Comment by docarbe** [comment]
I should have added that video displays fine in the browser and also from feedly

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

also turn on Hardware accelleration

**Comment by docarbe** [comment]
Thank you. Enabling the hardware acceleration worked. I can now see the CNN
videos through gReader. I won't worry about downloading the beta at this
time.

Steve
