### ISSUE TITLE
Keyboard won'the hide after new label is created and saved in the article view

### ISSUE THREAD

**Issue by sysadm01** [noinnion/greader#103]
Keyboard won'the hide after new label is created and saved in the article view

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
