### ISSUE TITLE
Subscriptions won't download

### ISSUE THREAD

**Issue by Anhlyss** [noinnion/greader#107]
For the past several days, none of my RSS subscriptions are downloading, except Reuters Top News.

**Comment by verycurt** [comment]
Same for me. Exactly two days. Perhaps related: for the last two days my Gmail hasn't synced either. (Only on my Galaxy Note 2, not in desktop Gmail.)

**Comment by verycurt** [comment]
Update: I cleared the cache through the gReader app, plus cleared the cache through Android app manager, then rebooted. No change.

**Comment by verycurt** [comment]
Update 2: When I deleted an RSS feed, then added it again, it updated that one time, but not subsequently.

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true
