### ISSUE TITLE
Text wraps too tightly around images

### ISSUE THREAD

**Issue by arcresu** [noinnion/greader#11]
For smaller images in the landscape mobile view, the text wraps too tightly on the right of the image like so:

![Text wrapping](http://i.imgur.com/FWs2Rh6.png)

It looks too cramped, and sometimes it's hard to tell the caption apart from the text like this. I would suggest adding some right margin to the images when they are less than half the width of the screen or so, and for any larger images clear the text so it doesn't wrap at all. Also possibly style the captions somehow to differentiate them from the article's body.

**Comment by noinnion** [comment]
Closed for now, if it still happens in latest version 5.1.2, please reopen it again. Thanks
