### ISSUE TITLE
Links in articles

### ISSUE THREAD

**Issue by ipkh** [noinnion/greader#112]
Links in articles are not functional when app switching.
Steps to reproduce;
1. Open a news article on greader
2. Switch to another app or have a notification pull you out of greader.
3. Click on a link or button in the article
4. Link does not work.  Text input does not work.
5. Reload article to enable links.

Other notes.  Article may get cut off below last viewable portion.

My main use case is getting passwords for site login from password manager.  Also, certain appsychological like gentle alarm take over screen on occasion.

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by ipkh** [comment]
So far so good.  Downloaded and installed a few hours ago.
Seems good so far.

**Comment by ipkh** [comment]
Fixed.
