### ISSUE TITLE
Blank screen when app was left within article and returning from other app 

### ISSUE THREAD

**Issue by tobischi** [noinnion/greader#115]
When I leave the app while reading an article and return back to it then the screen is blank. 

It helps to go back to the article list and re-enter the article. 

But this blank screen but has not been there "before some time". 
For me this is quite annoying as it breaks the flow.

**Comment by sentinelvdx** [comment]
Exactly the same issue I see and the workaround when troubleshooting is the same one, go back and re enter the article

**Comment by tobischi** [comment]
Forgot to mention: using Nexus 4, Android 5.1.1 LMY48T, stock launcher

**Comment by sentinelvdx** [comment]
My case is a Galaxy S6 (SM-G920I) running 5.1.1 Samsung's stock rom

**Comment by nyn3x** [comment]
Seems to be a dupe of https://github.com/noinnion/greader/issues/114. I have the same issue on HTC M9 running 6.0 stock ROM.

**Comment by markus-perl** [comment]
It's hard to track down the issue without the source code but is it possible, that the ItemActivity simply misses a .onResume() call on the web_view, cache_view and feed_view?

**Comment by borealissw** [comment]
Same issue here. Any change away from app and back loses screen. Doesn't seem to matter if its feed or web view.

Nexus 5, stock 6.0.1

**Comment by ajoe** [comment]
GReader is DEAD!  
Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available. 
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by sentinelvdx** [comment]
Well this beta seems to work. I'm not seeing the black screen or the static screen issue when switching between apps. Or after unlocking my phone with the app on a feed/web. But I'll keep testing and update if something different happens. Thanks!

**Comment by borealissw** [comment]
Looking good so far. Thanks.

**Comment by nyn3x** [comment]
Well,  after updating Android System WebView to 49.0.2623.105 the problem seems to be gone - even though I didn't update to the beta of greader.
