### ISSUE TITLE
Images are often not loaded in the cache

### ISSUE THREAD

**Issue by mlevison** [noinnion/greader#120]
Even though I've set them to load, pictures still don't load for some feeds example: bythom.com or theonlinephotograper.com.

**Comment by ajoe** [comment]
GReader is DEAD!  
Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available. 
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by noinnion** [comment]
here is the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by mlevison** [comment]
Not fixed please reopen. Will provide links to articles who's images are
not cached, later.

cheers
Mark

**Comment by mlevison** [comment]
This post:
http://feedproxy.google.com/~r/typepad/ZSjz/~3/npsIl6MJXc4/panasonic-is-wonderful.html
didn't
have its images loaded. Nor do many of the posts from the same feed. This
site: http://visualsciencelab.blogspot.ca often has trouble too.

Cheers
Mark

On Mon, Apr 11, 2016 at 8:49 AM, Mark Levison <mark@mlevison.com> wrote:

> Not fixed please reopen. Will provide links to articles who's images are
> not cached, later.
>
> cheers
> Mark
> On Apr 11, 2016 2:48 AM, "noinnion" <notifications@github.com> wrote:
>
>> Closed #120 <https://github.com/noinnion/greader/issues/120>.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/noinnion/greader/issues/120#event-621971249>
>>
>


-- 

[image: headshot-square-300x300]
<http://www.flickr.com/photos/36331075@N00/9674877046/> *Mark Levison* | 1
(877) 248-8277 | Twitter <https://twitter.com/mlevison> | LinkedIn
<http://ca.linkedin.com/in/marklevison> | Facebook
<https://www.facebook.com/agilepainrelief>
Certified ScrumMaster Training: Vancouver
<http://agilepainrelief.com/courses/vancouver> | Edmonton
<http://agilepainrelief.com/courses/edmonton> | Ottawa
<http://agilepainrelief.com/courses/ottawa> | Montreal
<http://agilepainrelief.com/courses/montreal> | Toronto
<http://agilepainrelief.com/courses/toronto>
Certified Product Owner & Private Training also available ~ Our Training
Schedule <http://agilepainrelief.com/courses/certified-scrum-agile-training>
Agile Pain Relief Consulting <http://agilepainrelief.com/> | Notes from a
Tool User <http://agilepainrelief.com/notesfromatooluser>
Proud Sponsor of Agile Tour Gatineau Ottawa <http://goagiletour.ca/> and Agile
Coach Camp Canada <http://agilecoachcampcanada.wordpress.com/>

**Comment by noinnion** [comment]
please try the latest beta v4.3.1_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.1_pro-beta.apk?raw=true

try to turn off "Save data traffic" in Settings->Offline Reading

**Comment by mlevison** [comment]
On Wed, Apr 13, 2016 at 7:01 AM, noinnion <notifications@github.com> wrote:

> please try the latest beta v4.3.1_beta
>
> https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.1_pro-beta.apk?raw=true
>
> try to turn off "Save data traffic" in Settings->Offline Reading


​Done. Give me a week or so to see if the problem reoccurs.

Cheers
Mark​
[image: headshot-square-300x300]
<http://www.flickr.com/photos/36331075@N00/9674877046/> *Mark Levison* | 1
(877) 248-8277 | Twitter <https://twitter.com/mlevison> | LinkedIn
<http://ca.linkedin.com/in/marklevison> | Facebook
<https://www.facebook.com/agilepainrelief>
Certified ScrumMaster Training: Vancouver
<http://agilepainrelief.com/courses/vancouver> | Edmonton
<http://agilepainrelief.com/courses/edmonton> | Ottawa
<http://agilepainrelief.com/courses/ottawa> | Montreal
<http://agilepainrelief.com/courses/montreal> | Toronto
<http://agilepainrelief.com/courses/toronto>
Certified Product Owner & Private Training also available ~ Our Training
Schedule <http://agilepainrelief.com/courses/certified-scrum-agile-training>
Agile Pain Relief Consulting <http://agilepainrelief.com/> | Notes from a
Tool User <http://agilepainrelief.com/notesfromatooluser>
Proud Sponsor of Agile Tour Gatineau Ottawa <http://goagiletour.ca/> and Agile
Coach Camp Canada <http://agilecoachcampcanada.wordpress.com/>

**Comment by mlevison** [comment]
It happens less often now, I've still seen a couple of instances in the
past 48hrs. Will share a link when I next get a repro.

Cheers
Mark

On Wed, Apr 13, 2016 at 9:30 AM, Mark Levison <mark@mlevison.com> wrote:

>
>
> On Wed, Apr 13, 2016 at 7:01 AM, noinnion <notifications@github.com>
> wrote:
>
>> please try the latest beta v4.3.1_beta
>>
>> https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.1_pro-beta.apk?raw=true
>>
>> try to turn off "Save data traffic" in Settings->Offline Reading
>
>
> ​Done. Give me a week or so to see if the problem reoccurs.
>
> Cheers
> Mark​
> [image: headshot-square-300x300]
> <http://www.flickr.com/photos/36331075@N00/9674877046/> *Mark Levison* | 1
> (877) 248-8277 | Twitter <https://twitter.com/mlevison> | LinkedIn
> <http://ca.linkedin.com/in/marklevison> | Facebook
> <https://www.facebook.com/agilepainrelief>
> Certified ScrumMaster Training: Vancouver
> <http://agilepainrelief.com/courses/vancouver> | Edmonton
> <http://agilepainrelief.com/courses/edmonton> | Ottawa
> <http://agilepainrelief.com/courses/ottawa> | Montreal
> <http://agilepainrelief.com/courses/montreal> | Toronto
> <http://agilepainrelief.com/courses/toronto>
> Certified Product Owner & Private Training also available ~ Our Training
> Schedule
> <http://agilepainrelief.com/courses/certified-scrum-agile-training>
> Agile Pain Relief Consulting <http://agilepainrelief.com/> | Notes from a
> Tool User <http://agilepainrelief.com/notesfromatooluser>
> Proud Sponsor of Agile Tour Gatineau Ottawa <http://goagiletour.ca/> and Agile
> Coach Camp Canada <http://agilecoachcampcanada.wordpress.com/>
>



-- 

[image: headshot-square-300x300]
<http://www.flickr.com/photos/36331075@N00/9674877046/> *Mark Levison* | 1
(877) 248-8277 | Twitter <https://twitter.com/mlevison> | LinkedIn
<http://ca.linkedin.com/in/marklevison> | Facebook
<https://www.facebook.com/agilepainrelief>
Certified ScrumMaster Training: Vancouver
<http://agilepainrelief.com/courses/vancouver> | Edmonton
<http://agilepainrelief.com/courses/edmonton> | Ottawa
<http://agilepainrelief.com/courses/ottawa> | Montreal
<http://agilepainrelief.com/courses/montreal> | Toronto
<http://agilepainrelief.com/courses/toronto>
Certified Product Owner & Private Training also available ~ Our Training
Schedule <http://agilepainrelief.com/courses/certified-scrum-agile-training>
Agile Pain Relief Consulting <http://agilepainrelief.com/> | Notes from a
Tool User <http://agilepainrelief.com/notesfromatooluser>
Proud Sponsor of Agile Tour Gatineau Ottawa <http://goagiletour.ca/> and Agile
Coach Camp Canada <http://agilecoachcampcanada.wordpress.com/>

**Comment by mlevison** [comment]
Here's another article which had trouble loading images:
http://onemileatatime.boardingarea.com/2016/05/02/value-of-points/

Cheers
Mark

On Sun, Apr 17, 2016 at 1:44 PM, Mark Levison <mark@mlevison.com> wrote:

> It happens less often now, I've still seen a couple of instances in the
> past 48hrs. Will share a link when I next get a repro.
>
> Cheers
> Mark
>
> On Wed, Apr 13, 2016 at 9:30 AM, Mark Levison <mark@mlevison.com> wrote:
>
>>
>>
>> On Wed, Apr 13, 2016 at 7:01 AM, noinnion <notifications@github.com>
>> wrote:
>>
>>> please try the latest beta v4.3.1_beta
>>>
>>> https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.1_pro-beta.apk?raw=true
>>>
>>> try to turn off "Save data traffic" in Settings->Offline Reading
>>
>>
>> ​Done. Give me a week or so to see if the problem reoccurs.
>>
>> Cheers
>> Mark​
>> [image: headshot-square-300x300]
>> <http://www.flickr.com/photos/36331075@N00/9674877046/> *Mark Levison* | 1
>> (877) 248-8277 | Twitter <https://twitter.com/mlevison> | LinkedIn
>> <http://ca.linkedin.com/in/marklevison> | Facebook
>> <https://www.facebook.com/agilepainrelief>
>> Certified ScrumMaster Training: Vancouver
>> <http://agilepainrelief.com/courses/vancouver> | Edmonton
>> <http://agilepainrelief.com/courses/edmonton> | Ottawa
>> <http://agilepainrelief.com/courses/ottawa> | Montreal
>> <http://agilepainrelief.com/courses/montreal> | Toronto
>> <http://agilepainrelief.com/courses/toronto>
>> Certified Product Owner & Private Training also available ~ Our Training
>> Schedule
>> <http://agilepainrelief.com/courses/certified-scrum-agile-training>
>> Agile Pain Relief Consulting <http://agilepainrelief.com/> | Notes from
>> a Tool User <http://agilepainrelief.com/notesfromatooluser>
>> Proud Sponsor of Agile Tour Gatineau Ottawa <http://goagiletour.ca/> and Agile
>> Coach Camp Canada <http://agilecoachcampcanada.wordpress.com/>
>>
>
>
>
> --
>
> [image: headshot-square-300x300]
> <http://www.flickr.com/photos/36331075@N00/9674877046/> *Mark Levison* | 1
> (877) 248-8277 | Twitter <https://twitter.com/mlevison> | LinkedIn
> <http://ca.linkedin.com/in/marklevison> | Facebook
> <https://www.facebook.com/agilepainrelief>
> Certified ScrumMaster Training: Vancouver
> <http://agilepainrelief.com/courses/vancouver> | Edmonton
> <http://agilepainrelief.com/courses/edmonton> | Ottawa
> <http://agilepainrelief.com/courses/ottawa> | Montreal
> <http://agilepainrelief.com/courses/montreal> | Toronto
> <http://agilepainrelief.com/courses/toronto>
> Certified Product Owner & Private Training also available ~ Our Training
> Schedule
> <http://agilepainrelief.com/courses/certified-scrum-agile-training>
> Agile Pain Relief Consulting <http://agilepainrelief.com/> | Notes from a
> Tool User <http://agilepainrelief.com/notesfromatooluser>
> Proud Sponsor of Agile Tour Gatineau Ottawa <http://goagiletour.ca/> and Agile
> Coach Camp Canada <http://agilecoachcampcanada.wordpress.com/>
>



-- 

[image: headshot-square-300x300]
<http://www.flickr.com/photos/36331075@N00/9674877046/> *Mark Levison* | 1
(877) 248-8277 | Twitter <https://twitter.com/mlevison> | LinkedIn
<http://ca.linkedin.com/in/marklevison> | Facebook
<https://www.facebook.com/agilepainrelief>
Certified ScrumMaster Training: Vancouver
<http://agilepainrelief.com/courses/vancouver> | Edmonton
<http://agilepainrelief.com/courses/edmonton> | Ottawa
<http://agilepainrelief.com/courses/ottawa> | Montreal
<http://agilepainrelief.com/courses/montreal> | Toronto
<http://agilepainrelief.com/courses/toronto>
Certified Product Owner & Private Training also available ~ Our Training
Schedule <http://agilepainrelief.com/courses/certified-scrum-agile-training>
Agile Pain Relief Consulting <http://agilepainrelief.com/> | Notes from a
Tool User <http://agilepainrelief.com/notesfromatooluser>
Proud Sponsor of Agile Tour Gatineau Ottawa <http://goagiletour.ca/> and Agile
Coach Camp Canada <http://agilecoachcampcanada.wordpress.com/>
