### ISSUE TITLE
Article display goes blank

### ISSUE THREAD

**Issue by Meower68** [noinnion/greader#122]
There are multiple things which cause the article display to go blank:

* display the article, click a link in the article (open in browser or some other app) leaving the app, then come back in; article is now blank

* display the article, rotate device from portrait to landscape (or vice versa); article goes blank

* display article, free version switches to ad, hit "back" to return to the article, article is blank

In each case, the article controls still work. I can mark the article unread, back out to the article list, tap the article and it displays again. Or I can choose to open the article in a browser and it works.

This is with recent versions, LG G3 running Android 5.1.1.

**Comment by adsamcik** [comment]
Same happens on Nexus 5 with Android 6, this gets very anoying.
It also happens when screen is turned of.

**Comment by theotherlinh** [comment]
Echoing this issue on a stock  6P on M.

**Comment by swar30** [comment]
Same on Samsung Galaxy S6

**Comment by gllorente-incubio** [comment]
Same on one plus one

**Comment by rudyych** [comment]
I am suffered exactly the same issue. I am using gReader Pro on Google Nexus 5x with stock ROM unrooted.

**Comment by nweinberg** [comment]
Happens on my Nexus 6P, and previously on my Note 3, both stock.

**Comment by arend-von-reinersdorff** [comment]
This happens on my Samsung Galaxy S5 Mini since the Android update to 5.1 (previously Android 4.4) :-(

**Comment by denychen** [comment]
I seem to only get the problem when turning on hardware acceleration. Recently, however, the article doesn't turn blank for me, but rather a static image of the article in the state before it was navigated away from. I can't interact with it, but the scroll bar does appear if I scroll around as if I were scrolling. 

Nexus 6P on 6.0.1 running version 4.2.0_pro.

**Comment by swar30** [comment]
Same here on Samsung Galaxy S6. With hardware acceleration see static
image. If turn it off things start working ok. Will try to run with
acceleration off to see if there are any noticeable performance problems

**Comment by swar30** [comment]
With no hardware acceleration scrolling is jumpy, not as good experience

**Comment by arend-von-reinersdorff** [comment]
@denychen Turning off hardware acceleration solved the problem for me. Thanks for the hint :-)

**Comment by theotherlinh** [comment]
Thanks for the tip, Deny. I too have the same issue of a static page, but I'll take that over nothing for now. Usual I just want to keep reading so not a huge deal. Still a bug though

**Comment by ajoe** [comment]
GReader is DEAD!  
Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available. 
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by noinnion** [comment]
here is the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true
