### ISSUE TITLE
Article view frozen after returning from locked state

### ISSUE THREAD

**Issue by mx4k** [noinnion/greader#123]
When an article is loaded, after locking the device and unlocking it the loaded article is frozen. I can't scroll up or down and the links aren't clickable anymore. 

Android 6.0.1 on Nexus 6

**Comment by greenify** [comment]
+1 &  confirming this behavior

**Comment by jasparagus** [comment]
I've also been having this problem. It seems to occur on any loss of focus (including app-switching) and is only solved by backing out of the article view and reloading the article.

**Comment by nweinberg** [comment]
I have this behavior as well. Anything that causes a loss of focus (task switching, the screen turning off, playing YouTube videos, pop up ads) breaks the reading view. I'm ready to buy premium just to avoid the ads, but that won't fix the other problems, but I'll commit to doing so if it'll pay to get this fixed.

**Comment by mx4k** [comment]
I think it's useless to post issues as the project is abadoned since a while now. It's sad as gReader was the best app for feedly.

**Comment by nweinberg** [comment]
That really sucks. I spend 80% of my smartphone time within this app, so it's irreplaceable. I'll use it until I can't stand the bugs anymore, or an alternative emerges. I wish there was some way to contact the developer, convince him to come back.

**Comment by ajoe** [comment]
Turning off hardware acceleration works for me.

**Comment by mx4k** [comment]
Yes it works but it ruins the whole experience for me. I switched to Palabre and happy with it.

**Comment by Dunkelmann** [comment]
Same for me.

I do hope this app is still supported.

**Comment by ajoe** [comment]
GReader is DEAD!  
Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available. 
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by noinnion** [comment]
here is the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by mx4k** [comment]
Finally, you are back! 
Is there a changelog?

**Comment by Dunkelmann** [comment]
Tried this and greader crashes on hitting the Android back button on my Samsung Galaxy Tab.

**Comment by Dunkelmann** [comment]
This should not be closed because it is a beta and the beta does not work.

**Comment by nweinberg** [comment]
Has anyone else installed the new beta? Does it work at all?

**Comment by greenify** [comment]
Tested - yes it does work... Although I just finished my migration to Palabre. Would be nice to hear a word from the developer about the planned future of this project.
