### ISSUE TITLE
Request: Open Articles with default browser (do not use feedly app browser) 

### ISSUE THREAD

**Issue by sdtbluethink** [noinnion/greader#124]
It would be great for me.

**Comment by JC-LGMS** [comment]
+1

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

try Open in Browser as Quick Action

**Comment by JC-LGMS** [comment]
Thank you ! It's way better but I prefer to have choice. Sometimes I switch over tabs to see other pages.
