### ISSUE TITLE
article will not display after switching back to article view from other app

### ISSUE THREAD

**Issue by MingchenZhang** [noinnion/greader#128]
Article will not be displayed after switching back to article view from other app. Also, after an ad is dismissed, the article view will be a blank.

**Comment by bgiaccio** [comment]
I've been seeing this as well since the last update. Rather annoying especially if it is a long article. I I see it happen across all my feeds.

**Comment by bruceheller** [comment]
Same problem, but I guess it's more a bug in the Android webview than in the application here. But anyway, still a problem, the app should be updated to support the updated webview and marshmallow.

**Comment by ajoe** [comment]
Turning off hardware acceleration works for me.

**Comment by bruceheller** [comment]
I does but makes the whole app sluggish and less responsive...

**Comment by nyn3x** [comment]
Turning off HW-accelartion works for me! +1

**Comment by SX86** [comment]
Same here. Hardware acceleration is enabled. If disabled, it works, but the app is sluggish. 

Used to work with same configuration on my previous phone, Nexus 6. Current phone is a Nexus 6P.

**Comment by machthree** [comment]
The same issue was happening to me until very recently but the latest version seems to show the text of the article but won't allow scrolling of the article (despite the "scroll bar" appearing to move) .  Using a OnePlus Two running Android 5.1.1 and OxygenOS 2.2.0 and GReader 4.2.0_pro

**Comment by machthree** [comment]
This appears to be the same issue as https://github.com/noinnion/greader/issues/122

**Comment by ajoe** [comment]
GReader is DEAD!  
Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available. 
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by noinnion** [comment]
here is the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by machthree** [comment]
I'm delighted to say that this issue has been fixed in the latest beta (on my phone at least: OnePlus Two, OxygenOS 2.2.1 = Android 5.1.1).

**Comment by machthree** [comment]
Unfortunately it's not all good news. On my Galaxy Tab S2 (Android 5.0.2) pressing the back button while viewing a news story or preview causes  the app to crash. I'd be happy to provide more information if you let me know how or what you need.

**Comment by SX86** [comment]
Seems resolved for me too! Thanks for your attention to this issue!

**Comment by noinnion** [comment]
@machthree please download the beta again. I just updated it.

**Comment by machthree** [comment]
That's great. It now works properly on both the OnePlus Two and the Samsung Tab S2. Grants very much for fixing this.

**Comment by bruceheller** [comment]
Nice to see the software still alive. The beta works perfectly!
