### ISSUE TITLE
Please release source code.

### ISSUE THREAD

**Issue by Vadammt** [noinnion/greader#129]
Due to the Issue Is development dead? #113 i think there won't come any updates.

Becouse I'm lacking of some enhancements and would be glad to have some bugs fixed **please publish the source code of this app** or continue working on it.

Though gReader is a great app, 5€ is a too much for getting no updates for nearly a year. And the website is down, too.

**Comment by klonamy** [comment]
I think to make it an open source project is great.

**Comment by ajoe** [comment]
GReader is DEAD!  
Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available. 
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by sknull** [comment]
Maybe someone writes a snail mail or nice postcard to the address from the google play store :)

**Comment by whatinthenameofgod** [comment]
@ajoe Thank you for the suggestion! I've been downloading and trying alternatives for a few weeks and nothing's been as attractive to me as greader. That is until I read your post. I LOVE Palabre! Been using it all morning. Just joined the beta community and paid for the premium. 

Uninstalling greader as I type this. Good riddance to a flaky developer!

**Comment by noinnion** [comment]
here is the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by sknull** [comment]
Hello,
is this some automed reply or are you still with us Noinnion? it would be nice of you to leave at least some words of clarification regarding the future of this to those pe<plo who he been willing to pay once.
Can we expect anyrhing more soon or is this software abandoned and dead now as some of us assumed?

Regards,
Steph

**Comment by noinnion** [comment]
you can see the changes for 4.3.0 beta here
https://github.com/noinnion/greader/tree/master/beta

**Comment by sandimschuh** [comment]
> Maybe someone writes a snail mail or nice postcard to the address from the google play store :)

Here is the address from play store, if someone wants to try to contact him/here. But I doubt that it is still valid.
noinnion@gmail.com
Börnestraße 36, 13086 Berlin
