### ISSUE TITLE
Horizontal scrolling for Github pull requests is only doable in baby steps while in web view

### ISSUE THREAD

**Issue by whimboo** [noinnion/greader#13]
When I switch an article to the web view, and it is larger than the current screen size of my phone, there are no scrollbars shown and I cannot scroll the page horizontally. Instead gReader want to switch to the next article. This is annoying when you have long lines of text, which you cannot read that way. A good example are the feeds from github for pull requests. Just try to check the code and scroll on such a page.

**Comment by noinnion** [comment]
Please try latest version, otherwise reopen the issue
