### ISSUE TITLE
Scrolling stops working

### ISSUE THREAD

**Issue by garethjudson** [noinnion/greader#133]
I open an article
then switch to another application,
i can no longer scroll the article up or down. 

If a full screen google ad displays after i dissmiss the advert, i get the same behaviour.

To resolve this issue i have to press back and then reopen the article.

**Comment by garethjudson** [comment]
Issue occurs on LG G3

**Comment by himphen** [comment]
Also on Nexus 5X with Android 6.0.1

**Comment by Xavver** [comment]
Same here on Nexus 6 (latest OTA). 
Only happens with activated hardware acceleration! 
But without hardware acceleration links and UI elements in the article can't be used. 
So neither of the two options works flawless...

**Comment by gruncho2004** [comment]
Same with Galaxy S6,  Nexus 4 and Nexus 6p. Fix it please.

**Comment by giccisw** [comment]
I have this issue as well. It happens on the paid version when suspending the app (locking screen, etc..)
I have seen also during normal operation but I guess it was due to onPause being called as well.

**Comment by per42** [comment]
Same on Sony z1 using paid. Typically after returning from sleep.

**Comment by langbakk** [comment]
Yup, same here, on a Oneplus One with latest OTA. Android 5 something. The scrolling locks up after full size ads, or particularly long articles (10 or more "pages"). Please fix

**Comment by MXOpentech** [comment]
also occurs on oneplus 2 almost every time switched back from another app, the list view screen would frozen.

**Comment by ajoe** [comment]
GReader is DEAD!  
Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available. 
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by noinnion** [comment]
here is the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by garethjudson** [comment]
The posted beta appears to have resolved this issue. Thanks for the update! 
Please let me know if you would like me tho test any other resolved bugs in the beta app.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
