### ISSUE TITLE
Controls stop working

### ISSUE THREAD

**Issue by eiredrake** [noinnion/greader#139]
There are occasions (listed below) where all of the pop up controls, article scrolling, as well as links and videos embedded in an article in an RSS feed will stop responding. The only way to get them to work again is to back out of the article I'm reading entirely and go back in. After that all of the controls work normally and I can scroll again. If for example there are multiple embedded videos and I click on the first to play it, I cannot then use the second one at all. Auto-play videos (I hate those anyway but they happen on occason) immediately screw up the controls every time I go into the article and thus make the article unreadable.

I've been noticing this for a while now. I used to use greader on my iPhone and didn't have this problem. Now that I'm on a droid I'm running into this issue almost every time I use greader.

To clarify I'm referring to all the pop up controls that appear when you touch the screen in an article. The 'chrome' button, the share button, the services button, the 'R' button, the next post button, the back button, full screen button, and the plus and minus buttons. But I'm also talking about scrolling down to read an article and activating any embedded videos or links to other articles (such as referral links for citations).

This happens a lot in the cracked.com feed but I think I see it there most just because it is the feed I read the most. I've also had it happen on Phys.org, Wonk Room, Daily Kos and others so I don't thik it is a specific feed being screwed up somehow.

It appears to happen after one of the following:

- Click on an embedded video to play it (doesn't matter if I actually watch it)

- Click on an embedded link that loads another page.

- Randomly while I am reading an article if I take a long time.

- After my device times out and locks itself.

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true
