### ISSUE TITLE
Request: Immersive Full-Screen Mode support

### ISSUE THREAD

**Issue by alexchan420** [noinnion/greader#142]
It would be great if greader could also support immersive full screen mode like google play books.
http://developer.android.com/training/system-ui/immersive.html

If more freedom is provided for user in order to enable this features or not, greader could be more modernized in some ways. Please consider it.

Thank you.

**Comment by mariozhivago** [comment]
They have it now but how not to have it?

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
