### ISSUE TITLE
Thumbnails mismatch

### ISSUE THREAD

**Issue by stdu00** [noinnion/greader#143]
Since today thumbnails displayed next to articles are not correct. In the article thé images are OK.
Thé

**Comment by noinnion** [comment]
do you use feedly? could you please look into feedly online and see if they show wrong images too?

**Comment by stdu00** [comment]
Hi,
Checked and no problem using feedly, pictures are good.
I clear cache but still some thumbnails mismatched.
Thx
Stéphane

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by stdu00** [comment]
Hi,
No more problems with the beta.
Thx for your work your app is great.
Stéphane
