### ISSUE TITLE
Article link is changed so that new link leads to 404 page

### ISSUE THREAD

**Issue by lattenwald** [noinnion/greader#146]
Feed in question is http://www.chainfire.eu/?mode=rss

Its entries link to Google Plus, such as https://plus.google.com/+Chainfire/posts/8WB78xvY2oM . greader replaces "+" in link with "%20", which is understandable but doesn't work with Google+.

I suggest not replacing "+" in links as a fix.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
