### ISSUE TITLE
Beta 7 crashes

### ISSUE THREAD

**Issue by Hiermur** [noinnion/greader#147]
Hello, 

beta 7 shows only the standard icons of the feeds and when I open an article the app crashes. 
I use the old reader.

**Comment by noinnion** [comment]
could you send me the log after it crashes
 Help & Feedback -> Feedback -> Send log

**Comment by Hiermur** [comment]
I've sent you a mail with the log. Beta 8 doesn't crash, but the feed icons are still the rss standard icons.

**Comment by Hiermur** [comment]
I've sent you a mail with the log. Beta 8 doesn't crash, but the feed icons are still the rss standard icons.

**Comment by Hiermur** [comment]
I've sent you a mail with the log. Beta 8 doesn't crash, but the feed icons are still the rss standard icons.

**Comment by noinnion** [comment]
could you send me a screenshot?
