### ISSUE TITLE
How to exit full screen mode on greader pro 4.2.0

### ISSUE THREAD

**Issue by mariozhivago** [noinnion/greader#148]
The new update full screen mode is kind annoying..

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta again
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

settings->look and feel

**Comment by mariozhivago** [comment]
Thank you so much for the prompt reply and for giving the option to exit the full screen :+1: :)
