### ISSUE TITLE
Double images in article view

### ISSUE THREAD

**Issue by timwood** [noinnion/greader#149]
Since the latest update (released 4/9/2016) an image displays in feed view at the top, above the article and title and also is duplicated below where it's supposed to be in the article.

**Comment by LaughingJohn** [comment]
I noticed this tootoo!

**Comment by jdaverth** [comment]
Yes, same here except i only get the image above the title, which is the one i do not want. I want the image to be inline like it was before the update but there is no setting to change this. Was this a deliberate design decision? I don't like it.

**Comment by noinnion** [comment]
please try the latest beta v4.3.1_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.1_pro-beta.apk?raw=true

Change log: https://github.com/noinnion/greader/tree/master/beta
- 3D Touch for thumbnails (long tap on thumbnails to show them immediately,
release will close it)
- Improved list item swiping
- Improved article view, prevent duplicate images

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
