### ISSUE TITLE
Not so easy to open in browser. 

### ISSUE THREAD

**Issue by LaughingJohn** [noinnion/greader#151]
Before the latest update the little world icon used to open the article in the browser. It now seems to open in the built in Web view (not sure of the technical term). You can then open in browser via the menu, but this is a pain as you have to wait for the page to load. 

I'd like the old behaviour back, or at least a way to configure it. I often open in browser because the Web view built in doesn't always render correctly.

**Comment by ameer1234567890** [comment]
Same here. Please add option to disable chrome custom tab.

**Comment by noinnion** [comment]
settings - reading preferences - article controls

**Comment by LaughingJohn** [comment]
Thank you!
