### ISSUE TITLE
Swipe to return back to articles list

### ISSUE THREAD

**Issue by Clynton79** [noinnion/greader#152]
It would be great if you could swipe to return to the articles list.

**Comment by noinnion** [comment]
it is possible with v4.3.0

**Comment by Clynton79** [comment]
I'm running 4.3.0 Pro

There is no option to swipe to return to the articles list, the only swiping options in the settings are:

Reading preferences >  Article view > Article controls > Navigation gestures > the only option is for Previous/Next article, in fact, I have selected Disable for both left and right and I am still able to swipe between articles

Look and feel > Article list > Quick actions > Swipe actions (BETA) > neither of the swipe actions have that option

I have been using gReader for a number of years now, I'm certain that there was an option some time back, but it was withdrawn at some point. I started to use double tap to return to the articles list, but it is not as natural as swiping.

**Comment by noinnion** [comment]
in article view, swipe from left edge. it will show you the article list.
(phone only)

**Comment by Clynton79** [comment]
Ok, I can see what the issue is now. You have to swipe from off-screen or pretty close to the edge of the screen, I was trying to swipe from the middle of the screen, which works fine in the articles list but not in an actual article. I can see this being an issue for someone that has a case where the front of the case is a bit thicker and doesn't allow your thumb to swipe close enough to the edge of the screen. Thank you for the prompt replies and for a great app.
