### ISSUE TITLE
Swipe actions are hard to trigger

### ISSUE THREAD

**Issue by ayemooth** [noinnion/greader#154]
The latest update seems to have made it so that I have to swipe further to trigger a swipe action than used to be the case, making the difficult to perform.

**Comment by noinnion** [comment]
please try the latest beta v4.3.1_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.1_pro-beta.apk?raw=true

Change log: https://github.com/noinnion/greader/tree/master/beta
- 3D Touch for thumbnails (long tap on thumbnails to show them immediately,
release will close it)
- Improved list item swiping
- Improved article view, prevent duplicate images

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
