### ISSUE TITLE
Back Button Functionality

### ISSUE THREAD

**Issue by whatinthenameofgod** [noinnion/greader#157]
Please, for once and for all, fix the back button. There are a few items on the uservoice site begging for it.

The back button, according to Android standards, should function the exact same way the up button, present in your app, should. If you click an article on the widget and navigate within a few links, hitting back should NOT take you out of the app unless you are on article view or the very first screen of an item.

"**When the previously viewed screen is also the hierarchical parent of the current screen, pressing the Back button has the same result as pressing an Up button**—this is a common occurrence. However, unlike the Up button, which ensures the user remains within your app, the Back button can return the user to the Home screen, or even to a different app."

**Comment by noinnion** [comment]
normal behaviour is to read a site and return to article list. if you want
to go back there is a button above zoom buttons.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
