### ISSUE TITLE
Move browser control settings to "settings->reading preferences"

### ISSUE THREAD

**Issue by schneemaier** [noinnion/greader#158]
Pre versiion 4.3 pressing the browser icon in article view opened the article in the ezternal browser. In version 4.3 the page openefinside greader. To get it open in the external btowser it takes 2 more taps.

I lookef at settings and did noy find any way to disable this new functionality. 

Pleaso provide setting to get back to the older open in browserfunctionality

**Comment by noinnion** [comment]
settings->reading preferences->article controls

**Comment by schneemaier** [comment]
Thanks, i was unable to find it :)

I think this should be 1 level higher in settings->reading preferences. As this more the control of the application behavior then article controls

**Comment by alvintc** [comment]
I had to create an account to say thanks for this. I too couldn't find this setting or any notes on this in the changelog.

**Comment by schneemaier** [comment]
Edited the tittle to reflect the change in the request to move the browser setting from "settings->reading preferences->article controls" to "settings->reading preferences"

**Comment by noinnion** [comment]
The problem is that I also want it to be accessible in article view: Menu->Article Controls
