### ISSUE TITLE
gif not displayed automatically after version 4.3

### ISSUE THREAD

**Issue by snufkinto** [noinnion/greader#159]
gif not displayed automatically after version 4.3. User need to click on it to display.

**Comment by noinnion** [comment]
please try the latest beta v4.3.1_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.1_pro-beta.apk?raw=true

Change log: https://github.com/noinnion/greader/tree/master/beta
- "3D Touch" for thumbnails (long tap on thumbnails to show them
immediately, release will close it)
- Improved list item swiping
- Improved article view, prevent duplicate images, gif issue

**Comment by snufkinto** [comment]
Thx. I have tried and that bug is fixed.
However, I would like to tell you that the list item swiping is not solved
yet. It is still more difficult to use compared with version 4.2.

Thx anyway.

(P.S. I has been contributing the traditional chinese translation)

2016-04-13 5:53 GMT+08:00 noinnion <notifications@github.com>:

> please try the latest beta v4.3.1_beta
>
> https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.1_pro-beta.apk?raw=true
>
> Change log: https://github.com/noinnion/greader/tree/master/beta
> - "3D Touch" for thumbnails (long tap on thumbnails to show them
> immediately, release will close it)
> - Improved list item swiping
> - Improved article view, prevent duplicate images, gif issue
>
>

**Comment by noinnion** [comment]
please try the latest beta v4.3.1_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.1_pro-beta.apk?raw=true

is it possible to make a video?

**Comment by snufkinto** [comment]
Thx. The swipe problem is fixed in
v4.3.1 beta 2
<https://github.com/noinnion/greader/commit/c51cb455dafb22a134d93f8efcb24afc297c0caf>
.

2016-04-13 16:13 GMT+08:00 noinnion <notifications@github.com>:

> please try the latest beta v4.3.1_beta
>
> https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.1_pro-beta.apk?raw=true
>
> is it possible to make a video?
>

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
