### ISSUE TITLE
Some images are not shown in Cache view.

### ISSUE THREAD

**Issue by whimboo** [noinnion/greader#16]
This is similar to issue #12 but for the Cache view. I have instructed gReader to always download the full article for offline reading. In most articles of my feeds images are missing. This can even vary in an article itself. So some images are visible and others not.

**Comment by whimboo** [comment]
I tried it since your reply and I don't see any changes. The option you mention here is not activated.

**Comment by noinnion** [comment]
try the latest beta v4.0.4beta
http://noinnion.com/greader/updates/

**Comment by whimboo** [comment]
Nothing has been changed with the 4.0.4pro release. Images are still not shown, but now it's even worse. The above mentioned small images in articles of the Tagesschau are not presented with really huge placeholder boxes. That means you have to scroll a lot until you get to the first content.

**Comment by noinnion** [comment]
Have you tried reinstalling the app??

**Comment by whimboo** [comment]
Interesting that a reinstall makes things better. Shouldn't this also work without it? It seems that all images are shown now, beside the before mentioned social media icons, which now have a really huge placeholder and are kinda annoying.

**Comment by whimboo** [comment]
Today I have seen some missing images for articles in the DNN-online feed: http://www.dnn-online.de.

**Comment by noinnion** [comment]
What Android version do you have? Is Storage permission enabled?
Settings->App->gReader->Permissions

please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by apatternjugglers** [comment]
Hi.
Android Versions 5.1 on Phone and 6.0 on Tablet, and both running the latest beta.
Storage permissions are on in both cases - screenshots attached.
![screenshot_2016-04-03-10-56-45](https://cloud.githubusercontent.com/assets/1109424/14229626/14632884-f98c-11e5-972e-c4e1abc3215d.png)
![screenshot_2016-04-03-10-56-41](https://cloud.githubusercontent.com/assets/1109424/14229627/1465b75c-f98c-11e5-9172-f33eb76d9e7d.png)
![greader pro_20160403_110008](https://cloud.githubusercontent.com/assets/1109424/14229628/1467a2ce-f98c-11e5-95fd-e1246ea7154a.png)
![greader pro_20160403_105946](https://cloud.githubusercontent.com/assets/1109424/14229629/14691fbe-f98c-11e5-8b6c-7c2ea3ed9a35.png)
![package installer_20160403_110049](https://cloud.githubusercontent.com/assets/1109424/14229625/1460d318-f98c-11e5-90b0-5f849af5f1c3.png)
![screenshot_2016-04-03-10-55-41](https://cloud.githubusercontent.com/assets/1109424/14229630/146c286c-f98c-11e5-8da1-655a5a61a8c5.png)

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta again
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by apatternjugglers** [comment]
Hi, thanks for the reply.
Have tried the beta from the link provided just above (on both phone and tablet), and am still getting the same results.
It's not a _huge _deal, it just means there a few feeds where I need to read the Feed view to get the image (and sometimes first paragraph), and then move to the Cache view to get the rest of the full content.
Thanks.

**Comment by noinnion** [comment]
there are websites where images are not recognised. Use Normal Page as
Offline Format instead for these feeds.
