### ISSUE TITLE
When set for WiFi-Only, synchronization started on WiFi should stop as soon as phone switches to mobile internet

### ISSUE THREAD

**Issue by paulvancotthem** [noinnion/greader#161]
**I just discovered that gReader consumed 1.5GB of my 2GB mobile data plan today, because a background synchronization which started in my home over WiFi did not stop when I left my home and my phone automatically switched from WiFi to mobile internet, while the sync was still ongoing.**

My gReader settings are all set to "WiFi-Only" wherever such an option is offered:
- auto-update feeds is set to WiFi-Only
- sync on startup is set to WiFi-Only
- Offline usage (BETA) is set to WiFi-Only
- Load images is set to WiFi-Only

Android 6.0.1 on Nexus 6P

**Comment by nweinberg** [comment]
I have this issue, too. Nexus 6p on Marshmallow, Greader Pro.
