### ISSUE TITLE
Long-press Chrome icon should open in external browser.

### ISSUE THREAD

**Issue by kevin1979** [noinnion/greader#162]
I'm actually really liking the new integrated chrome pages when tapping on stories. However one suggestion I have is a shortcut to make the story open in the full Chrome app via long-pressing the chrome icon. This would save a couple taps as well as save from reaching to the top right menu with your thumb. Thanks for reading.

**Comment by noinnion** [comment]
please try v4.3.1

**Comment by kevin1979** [comment]
Thank you so much for your responsiveness! Feature works perfectly. I'm even more glad I paid for Pro.

**Comment by pearson** [comment]
It would be nice to have an option to make the full Chrome app launch on a tap of the icon. I find that I quite often want to share the articles I open in the integrated browser, and that integrated browser lacks a share button. I end up having to open the article in the full Chrome browser to share it. (I'd rather share the link to the article itself than a link to the RSS link.)
