### ISSUE TITLE
Hide search button

### ISSUE THREAD

**Issue by imqqmi** [noinnion/greader#163]
I use the greader pro app on a tablet, in mobile mode. I use the load new articles button and mark as read buttons. I often hit the search button. The nexus 7 2013 touch screen isn't very accurate so it's not anyones fault really but would really like to be able to turn off the search button at the top. Either that or triple the button spacing.
Thanks!

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
