### ISSUE TITLE
Podcast streaming doesn't work when audio URL contains spaces

### ISSUE THREAD

**Issue by nareksaribekyan** [noinnion/greader#164]
Podcast streaming doesn't work when audio URL contains spaces in Android 5.x.
After clicking the stream button the player does nothing, the audio duration is shown as 0.
However, the podcast is available using the download option, or through web view.

**Comment by noinnion** [comment]
could you posts some examples, also feed url
Am 14.04.2016 6:15 vorm. schrieb "nareksaribekyan" <notifications@github.com

**Comment by nareksaribekyan** [comment]
Example feed url: http://vem.am/home/ajxcontent/podcast/53/

Screenshots: 

https://goo.gl/photos/fWLiXaiRnU8m2BUy9 
https://goo.gl/photos/5kvYaZXGT8GoJ7Cu8
