### ISSUE TITLE
Can't disable reading mode

### ISSUE THREAD

**Issue by Jimbo66ca** [noinnion/greader#167]
I've been through the help screens and settings several times and I can't seem to turn off reading mode when I open an article from my list.

**Comment by klo2k** [comment]
Have you checked feed preference?

**Comment by Jimbo66ca** [comment]
That did it! You have to long press on your feed, select Preference, and then under Reading Mode, change the value from Default to **Off**.
I wonder if this was a recent change, as this has only been happening in the past few months.  I'd just gotten used to flipping out to Chrome to read the original article/watch the video.
