### ISSUE TITLE
Feed view offline image not cached - broken image icon

### ISSUE THREAD

**Issue by klo2k** [noinnion/greader#168]
Since the 4.3.0 update, images in feed view doesn't seem to cache (display offline) anymore; I get a broken image placeholder icon instead.

The images still aren't cached even after viewing the post online first in feed view.

Steps to replicate:
1. Open an article from, for example, http://www.engadget.com/rss-full.xml
2. Go offline 
3. Reopen the same article - broken image placeholder icon displayed 

"Full content format" is set to "Simplified" 
"Cache feed images" is checked 

I've tried clearing Articles and Image cache but it didn't help.

"CACHE" view works OK though.

I'm on a G3 D855 with Candy SiX rom (Marshmallow), gReader pro 4.3.1.

Happy to provide more info - let me know what you need.

**Comment by cubei** [comment]
Can confirm.

**Comment by lattenwald** [comment]
Images are not cached for offline view in uploadvr.com feed, I feel this belongs here.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
