### ISSUE TITLE
App Update

### ISSUE THREAD

**Issue by denno020** [noinnion/greader#169]
The latest app update removed the shortcut icons from my homescreen and also reset all of my settings within the app.. Really uncool man

**Comment by noinnion** [comment]
Really? what version do you use? do you update from basic to pro version?

**Comment by denno020** [comment]
I've been using Pro for quite some time. It did it on both my phone and
tablet.

I'm on version 4.3.1 now, which I'm assuming is the latest.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
