### ISSUE TITLE
Video playback doesn't stop when navigating away

### ISSUE THREAD

**Issue by whimboo** [noinnion/greader#17]
When a post has a video included and you watch it via the 'web' tab, it is not paused/stopped when you navigate to the next feed.

**Comment by whimboo** [comment]
HW acceleration I have enabled for a long time now. So that should not be the problem.

**Comment by noinnion** [comment]
try the latest beta v4.0.4beta
http://noinnion.com/greader/updates/

**Comment by whimboo** [comment]
So I had to wait a while until I noticed this problem again in a feed. So this is still present in the final 4.0.4_pro.

Steps I have here:
1. Add the following feed: http://www.nachdenkseiten.de/?feed=atom
2. Look for the article: "Landgrabbing in Kambodscha – NachDenkSeiten Spezial"
3. Read the article and scroll to the very end
4. Click the link "eine Kopie unseres Films auf YouTube"
5. Start playing the video and wait some seconds
6. Swipe to the next article
7. If video stopped playing go back to 5) and retry

It might be that this problem is not visible immediately and you need 2 or 3 tries. But then it always happens for me.

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by whimboo** [comment]
Sorry that I currently cannot test everything immediately. I checked that now and the last release 4.3 doesn't fix the problem. I still see it in the web view for the Tagesschau feed.

**Comment by noinnion** [comment]
Please try latest version, otherwise reopen the issue
