### ISSUE TITLE
Feature request: save different sort options for unread/all articles

### ISSUE THREAD

**Issue by virtualdj** [noinnion/greader#172]
Is it possible to have different saved options for the 2 modes of the switch on the top toolbar, i.e. a set of settings when the switch is on **Unread articles only** and another for **All articles**?

I'm asking because normally I use the unread articles view sorted by oldest items; but when sometimes I mark as read and refresh an article that I want to re-read, it would be great to have the **All articles** view sorted by newest items (so the newer read are at the top).

I know it's just a click of a button, but it's easier if the app remembers these couple of settings, IMHO.
Thank you!

**Comment by cubei** [comment]
I have the same use case, so having this feature would be nice.
