### ISSUE TITLE
Multiple gif viewing issue : the solution has already been included in previous version, but disappeared in 4.3.1_pro !

### ISSUE THREAD

**Issue by LetTheMusicFlow** [noinnion/greader#173]
Viewing articles with several animated gifs is awful because the animations are displayed very slowly, and some are frozen, even on powerful phones , and hardware acceleration changes nothing.
The solution appeared in the previous version : the images were not loaded , instead a box indicating "gif" was displayed, and when the box was pressed, the animated gif was loaded and displayed in full-screen. It was perfect!
But this feature has disappeared in 4.3.1_pro version of greader !!!
Please , could this feature be implemented as an option in the next version ? So users could choose to show or not the gifs, at their convenience ?

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
