### ISSUE TITLE
Default browser settins are ignored (bug).

### ISSUE THREAD

**Issue by DreamNik** [noinnion/greader#174]
Articles always being opened in "Internet" app, no matter what default browser is set. This started to happen after one of the last updates.

**Comment by derekja** [comment]
Furthermore, with this change "open in browser" open in the app rather than an external browser. This is very detrimental to the reading experience. I would like a return to the previous behavior where open in browser launches a new instance of the default web browser.

**Comment by MyLittleTardis** [comment]
Yes! Please please please return that feature, or at least offer an option to make that the default. I want "open in browser" to open a new browser instance rather than the onboard browser. I used that feature frequently, and now have to go through the extra step of "Open in Chrome" to get there.

**Comment by Luca2903** [comment]
Yes please

**Comment by noinnion** [comment]
you xan turn off Custom Chrome app in Menu-Article Controls
Am 15.05.2016 8:18 nachm. schrieb "Luca2903" <notifications@github.com>:
