### ISSUE TITLE
List order bug 

### ISSUE THREAD

**Issue by Luca2903** [noinnion/greader#177]
Hi. I use folders to group the feeds, but, if I'm on "all feeds" at the "home screen" (this only happens when using group by feed), the list of news/feeds showed on the right, is actually organized by the "main feeds" order (the list of main feeds appear when we ask the app to ignore/not show folders). 

Is it possible to backup the subscription options? Order, format, reading mode, etc..

thanks for the great app

**Comment by noinnion** [comment]
How should it be grouped?
Am 15.05.2016 8:17 nachm. schrieb "Luca2903" <notifications@github.com>:

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
