### ISSUE TITLE
Cached articles only contain cookie information

### ISSUE THREAD

**Issue by whimboo** [noinnion/greader#178]
If you subscribe to the feed for http://www.fujirumors.com/ and enable offline reading in greader, all downloaded full articles only contain the legal cookie information but nothing more. That somewhat started recently, so not sure if it was a gReader update or if something changed on the website. I hope that this can be fixed.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
