### ISSUE TITLE
Youtube (maybe others) autoplaying, cannot stop or nav away

### ISSUE THREAD

**Issue by drjdaverth** [noinnion/greader#189]
Started only recently (perhaps a week?).  Any feed item containing an embedded Youtube video will autoplay the video (modal window or external link depending on defaults).  I can dismiss the modal, but it pops right back up so can take several tries to nav away from that item.

Hardware: Samsung SM-G900a (AT&T Galaxy S5, USA)
Android Version: 4.4.2

**Comment by Ack0** [comment]
It's happening here too.
Zenfone 2 (5.0.1)

**Comment by superbonaci** [comment]
Happening here too.

**Comment by koonyook** [comment]
+1
is there an option to disable video autoplay?

**Comment by ChocoSmith** [comment]
Same, nexus 6.0.1 full version. it's starting to get expensive reading my feeds.
If I swipe it will start on the next screen also. Please revert to how it was

**Comment by ChocoSmith** [comment]
Just to add, it's easy to reproduce in Engadget

**Comment by jdaverth** [comment]
> If I swipe it will start on the next screen also. 
Yes, thanks for pointing that out.  Swiping to the next item 'really quickly' does no good since the video just starts playing over the next feed item.

**Comment by emelarnz** [comment]
+1. gReader 4.3.1_pro. Nexus 5x. Marshmallow. Disabling in-app browser and in-app YouTube doesn't seem to help.

**Comment by colmbuckley** [comment]
This is destroying the app's usability. Hope it gets fixed soon.

**Comment by jdaverth** [comment]
More than a month since the original issue was opened and not even an acknowledgement of the bug.  At this point, I'm starting to think it is a feature.  Has anyone else jumped to another reader yet?  I'm looking for recommendations.

**Comment by Razunter** [comment]
> Has anyone else jumped to another reader yet? I'm looking for recommendations.

I think I tried them all and this one is the best. Unfortunately. Lost of bugs and imperfections in this one.

Best reader I've used was Mr. Reader on iOS, nothing as good on Android.

**Comment by superbonaci** [comment]
The last app update on the Google Play Store is from 14th April 2016. I don't know if this developer is active anymore or if something happened to him. I would start to look for an alternative.
What about the official Feedly app?

**Comment by colmbuckley** [comment]
> Has anyone else jumped to another reader yet?

I had previously never found one which did everything I liked in gReader Pro, but with this bug driving me crazy I took the plunge and installed Palabre (https://play.google.com/store/apps/details?id=com.levelup.palabre) which I'm finding to be really good. Take a look.

**Comment by superbonaci** [comment]
Thanks @colmbuckley, trying out Palabre.

**Comment by Razunter** [comment]
Tried Palable, not good enough :/

**Comment by superbonaci** [comment]
@Razunter why's that?

**Comment by Razunter** [comment]
@superbonaci don't remember all annoyances, but you can't pin feeds panel on left. I browse hundred news a day and good feeds navigation is necessary.

**Comment by superbonaci** [comment]
I like Palabre, I'm premium now!

**Comment by paour** [comment]
Funny that I had just come back to greader from Palabre, frustrated with its lack of updates and small issues, like the inability to read grouped by feed, or the useless footer suggesting other items in your feeds, or the inability to keep a feed unread without going back to the list...

**Comment by Tezi** [comment]
I also just come back to greader. Because I was unable to make offline cache work in Palabre. Even in article where it shows "This article is available offlibe." With button "Show" and after pressing show it just write error about availability.

**Comment by superbonaci** [comment]
gReader still works perfectly. Just when the video appears hit the back button.

**Comment by valentinomiazzo** [comment]
+1

**Comment by vakasoft** [comment]
I hate the auto play ... please make one option to disable

**Comment by Matth7878** [comment]
+1

**Comment by superbonaci** [comment]
Maybe the developer is dead guys, it's been missing for a while.

**Comment by WCityMike** [comment]
Disappointed to see no fix, but I'm unsurprised -- I believe I remember the developer saying somewhere that this is a dead project.  (Credit that with all the weight of a third-hand vague remembrance, i.e., none.)

That having been said, one suggested workaround: use the volume buttons, as opposed to a finger swipe, to scroll previous-next.  It does not seem to trigger this bug.

**Comment by vakasoft** [comment]
I hate this . Disable the autoplay please

**Comment by ChocoSmith** [comment]
Stopped when I upgraded to android 7.o

**Comment by sweca** [comment]
Not here. Still autoplay when I upgraded to android 7.0 and the newest. Im doing a claim in google store, I have purchase this buggy app!

**Comment by superbonaci** [comment]
What alternative is for iOS?

**Comment by Razunter** [comment]
@superbonaci Mr. Reader

**Comment by superbonaci** [comment]
@Razunter thanks!

**Comment by superbonaci** [comment]
@Razunter Mr. Reader is a crap, does not allow to add my Feedly account.

**Comment by Razunter** [comment]
@superbonaci It was good, but looks like it's discontinued now. From official site: "September 2016: I stopped iOS development and removed all apps from the App Store."

**Comment by askearitza** [comment]
I just saw here that I am not the only one despairing over this. I can't believe this is going on. It's annoying as hell and so easy to fix.

**Comment by wilransz** [comment]
This is really annoying. I am a Pro user. It doesn't matter whether you opt to play videos in-app or through YouTube. It has to be app related since loading videos isn't as nervous with Feedly.

**Comment by sweca** [comment]
I'm a Pro user to but emigrate to Inoreader. Greader was the best rss reader but the video bug take i down from the throne.

**Comment by superbonaci** [comment]
@sweca Inoreader from Innologica?

**Comment by sweca** [comment]
yes, Inoreader from [Innologica](https://play.google.com/store/apps/details?id=com.innologica.inoreader&hl=sv).

**Comment by mcongom** [comment]
+1, please fix this annoying bug!

**Comment by superbonaci** [comment]
Inoreader does not support importing from Feedly.

**Comment by Razunter** [comment]
@superbonaci you can export OMPL from Feedly and import it in Inoreader.

**Comment by superbonaci** [comment]
@Razunter yes but each time I modify the list on feedly I've got to reimport. Just prefer to use the feedly app directly.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
