### ISSUE TITLE
Fever API support

### ISSUE THREAD

**Issue by alesnav** [noinnion/greader#19]
Hello there!

What do you think about supporting Fever API?

This API is public. I mean, supporting this, gReader will support all RSS servers which use Fever API, like miniflux.

The docs are public, too, in here: http://feedafever.com/api

Thanks!

**Comment by tapir** [comment]
Is there any work going on for this?

**Comment by noinnion** [comment]
Duplicate with https://github.com/noinnion/greader/issues/406
