### ISSUE TITLE
Captions for images containing quote character get truncated

### ISSUE THREAD

**Issue by domingos86** [noinnion/greader#197]
At least on the feed view (reading an article) and long pressing an image and selecting "view caption", if such caption has any quote character `"`, the text that gets shown on the dialog gets truncated until the first such quote. So if the caption was originally `abc"def"` we only get to see `abc` unless we open the article with the browser.

**Comment by DoHe** [comment]
I know this is quite minor for most peopöe, but I imagine I'm not the only one that uses rss feeds to read web comics and there it really is quite an important feature. Would be great if this would get fixed.
