### ISSUE TITLE
Sometimes cache link is not visible in article view

### ISSUE THREAD

**Issue by whimboo** [noinnion/greader#2]
I have already reported that via email but I think its better to have it listed as an issue, so others might collaborate if they are affected by the same issue. 

So what I experience is that under special conditions the Cache link is not visible in the article view. It happens randomly and not that often. so by default I let gReader download all articles across all my subscribed feeds. And it seems when the Wifi network is not that reliable, the download still happens but some flag is not set. So opening the article view doesn't list the given Cache link. When I swipe to the next article in the list, the link is visible. And it also becomes visible for the original link when I swipe back. Other steps to make it visible is to go back to the list view and enter the article view for the same article again.

Not sure what I could do to further investigate that problem.

**Comment by whimboo** [comment]
Sorry for being late here. I think you asked while the 4.0.3 was in beta. So I tested this with the official 4.0.3 release and yes, I still see this behavior.

Also when I see this problem, I can click on 'Web' and the 'Cache' link will appear immediately. I assume it is a screen resolution problem, and you might have a larger resolution than me on the Samsung S4 mini?

**Comment by noinnion** [comment]
and now?
try the latest beta v4.0.4beta
http://noinnion.com/greader/updates/

**Comment by whimboo** [comment]
No changes here either with the 4.0.4pro release. But I feel it is really the problem with the feed name overlay. This problem can easily be seen for feeds with a long name. Cropping of it doesn't happen and seem to overlay the `Cache` link, which makes that one invisible. Tapping on e.g. `Web` corrects that problem and the cropping is applied.

**Comment by cubei** [comment]
I have a similar report here:
[https://groups.google.com/forum/?#!msg/g_reader/nPUqUw54Tk0/HEuC5W70AwAJ](https://groups.google.com/forum/?#!msg/g_reader/nPUqUw54Tk0/HEuC5W70AwAJ)

![cache2](https://cloud.githubusercontent.com/assets/2197875/17747386/edb9069c-64b4-11e6-92c3-9193d9aa2122.gif)
As you can see in this gif the workaround for me is to refresh the view with a tab on "feed".

**Comment by noinnion** [comment]
Closed for now, if it still happens in latest version 5.1.2, please reopen it again. Thanks
