### ISSUE TITLE
In card view - font size randomly changes

### ISSUE THREAD

**Issue by talios** [noinnion/greader#20]
I'm noticing ( 4beta2 ) that when in the new card view, the font size seems to randomly change on an entry as I scroll thru. I have the app set to Tiniest font size.  I don't think I've noticed this issue when using a larger font size.

**Comment by noinnion** [comment]
try the latest beta
http://noinnion.com/greader/updates

**Comment by martynhaigh** [comment]
I'm still seeing this issue on 4.3.0_pro

**Comment by noinnion** [comment]
Closed for now, if it still happens in latest version 5.1.2, please reopen it again. Thanks
