### ISSUE TITLE
Every YouTube video opens twice

### ISSUE THREAD

**Issue by Razunter** [noinnion/greader#202]
Every YouTube video opens twice (opens second time after closing modal\switching from YouTube app). Very annoying.

Tablet: Google Pixel C.
Android v6.0.1

**Comment by paour** [comment]
And just touching (not tapping -- down but no up) a YouTube video launches it.

**Comment by jdaverth** [comment]
This is related to https://github.com/noinnion/greader/issues/194 and https://github.com/noinnion/greader/issues/189.  Neither has been acknowledged (almost a month later) and it is making the app fairly unusable.

**Comment by alliedcvil** [comment]
Yep, this issue is incredibly frustrating.

**Comment by WCityMike** [comment]
Disappointed to see no fix, but I'm unsurprised -- I believe I remember the developer saying somewhere that this is a dead project. (Credit that with all the weight of a third-hand vague remembrance, i.e., none.)

That having been said, one suggested workaround: use the volume buttons, as opposed to a finger swipe, to scroll previous-next. It does not seem to trigger this bug.

**Comment by vakasoft** [comment]
I hate this . Disable the autoplay please

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
