### ISSUE TITLE
Images don't display

### ISSUE THREAD

**Issue by scottybrown** [noinnion/greader#203]
I'm using greader in offline mode. It used to download a whole article images and all. But nowadays it only downloads the top image (the one in the preview) and not the rest.
Most of my feeds are from kinja based sites like jalopnik and kotaku, so it's possible the issue is limited to those sites. But it's an issue nonetheless.

**Comment by scottybrown** [comment]
I'll try to clarify here.
It seems to worked very sporadically. If I open a feed with Wi-Fi on, it will download all the preview images and the full articles for just 10 or so of the most recent articles. But it won't get all of the images.
When it syncs without being open it seems to miss some articles (not get the full article) and miss some preview images (though it loads an image in the full article). And never get _all_ the images.
It's hard to put my finger on, it seems so random. But it's gone from being amazing for offline access to being nearly useless.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
