### ISSUE TITLE
Thumbnails in list view are not cached for offline view.

### ISSUE THREAD

**Issue by cubei** [noinnion/greader#206]
The images for the rich article list are loaded when online (or only via wifi depending on settings) one by one if needed. They are not loaded ahead of time with the normal sync. This means offline access is not possible.
I expect to sync all the articles in wifi and then later when offline to go through the list including the thumbnails.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
