### ISSUE TITLE
Two way sync is not working correctly for starred items

### ISSUE THREAD

**Issue by cubei** [noinnion/greader#207]
When my gReader is syncing automatically or when I manually sync all items, I get new items and items that I read on another server are removed from my unread list.
So this is the normal behavior for two way sync, read status is synced from server to app and the other way.

For starred items star status is synced as well. When I star an item on my computer and sync the app, the item appears in my starred list. If I unstar the item on my computer and sync the app, the star on that item is gone as well. So again normal behavior for two way sync.
BUT there is one problem: Although the item is now unstarred in the app, it still appears in the list of starred items.
So when I click on "starred items" in the app, I see now about 20 items without a star. The button is called "starred items", why do I see items that are not starred??? The articles aren't removed for the automatic sync or the "manual sync all". I have to be in the starred list and sync there to clean up the list.

So the two way sync is working somehow, but the starred list is not cleaned up for the normal syncs, like the unread list is.

The reason for this behavior is the settings under cache "auto cleanup read items". I don't have it set to instantly, but to 3 days, so I can access read items in case I remember something the next day.

The expected behavior is:
- star/unstar is synced from server to app and the other way around. This is working.
- When I click on "starred items" I get a list with only items that are starred. This is not working, because I see items without a star.

The clean up of the starred items list is working when I manually sync from the starred items list, but not for the normal list.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
