### ISSUE TITLE
Sources request 

### ISSUE THREAD

**Issue by Perksy91** [noinnion/greader#209]
Hello! Long time user, thanks for everything.  So for example, I subscribe to nytimes.  The reading mode messes up the article. Same with Mashable.  I am probably doing something wrong, but is there a way to pick how each source loads?  Like - open in chrome for nytimes, all else opens with reading mode unless I change setting?  Thanks!

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
