### ISSUE TITLE
Marking articles as read when scrolling past them seems broken

### ISSUE THREAD

**Issue by muelli** [noinnion/greader#21]
In earlier versions, i.e. 2.8.4, I could have articles marked as read when scrolling past them in the articles list.  Interestingly, it does work when using the volume buttons, but not when doing "regular" scrolling.  I am experiencing this with 4.0.1.

**Comment by noinnion** [comment]
press on the title and enable MArk read on scroll

also try the latest beta v4.0.3beta
http://noinnion.com/greader/updates/

**Comment by muelli** [comment]
hm. Can you clarify what you mean by "press on title"?  The title of an article in the article list?  Then I get the options to "mark read", "mark read until here", "keep unread", etc.

**Comment by noinnion** [comment]
press on title in actionbar

**Comment by muelli** [comment]
ah. okay. I see. The very top.  For some reason, I need to be very careful when clicking the action bar, because it fullscreens the application very quickly.

**Comment by 700saikumar** [comment]
Hi,

I have the same problem, can you please tell me where i can find the actionbar ?
Trying to see the option "mark as read on scroll"

Thanks.

**Comment by noinnion** [comment]
click on the title in actionbar. it will popup the options
