### ISSUE TITLE
Image overlay stuck over app

### ISSUE THREAD

**Issue by jonaswashe** [noinnion/greader#217]
Holding finger over thumbnail while performing other actions can result in a state where the image overlay is stuck over the app preventing further action.

**Comment by jonaswashe** [comment]
Note: This occurs when the the image overlay appears at the exact same moment an article is opened. Returning to the article list displays a stuck image and the app is then unresponsive.

**Comment by sorgo** [comment]
I am experiencing this when scrolling the list of articles. Randomly but frequently there is an image overlay stuck when I hit the thumbnail while scrolling. Only fix is to use back button to close the app and restart
