### ISSUE TITLE
No scrollbar in cache, Web or feed view

### ISSUE THREAD

**Issue by PerfectSlayer** [noinnion/greader#22]
Hi, 

I'm very happy with greader but I face an annoying issue. I have no scrollbar when reading an article whatever the view I use (cache, Web of feed). 
It's quite useful to have an overall idea of the article length before starting to read it. 

I'm the only one? I'm on Nexus 6 with stock 5.0.2 rom. 

Thanks.

**Comment by giwu37** [comment]
No, you are not the only one. I have a Nexus 5 (5.0.1) and Nexus 7 (2013, 5.0.2) and I am dealing with the same problem.

**Comment by PerfectSlayer** [comment]
Thanks for the reply!
I hope @noinnion is aware of the issue =/

**Comment by giwu37** [comment]
I hope this, too. But I'm afraid they are not. Because this is the only report on this issue on the whole internet ;-)

**Comment by PerfectSlayer** [comment]
Yes, I did the search and found nothing…
I hope we are enough to get attention of the dev ;)

**Comment by noinnion** [comment]
Could you please send a screenshot. i could not reproduce the issue.

**Comment by giwu37** [comment]
It's a little difficult to show something that is missing ;-)
When you have a long text in the rss feed that you have to scroll to read on there is normally a small grey marker on the right side of the screen which shows you the text position. This marker is missing.

**Comment by PerfectSlayer** [comment]
@noinnion I could do better ;) https://www.youtube.com/watch?v=r_Zk5Kk3lrU
You could see there is no scrollbar when I read the article.

**Comment by giwu37** [comment]
I can add some more information: yesterday evening I used the "invert page" feature. Then you can see the sliding bar again. Seems to be a problem with colour settings.

**Comment by PerfectSlayer** [comment]
Right, when I use black theme and and "Feed" view, I got a black background for the article.
And then, I succeed to see a scrollbar which looks white.
It has barely the same color than white background of article, that's should be why we can't see it…

@noinnion Is there a way to change / force color of the scrollbar to make it visible on white bakground?

**Comment by PerfectSlayer** [comment]
No news about this issue?
I still don't have scrollbar :disappointed:

**Comment by giwu37** [comment]
Especially annoying when you switch from white on black to black on white in the morning. Inverted is still my workaround - and not more!

**Comment by giwu37** [comment]
Just a little push. I think there are other problems with higher priority now.

**Comment by giwu37** [comment]
I thought the newest update would fix it. But the scroll is still as white as possible ;-)

**Comment by PerfectSlayer** [comment]
Still no scrollbar for me neither.. Even with the last update :sad:

**Comment by giwu37** [comment]
The new Beta 4.1.3 seems to solve the scrollbar problem.

**Comment by PerfectSlayer** [comment]
Thanks you for the fix! Can't wait to test it :)
