### ISSUE TITLE
Request: Open Articles directly with default browser (do not use feedly app browser) 

### ISSUE THREAD

**Issue by Filo90** [noinnion/greader#220]
it would be great

**Comment by chronocrossminh** [comment]
Totally argee

**Comment by reflechant** [comment]
It's the only thing i want to be changed. Currently you need to make too many taps to finally open the article in default browser.

**Comment by pghant** [comment]
+1 on this. This is the only thing missing for me with this app now.

**Comment by dx8519** [comment]
Agreed.
