### ISSUE TITLE
News article URL gets truncated when  it's coming from Google Alerts RSS feeds

### ISSUE THREAD

**Issue by jsimon1080** [noinnion/greader#222]
When you set a Google Alert to create an RSS feed and then add it in gReader, everything works fine except when the news article URL is too long. It gets truncated, which makes it impossible to open the article in a web browser.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
