### ISSUE TITLE
I cannot minimize feeds into sub categories on my android tablet.

### ISSUE THREAD

**Issue by neonpyra** [noinnion/greader#223]
Is this a missing feature or are we able to change the settings for this? I paid $5 for this app itd be nice to continue using with the convenience i expected. Though its not a big deal i just like to view certain feeds for only what im in the mood for. I thought the paid version of the app would have all features similar to the feedly chrome extention.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
