### ISSUE TITLE
Widget disappeared when on Sd card

### ISSUE THREAD

**Issue by WilliamSiemons** [noinnion/greader#226]
After moving app to  Sd card, widget is gone from screen as well as widget list (so you can't create a New widget. Must be a bug...

**Comment by WilliamSiemons** [comment]
On Sony Xperia Android

**Comment by yosnoor** [comment]
Same behaviour here. I have an xperia, too. Even if you move the app back to internal storage, the widget isn't available. The only way to get it back is to uninstall and reinstall.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
