### ISSUE TITLE
Still issues with tagging.

### ISSUE THREAD

**Issue by sysadm01** [noinnion/greader#229]
When tags are selected for an article and saved, and then when open tags again, completely different set of tags appears to be selected.

**Comment by noinnion** [comment]
Closed for now, if it still happens in latest version 5.1.2, please reopen it again. Thanks

**Comment by mcl1234567** [comment]
The issue happens ( again )
I save an article with two tags ( tag1 & tag2 ) and when I open tag3 , I have this article.
