### ISSUE TITLE
After disabling HW acceleration no article content is shown

### ISSUE THREAD

**Issue by whimboo** [noinnion/greader#23]
If you disable the HW acceleration during a session and do not restart gReader, no content in articles is shown. The whole page stays empty. Only article views are affected here, and not the feed list or anything else. Also this is not a problem when enabling HW again. In this case no restart is necessary. The content is still visible right after doing this switch.

**Comment by whimboo** [comment]
This issue has been seen with version 4.0.4_pro.

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by noinnion** [comment]
Closed for now, if it still happens in latest version 5.1.2, please reopen it again. Thanks
