### ISSUE TITLE
Read aloud reading an irrelevant article

### ISSUE THREAD

**Issue by andreascons** [noinnion/greader#232]
I am a paid user and I rely on this app daily, as I am driving, to read my feeds to me. In the last few days, though, when I select "Read Aloud" on any feed, it reads the title and then an article (in Spanish, I think), the same article every time, whatever the feed. Please provide a solution ASAP, as I rely on this app, which I paid for.

**Comment by otrapersona** [comment]
Paid user here. This happens to me to, it pulls news in Portuguese or sometimes the same one every time. it started around a week ago

**Comment by alfredodiaz** [comment]
This happens to me several times during the last week. Each time I have to close greaderPro and queue the articles again.  For some strange reason it reads aloud this article: [O Maestro Griot do Canão](http://www.anf.org.br/o-maestro-griot-do-canao/)

> Antes de trabalhar com comunicação e produção cultural, sou MC. O ponto de partida que me levou até aqui foi a música, mais precisamente o rap. Nada melhor e mais justo que estrear minha coluna na Agência de Notícias das Favelas falando sobre o rap e a cultura hip hop, que fazem parte da minha vida – cultura essa que desperta a potência de vários jovens nas favelas e periferias do Brasil. Sou só mais um a quem o hip hop deu asas e vou falar de um dos mestres que o gênero eternizou por aqui.
> 
> No último dia 17, foi lançado um dos discos mais aguardados do rap brasileiro. Batizado com o nome do próprio artista, “Sabotage” é o legado que o “Maestro do Canão” deixou não só para o rap, mas para a música brasileira.
> 
> Créditos: Reprodução / Revista Trip As rimas tem em torno de 13 anos e se encaixaram com instrumentais da atualidade, produzidos por grandes nomes como Tropkillaz e Daniel Ganjaman. É extraordinário como parece que foi ontem que Mauro Mateus dos Santos rimou aqueles versos, com aquela técnica. Saber que muito desse material foi gravado no dia anterior ao de seu assassinato mostra como o roteiro da vida é de arrepiar. O jornalista e colaborador da ANF Daniel Velloso falou mais sobre o disco também aqui.
> 
> Sendo o hip hop uma cultura de matriz africana que se consolidou nos guetos do Bronx, bairro predominantemente negro nos Estados Unidos, percebemos como os MCs que realmente representam essa cultura são como griots. Os griots são conhecidos em algumas partes da África como os responsáveis por contar as histórias e passar adiante as tradições de seu povo através da fala.
> 
> Créditos: Reprodução Internet Isso não é muito diferente do que os selectas dos soundsystems jamaicanos fazem até hoje através de gírias e expressões. Aliás, foram esses mesmos soundsystems que fizeram a cabeça do DJ Kool Herc, que voltou ao Bronx e mostrou como se fazia em Kingston. As festas tanto de dancehall como de rap também não são muito diferentes dos bailes funk daqui. Ou seja, tudo está linkado através da ancestralidade.
> 
> Entender esses valores e conceitos é fundamental para o prosseguimento e expansão da cultura hip hop. O momento sociopolítico brasileiro, que inevitavelmente se reflete no rap, se mostra propício para um lançamento do Sabotage. Só reforça a narrativa do rap, que tem sua raiz nas favelas brasileiras e que se permite ocupar outros espaços, como o próprio Sabota fez ao atuar em filmes e participar de programas de TV.
> 
> Rap e comunicação, compromisso por aqui.
> 
> Nyl de Sousa é MC, produtor cultural, estagiário da Agência de Notícias das Favelas e escreve às sextas-feiras.

**Comment by optical10** [comment]
I've opened this & other (see above) "Voice-reading" over the last year, with no response, so i'm not hopefull even as a paid user it will get a dev response here.

**Comment by klengyel** [comment]
I've encountered the same issue during the recent days. Here a picture about the original article 
![screenshot_20161117-064652](https://cloud.githubusercontent.com/assets/18306735/20378162/97efd088-ac94-11e6-80ef-02247f98ad11.png) and the voice reading screen 
![screenshot_20161117-064702](https://cloud.githubusercontent.com/assets/18306735/20378187/c7d565d8-ac94-11e6-8233-14f20a3854b4.png)

It happened that during the day sometimes it worked, but mostly it loads different article. With saved articles it also seems to work, however I believe the voice reading is a strong feature of the Pro version, so it should to be fixed.

**Comment by dcdruck** [comment]
I'm not even sure this is strictly related to text to speech because I've had a similar issue the last week or two when I double tap to expand the article (to load the whole article in the app for reading). When I double tap it now loads an unrelated article. The same untested article loads regardless of what article I double tapped on.

**Comment by dcdruck** [comment]
Perhaps mine is unrelated after all because I saw this bug https://github.com/noinnion/greader/issues/231

However, it's curious that both issues started around the same time. Maybe the read aloud feature first sent the page to readability and then read that, which would explain both issues.
