### ISSUE TITLE
Application restart on heavy cached or web articles

### ISSUE THREAD

**Issue by netnazgul** [noinnion/greader#234]
Every now and then application hangs and then restarts when reading through a long article or an article with several images. All previously read articles are reset to unread state (which is itself very annoying). 
Started several weeks ago or so. Probably after a fix of cached articles not caching the whole page.

Can provide any possible feedback.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
