### ISSUE TITLE
Articles with embedded vimeo video do not show video output

### ISSUE THREAD

**Issue by whimboo** [noinnion/greader#24]
Seen with gReader 4.0.4pro. If you have an article with an embedded video from Vimeo there is no graphical output. The area stays black.

Steps:
1. Add the following feed: http://www.nachdenkseiten.de/?feed=atom
2. Look for the article: "Landgrabbing in Kambodscha – NachDenkSeiten Spezial"
3. Try to play the video at the top in gReader

**Comment by Mateopato** [comment]
I'm having this issue as well. Videos on engadget do not play either (I think they use an AOL video player).

**Comment by noinnion** [comment]
Please try latest version, otherwise reopen the issue
