### ISSUE TITLE
Some feed not synchronize

### ISSUE THREAD

**Issue by leoncoolmoon** [noinnion/greader#240]
Some feed synchronize on my old phone,but not on my new phone.ie http://www.ozbargain.com.au/deals/feed

**Comment by birdjumper** [comment]
Same here. Not all feeds, just some. Fixes I have tried:
- Unsubscribing and re-susbscribing to a non sync-ing feed
- Clearing the app cache
Neither of the above make any difference ...
What can I try next?
Thanks

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
