### ISSUE TITLE
Is this project still supported at all

### ISSUE THREAD

**Issue by mcdragonsi** [noinnion/greader#245]
There seem to be no updated to any of the noinnion apps. The noinnion website still seems to work (or started working again).
Who is in charge of the apps anyway?

**Comment by hadim** [comment]
If the author does not want to support the project anymore, could it open source it so the community can take care of it ?

**Comment by OsakaBoi** [comment]
I think you guys should try out FeedMe, has similar cached offline reading and is actively being developed (last update was 29th Dec. 2016). https://play.google.com/store/apps/details?id=com.seazon.feedme&hl=en

**Comment by mcdragonsi** [comment]
Nope I'm afraid. Does not seem to support self-hosted rss aggregate systems
like TTRSS.

**Comment by andyd0** [comment]
Funny.  I was about to post the same thing.  There several bugs that have been an issue for some time that need addressing.  Not sure what the alternatives are but probably time to start looking for them

**Comment by psycholyzern** [comment]
Any other good alternative?

**Comment by andyd0** [comment]
Seems like feedme is the way to go for now.

**Comment by ajh3000** [comment]
Flym is pretty good, and is open source.  
https://github.com/FredJul/Flym

There is also spaRSS which is a fork of Flym (I haven't tried it yet)
https://github.com/Etuldan/spaRSS

Both are on the app store.

I really like gReader but it's currently broken so had to look elsewhere.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
