### ISSUE TITLE
Feeds don't sync anymore 

### ISSUE THREAD

**Issue by Gurgelhupf** [noinnion/greader#246]
Hi, I was always happy with the app. Just a little while ago I bought the pro version. Now, all of a sudden, with no apparent reason, tbe feeds don't sync anymore. What can I do?

**Comment by noname30** [comment]
have the same issue

**Comment by mistergreens** [comment]
Same issue as well. At or after 2:30pm EST yesterday the 10th all of my feeds stopped updating.

**Comment by Vyacheslav-1** [comment]
Similarly. To earn the channels, you need to re-add them all. The same can not be so many. Where a developer? Why silent?
(Аналогично. Чтобы каналы заработали, нужно заново их все добавить. Это же невозможно такое количество. Где разработчик? Почему молчит? )

**Comment by Gurgelhupf** [comment]
OK,  I solved it this way: Export your feed list to an OPML file, then delete all your feeds,  then  import the OPML file again.  I hope  this will  last a while...

**Comment by Vyacheslav-1** [comment]
The perfect solution. I also helped

**Comment by Gurgelhupf** [comment]
Too bad,  but the same error reappeared just after a few hours and then again after I did the export-delete-import procedure. I think I shall uninstall greader and look for another feed reader ( I tried FeedX reader which is nice except for the ads you can't avoid).

**Comment by psycholyzern** [comment]
This is sad. I couldnt find any other good feed reader like greader.

**Comment by Vyacheslav-1** [comment]
If someone finds a better reader than Greader tell us too, please

**Comment by hadim** [comment]
The ideal would be to have this one released as an Open Source project so everyone could make it better !

**Comment by GhostWhisper3010** [comment]
hadim is right. Does anyone else agree?

**Comment by psycholyzern** [comment]
I use greader to sync feed every 5minutes. I couldnt find any oher alternative that have the same short interval.

**Comment by psycholyzern** [comment]
I took a peek into greader connection and.found out it is using Google Feed API. Unfortunately google shutdown the service (https://developers.google.com/feed/). That is why greader wont work anymore until the dev fixed it.

**Comment by astraetech** [comment]
Same here -- no syncing, spent 30 mins today working on this. And i just paid for the Pro version! Where are the devs??

**Comment by Gurgelhupf** [comment]
It works if you connect to feedly. But if you don't want to give information about what you read to another data leech, you cannot use gReader any more. Sad.

**Comment by astraetech** [comment]
Well, the 100 feed limitations on Feedly is  BS; that's why I was using local feeds anyway. I don't see a reason for Feedly at all to be honest, if the feeds can be pulled and organized by a local client. Is this true that greader can no longer work solo? Then everybody who paid for the PRO should ask for a refund from the devs.

**Comment by psycholyzern** [comment]
How you did it @Gurgelhupf ? Login with Feedly and thats it? Because I already did that yesterday and still new entries wont show.

**Comment by TheBigDogz** [comment]
psycholyzern, Try this:
1.  Export your RSS list to an OPML file within gReader.
     
       - This option is not obvious to find.  It is under "All Items" > Subscriptions > Manage Resources >OMPL Export (via the "3 dots" icon on the right hand side).
    
       - The file is located /sdcard/gReader/OPML_2017XXXXXXXXX.xml (X is time stamp).

2.  Sign in Feedly and import the OMPL file (The OPML_2017XXXXXXXXX.xml file above).  Check to make sure that you have all the feeds in Feedly.
3.  "Clear cache" in gReader and make sure that you select "complete" in this step.
4.  Logout of gReader
5.  Start gReader and login via Feedly.

**Comment by psycholyzern** [comment]
I simply clear app data and login via Feedly. Then add rss I want.
Greader still broke on me.
I will give it another try with your method TheBigDogz. Thanks

**Comment by GhostWhisper3010** [comment]
I don't want to abandon gReader, so I don't want to do that. Also, your 
technique may be as useless as trying to use Birdie94's "unlock 
everything" cheat code for State Of Emergency 2, as far as I'm concerned.

**Comment by TheBigDogz** [comment]
GhostWisper3010, I don't want to abandon gReader either.   In this case,  gReader abandoned us.  With the approach outlined,  you are still using gReader. 

Sorry,  I am not familiar with your "cheat code"  reference.   Care to elaborate?

**Comment by psycholyzern** [comment]
Hey @TheBigDogz it is working! Thanks. I dont care if it use Feedly, I just want it to sync every 5minutes xD.

**Comment by GhostWhisper3010** [comment]
The State Of Emergency 2 cheat code that I mentioned was tried out by a 
Youtuber named BlondeGuyGamer who was expecting to have an effective 
cheat code that claimed he would get "100% completion of the game" in 
effect, after he got pissed off for no way of completing the game's 
"Mystery Objectives". He stated that in his Youtube video "'They Made A 
Sequel?': State Of Emergency 2" (You can find the video here: 
https://rivercitygamers.com/2016/05/26/they-made-a-sequel-state-of-emergency-2-ps2-review/). 
I feel like I may be having that same effect as BlondeGuyGamer had with 
that cheat code when I would ever try to use your complex method. I 
understand your good intentions, but unlike you, I don't think that 
gReader "abandoned" us and will continue to hold onto the app more and 
more.

**Comment by BarDick** [comment]
Thanks for the solutions but as I think the dev have to fix the problem. What for I paid?

**Comment by TheBigDogz** [comment]
I agree that the Dev should fix the problem.   Since the last update was in April in 2016, we will continue to patiently wait.   Until then,  the "conplex"  6 steps detailed above,  which,  by the way, anybody can do,  can serve as an intermediate solution for those who continue to hang on to gReader,  including myself.

**Comment by BarDick** [comment]
Agree but have no endless patience. 
Any way thanks for the solution.  Did so cause like this app too much.))

**Comment by BarDick** [comment]
Agree but have no endless patience. 
Any way thanks for the solution.  Did so cause like this app too much.))

**Comment by bonelli** [comment]
Same issue here, is there a +1 button somewhere here?

**Comment by gram7gram** [comment]
gReader pro stoped sync approximately 08.01.2017. Autosync does not yield results, opening feed in browser results in "uriString" toastr and browser is not opened.

Feed source is at http://xxx.com/feed?access_token=xxx. Manual copy/paste to browser results in undisplayed in gReader items.

Some public feed sources, when I click "open in browser", for several seconds are displayed as "blocked by browser". Then it is redirected to requested feed.

Such symptoms...

**Comment by lutomas** [comment]
I had this problem too that LOCAL RSS feeds stopped syncing.
By reading posts in other languages I found suggestion and it worked for me.

1. I have reinstalled gReader Pro (I have deleted 'greader' folder from device storage from previous installations, but this might be not mandatory).   
2. During installation I have removed flag 'Optimized sync'.

Thats it. Works for me. I hope that can help you too.
![1](https://cloud.githubusercontent.com/assets/145708/23410920/8264375e-fdd9-11e6-8bc1-50868140314a.png)
![2](https://cloud.githubusercontent.com/assets/145708/23410923/85e9d64a-fdd9-11e6-820f-b0f910a12d4d.png)

**Comment by user113** [comment]
@lutomas Lol it works, but you just need to delete the application data and cache, and then follow your instructions. I recommended backup the preferences and export the opml before, in a save location.
TY!

**Comment by ogradame** [comment]
@lutomas  It helps. Later synchronize there too. But the big but: downloaded and marked as read messages for the current  day are downloaded and appear again and again.

**Comment by gram7gram** [comment]
Thank you, @lutomas. Re-installation without Optimized sync helped restore application glory.

**Comment by GhostWhisper3010** [comment]
@lutomas I did back up my gReader, but lost different articles/videos from 2016 and/or 2015 in the process. Could you ask the devs restore these missing articles/videos from 2015/2016 using a patch, please?

**Comment by joelmdev** [comment]
No need to reinstall. Logout, then log back in, select RSS Reader (Local), click 3 dots, deselect "Optimized Sync".  Sources should still be present.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue

**Comment by FeiLZX3Km** [comment]
> I had this problem too that LOCAL RSS feeds stopped syncing. By reading posts in other languages I found suggestion and it worked for me.
> 
>     1. I have reinstalled gReader Pro (I have deleted 'greader' folder from device storage from previous installations, but this might not be necessary).
> 
>     2. During first start I have removed flag 'Optimized sync'.
> 
> 
> Thats it. Works for me. I hope that can help you too.
> 
> ![1](https://cloud.githubusercontent.com/assets/145708/23410920/8264375e-fdd9-11e6-8bc1-50868140314a.png) ![2](https://cloud.githubusercontent.com/assets/145708/23410923/85e9d64a-fdd9-11e6-820f-b0f910a12d4d.png)

Yes yes!  U r right, thx!
