### ISSUE TITLE
Wrong encoding of the cached articles

### ISSUE THREAD

**Issue by Malachiasz** [noinnion/greader#248]
Since a month cached articles are presented with the wrong charset. That makes articles in German hard to read because German characters like  ä, ö, ü are showed incorrectly.

**Comment by thw0rted** [comment]
I believe this is still happening. It's not just an issue for foreign languages either - "smart quotes" are also stored as two characters, resulting in gibberish displayed e.g. in place of the apostrophe in a contraction. It's been bothering me for a while but I finally took the time to reproduce it reliably.

**Comment by Malachiasz** [comment]
I think author has abandoned the project. I use now "Flym". It's not comprehensive app as greader, but works reliably and has options to download load whole articles on wifii in order to read them later. https://play.google.com/store/apps/details?id=net.fred.feedex&hl=en

**Comment by thw0rted** [comment]
I think you're probably right about abandoning it (or maybe they just don't have time for it lately?) but your suggested app isn't going to help me -- I really need something that syncs with Feedly.  The encoding issue is annoying but not enough to make me give up on Feedly integration.

**Comment by kiron777** [comment]
Try Feedme. Similar to Greader with Feedly integration. Gets updated regularly.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
