### ISSUE TITLE
Incorrect layout on tablet Huawei M3

### ISSUE THREAD

**Issue by tmysik** [noinnion/greader#253]
Hello,
I love your application but recently I switched to a new tablet Huawei Mediapad M3 and the layout of the application is incorrect - instead of one for tablets, one for phones is used (M3 has 1600 x 2560 pixels (2K?) display resolution I believe).

Thank you!
Tomáš

**Comment by kiron777** [comment]
That can be changed in settings under "Look and feel". I use a tablet but prefer the mobile setting.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
