### ISSUE TITLE
gReader STILL ISN'T SYNCHRONIZING PROPERLY!

### ISSUE THREAD

**Issue by GhostWhisper3010** [noinnion/greader#254]
C'mon, devs. Please fix the feeds. Please give us those videos and articles that I missed and then the ones that I'm supposed to get later on.

**Comment by GhostWhisper3010** [comment]
Am I alone on this issue?

**Comment by Dolphin3303** [comment]
No, you are NOT alone. I even tried going bAck to an older version of gReader that I had backed up as an apk file ... still nothing. 

Which does make me wonder it the issue is an Android permission problem (I didn't notice the problem until I was pushed the Android 7.0 update...) or if there is some communication breakdown between the app servers ...

**Comment by Reagankm** [comment]
I'm having this same problem. Happy to send logs if that helps

**Comment by Dolphin3303** [comment]
Hmm. I am leaning f towards the issue being new "battery boost" features in the Android 7.0 update. I turned off BATTERY OPTIMIZATION  (Settings > power > battery optimization --> all apps, uncheck Optimize battery in gReader section).

Further testing is needed but it has synced twice since I disabled this. 

If others can test & verify...and maybe the developers can then add a note in app or in Google Play

**Comment by Dolphin3303** [comment]
Greader seems to be syncing everything properly for me ever since I turned off the stupid Battery Optimization feature in the Android 7.0 update. Hope same is happening for others.

**Comment by GhostWhisper3010** [comment]
I just got a notification from gReader, but the articles still aren't there. I think the devs better fix that problem right away.

**Comment by Haz3lnut** [comment]
No. Turning off battery optimization does not resolve the issue. 

It appears that feedburner feeds sync properly, but individual feeds like http://rss.slashdot.org/Slashdot/slashdot will not sync.

PLEASE FIX!

Thank you.

**Comment by GeraldSoellinger** [comment]
I have the same problem with Android 5.1 . 

I currently use only the local RSS reader (since a month, free version).

Please fix it, since the app would exactly can what I have searched for.
Thank you in advance.

**Comment by GhostWhisper3010** [comment]
I keep getting videos from the Mass Effect Youtube channel, but articles or videos from my other gReader subscriptions STILL aren't being synchronized properly. For the gReader devs at noinnion,please get off your case, get your act together and actually fix the free gReader app. Thank you.

**Comment by lutomas** [comment]
I had this problem too that LOCAL RSS feeds stopped syncing.
By reading posts in other languages I found suggestion and it worked for me.

1. I have reinstalled gReader Pro (I have deleted 'greader' folder from device storage from previous installations, but this might not be necessary).   
2. During first start I have removed flag 'Optimized sync'.

Thats it. Works for me. I hope that can help you too.

![1](https://cloud.githubusercontent.com/assets/145708/23410920/8264375e-fdd9-11e6-8bc1-50868140314a.png)
![2](https://cloud.githubusercontent.com/assets/145708/23410923/85e9d64a-fdd9-11e6-820f-b0f910a12d4d.png)

**Comment by dsteinschneider** [comment]
@lutomas - THANK YOU! - uninstall greader - went to Android Settings -> Manage Applications -> gReader Pro -> delete all application data. Then go to the store and download and install gReader -> RSS Reader Local -> uncheck "Optimized Sync" and all my feeds sync as they should

**Comment by didierCH** [comment]
@lutomas thank you. Your tip solved the problem for me.

**Comment by AkikoOrenji** [comment]
Thanks lutomas. 

also fixed it for me. Not sure why this option is so hidden when re-installing. you have to expand the breadcrumb to find this option upon re-install. I registered here just so i can confirm this fixes the terrible sync issues.

**Comment by generalredneck** [comment]
Fyi you can get to that interface by simply logging out... that worked for me... no uninstalling or deleting needed.

**Comment by Jackhford** [comment]
I just can't get these tips to work. I have 3 devices on which I use Greader pro and I want all my feeds to be same on all. I downloaded the OMPL file which is stored in /storage/emulated/0/gReader and placed it in the same folder on another devices hoping Greader Pro would simply read it on start. No such luck. I can't find a way to import the OMPL. I also cited the backup file from one device to another and did a restore, but no feeds. I also tried @lutomas' solution, but that didn't work either. I'm hoping someone has figured this out.

**Comment by MrMoxy** [comment]
Same problems here after many good Years before upgrading to Galaxy s7. Developers seems unresponsive and/or uninterested, sadly.

**Comment by Dave-G-K** [comment]
Just want to add that deselecting Optimized Sync has solved the problem for me
Thanks lutomas

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
