### ISSUE TITLE
(Please read.) Hey, noninnon. We need to talk.

### ISSUE THREAD

**Issue by GhostWhisper3010** [noinnion/greader#259]
I am fed up with the fact that I'm not getting any new articles or videos on my end. Please find a way to patch gReader In a way that you can solve that Issue so I will not be inconvenienced on the gReader app ever again.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
