### ISSUE TITLE
Switch to Webview does not always work

### ISSUE THREAD

**Issue by giwu37** [noinnion/greader#26]
Since some days the Website Button does not work every time I want to use it. I found out that switching back to the overview then back to the article and then clicking the Website Button helps.
Could be a problem with the updated WebView in Android itself (some other developers are reporting/updating).

**Comment by giwu37** [comment]
Oh. As I write there comes the update to 4.1.2. But this one is not fixed.

**Comment by neclepsio** [comment]
Same here. See also https://groups.google.com/forum/m/#!topic/g_reader/5I0SeShK-nI

**Comment by noinnion** [comment]
Could you try the beta?
http://noinnion.com/greader/updates

**Comment by giwu37** [comment]
I downloaded the Beta. First impression is good. To confirm it I have to use it some time.

**Comment by neclepsio** [comment]
It is not fixed. I've just touched web from feed view. Progress bar filled.but no change to the view.

**Comment by giwu37** [comment]
Unfortunately I can confirm that it doesn't work. Hope you keep on trying, guys!

**Comment by neclepsio** [comment]
Please reopen this bug; it's not fixed.

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by neclepsio** [comment]
Installed, thank you. I will let you know as soon as possible. I noticed
the error can sometimes be related to full screen advertising. After it's
shown, the error always happens.
Il 31 mar 2016 2:13 PM, "noinnion" <notifications@github.com> ha scritto:
