### ISSUE TITLE
Search and Search Filters Not Working

### ISSUE THREAD

**Issue by cydhaselton** [noinnion/greader#263]
Example:
Searching for the exact phrase "The A.V. Club" returns 0 results, even though there are numerous articles with that phrase in the All Items view.

The existing filter (created without quotes) does not display all items with The A.V. Club in the title.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
