### ISSUE TITLE
YouTube Videos Automatically Open YouTube App

### ISSUE THREAD

**Issue by denno020** [noinnion/greader#265]
When browsing through my feeds, if i encounter an article that has a YouTube video embedded, then the YouTube app will automatically open and start playing the video.
This is ESPECIALLY annoying when that YouTube video is an ad.
This problem has been happening for quite a while, but I've only just recently noticed it again because i hadn't use this app for a while, likely due to this annoying problem

**Comment by leoogh** [comment]
have been experiencing the same problem here for quite a while. Makes posts with videos in them almost unreadable.  It would be much much  better to show a thumbnail and only play the video when double tapping that. I love greader and hope a fix is coming soon!

**Comment by otstrel** [comment]
Each YouTube video in post autoplays several times which is annoying as hell. Please fix this.

Regards,

Unhappy paying customer

**Comment by uratewl** [comment]
Ditto

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
