### ISSUE TITLE
Audio not being deleted from cache

### ISSUE THREAD

**Issue by tobydjones** [noinnion/greader#267]
I have only 90 unread articles, but my cache is 11Gb!

Settings:
*Auto-cleanup 4 weeks
*Delete immediately after reading
*Download audio/video on.

If I go to explorer and find an audio file that I haven't listened to, I can go into greader, read the article, listen to the audio, and exit but the audio is not deleted.

I can also find lots of audio files I've listened to, and the article is read. These articles are not shown in greader unless I select show read and do a sync.

Is there an option to clean the cache?
If I manually delete the cache, will greader re-download unread articles & audio?

**Comment by tobydjones** [comment]
I deleted an audio file of a current unread article and it is not re-downloaded on sync.

In ES file explorer I searched for files > 1 year old and deleted those (9gb!)

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
