### ISSUE TITLE
Sidebar items stay selected even if not active

### ISSUE THREAD

**Issue by gram7gram** [noinnion/greader#276]
Priority: Minor
Type: Bug
Description:
In the sidebar there are my subscriptions. 
After sync, I click on any subscription and it becomes selected. I look through its feeds. 
I click other subscription, it becomes selected. I look through its feeds.
The selection from the first one does not disappear.
It is possible to make all subscriptions in sidebar selected.

The selection restores on activity resume

**Comment by gram7gram** [comment]
![screenshot_20170523-111333](https://cloud.githubusercontent.com/assets/8168799/26344824/9d3bff78-3fa9-11e7-8a4f-36d59017fc4d.png)

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
