### ISSUE TITLE
disallowed_useragent

### ISSUE THREAD

**Issue by TJude** [noinnion/greader#278]
Cleared Cache (to move store to SD card), and am trying to login using OAuth in Feedly Cloud.  Getting a 403 error, disallowed_useragent.  Advice?

**Comment by andrewducker** [comment]
Same here.
Logging into Feedly using Google auth no longer works.

**Comment by andrewducker** [comment]
Looks to be this issue:https://stackoverflow.com/questions/40591090/403-error-thats-an-error-error-disallowed-useragent

**Comment by chirba4** [comment]
Same issue here
Can't login to freshly cloud using Google auth

**Comment by TJude** [comment]
So, I'm resuming at this point that further development is not in the cards?  yes?

**Comment by hub2git** [comment]
I have this same problem.

**Comment by hub2git** [comment]
I have this problem too. Can anyone recommend other **offline** feedreader apps?

**Comment by kiron777** [comment]
Try Feedme. That is what I am using now . Almost as good as Greader.

**Comment by hub2git** [comment]
Send that FeedMe has a similar issue. I can't just it to log in to my
Feedly-Google account

**Comment by taschmidt** [comment]
FYI, I got around this by going to feedly.com from a desktop browser and creating an actual Feedly account. Then log out of that account, log back in with your Google account and link that Feedly account (somewhere in the account preferences screens). Then you can log into gReader using your newly created Feedly credentials and you're good to go.

**Comment by hub2git** [comment]
Thanks, @taschimdt.
> (somewhere in the account preferences screens). 

https://feedly.com/i/account/logins

**Comment by bderiso** [comment]
+1 for this issue

**Comment by ViX7** [comment]
Это действительно проблема!!!!!!! Что делать? Приложение мертвое???

**Comment by ViX7** [comment]
Без Google аккаунта в feedly не войти никак!?!

**Comment by bderiso** [comment]
Here is a workaround from taschmidt; this worked for me. Sorry I can't speak Russian :)
"FYI, I got around this by going to feedly.com from a desktop browser and creating an actual Feedly account. Then log out of that account, log back in with your Google account and link that Feedly account (somewhere in the account preferences screens). Then you can log into gReader using your newly created Feedly credentials and you're good to go."

**Comment by bmp412** [comment]
Same issue on my new tablet, trying to login via Feedly with Google account: "disallowed user agent".

**Comment by nikolayg** [comment]
Same issue here. I paid for the `Pro` version of the app and I have been unable to use it for over a month. 

Please advise on how you are planning to resolve this issue, or I will request a refund ...

**Comment by gromlix** [comment]
Can we have this fixed ASAP? Adding more accounts to feedly according to the workaround is in effect decreasing security because now there are 2 acounts which can be attacked (e.g. passwords could get lost). Thx.

**Comment by FoxBJK** [comment]
I believe it's happening because Google deprecated the login API that Feedly was using. They announced it several months ago, and it was officially killed in April.

https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html

This should've been resolved several months ago. The fact that it still hasn't doesn't make me very optimistic about a quick fix.

**Comment by gromlix** [comment]
No, it is not because feedly does something wrong. **Greader uses a now unsupported method.** It uses the Android Webview component to do the authentication. If Greader would **use the Browser (usually Google Chrome) instead**, the bug would be gone.

**Comment by leomoon** [comment]
Anybody's gonna fix this?

**Comment by TJude** [comment]
Doesn't look like anybody's going to fix it. I tried a few other readers but this one really is the best. Do what ta Schmidt says,  login to Feedly directly rather than through Google oauthf. It works just like it used to.

**Comment by leomoon** [comment]
Yea but I am a Feedly Pro user. If I login using Feedly, that means it will be another account and I won't have Feedly Pro anymore! What happened to the developer of gReader? He's not gonna support the people who bought the gReader Pro app?

**Comment by bmp412** [comment]
To add on to taschmidt's suggestion: on a computer export your OPML backup, create a Feedly account, import the OPML, and login to gReader Pro with the new Feedly creds.

Also, I've flagged the app for review on the Play store.

**Comment by holla2040** [comment]
adding feedly login workaround got me back in.

**Comment by gyoung345** [comment]
Linking the accounts worked for me too! Thanks!

**Comment by avinash** [comment]
Linking the original Google account with a newly created Feedly account works great.

**Comment by gromlix** [comment]
@avinash: You missed the point: Linking a feedly account to a google account for authentication works like a charme. Using this combination with gReader app is broken.

**Comment by avinash** [comment]
I'm confused. I can now login using my newly created Feedly credentials and I see all my feeds. It seems to me that everything is working fine.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
