### ISSUE TITLE
Articles not caching, Android 8.0

### ISSUE THREAD

**Issue by FoxBJK** [noinnion/greader#289]
I realize that it's currently in alpha, but I figured it's best to report this now so you've got plenty of time to fix it before release. In the Andoird O developer preview, I noticed that caching articles no longer works. It _appears_ to function on the same schedule, but from what I can see, the cache is not actually being used and no articles are saved to device.

Nexus 5X
Android: 8.0.0 (build OPP3.170518.006)

I'll re-test as future builds are pushed to see if this changes

**Comment by tigerandyx9** [comment]
Similar problem. Am reinstalling and meanwhile using alternative app
