### ISSUE TITLE
Every fiftieth article displayed blank.

### ISSUE THREAD

**Issue by colmbuckley** [noinnion/greader#29]
When reading many articles in article view, every fiftieth article (ie: when the article count is updated) is displayed blank. Going to the previous or next article and back fixes it.

**Comment by alephnull** [comment]
I see this too. Except it is not just every fiftieth.

**Comment by colmbuckley** [comment]
Yes; I see it with other articles too from time to time, but it's *always* the fiftieth ones.

**Comment by noinnion** [comment]
Could you try the beta?
http://noinnion.com/greader/updates

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by noinnion** [comment]
Closed for now, if it still happens in latest version 5.1.2, please reopen it again. Thanks
