### ISSUE TITLE
Authentication on Feedly with Google is dead

### ISSUE THREAD

**Issue by somepad** [noinnion/greader#292]
Google changed its requrements for OAuth, and gReader is no more available to authenticate.
Pks fix

**Comment by davidgraeff** [comment]
I can confirm this

**Comment by anttitelio** [comment]
Please note that this is a duplicate issue. First issue of the same topic was opened already a month ago.

**Comment by bderiso** [comment]
Duplicate of issue #278

Please comment there for increased visibility (although it seems like this project is abandoned anyway).

There is a workaround in the comments of that issue as well.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
