### ISSUE TITLE
Voice reader only plays summary

### ISSUE THREAD

**Issue by kranix0** [noinnion/greader#297]
I've got voice reading set to full content, but it is only reading out the summary.

gReader 4.3.1_pro
Android 7.0
Samsung Galaxy S6 (SM-G9208)

**Comment by lordyama** [comment]
I can make it read the whole article if I chose Save Page from the menu.

**Comment by Futureknows** [comment]
Exact same on all devices with pro version. Have to export to pocket to voice read entire article.
