### ISSUE TITLE
HTML Parsing Failure

### ISSUE THREAD

**Issue by aarongustafson** [noinnion/greader#298]
Every time I load an article from brucelawson.co.uk, all gReader shows me is the instructions above the comment form. I checked with Bruce and we're confident it's not on his end. Here's an example: http://www.brucelawson.co.uk/2017/reading-list-172/

Here's the result in gReader:

![screenshot_20170715-080241](https://user-images.githubusercontent.com/75736/28266383-8de325c6-6ac2-11e7-8e66-9b5aae66afcc.png)

**Comment by brucelawson** [comment]
That page mostly validates (https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.brucelawson.co.uk%2F2017%2Freading-list-172%2F) except for 2 errors in the WordPress-generated RSS feed links ("Error: Bad value feed:http://www.brucelawson.co.uk/feed/ for attribute href on element a: Expected a slash ("/")."). Could that be causing it?
