### ISSUE TITLE
Image captions not shown in offline article views

### ISSUE THREAD

**Issue by usmonster** [noinnion/greader#3]
Similar to a [previous regression](https://groups.google.com/d/topic/g_reader/u_AXFDWqxH4/discussion), I can't view image captions (title text) via the long press menu option. Nothing happens. Tried offline and online, simplified an full article views.

Using current beta version.

(Great app, though, by the way--thanks!)

**Comment by usmonster** [comment]
I recently noticed what I think is another manifestation of the issue (unless it's a new issue altogether): The title text is only displayed up until the first quotation mark (`&quot;`), or perhaps until the first HTML entity. Example can be seen looking at [today's xkcd](http://xkcd.com/1485/) in your feed.

**Comment by noinnion** [comment]
Closed for now, if it still happens in latest version 5.1.2, please reopen it again. Thanks
