### ISSUE TITLE
Volume down has same effect as back button

### ISSUE THREAD

**Issue by Lenoxus** [noinnion/greader#30]
An odd one: If I'm looking at a feed item and hit the volume down button, it takes me back tothe list of items for that subscription, and hitting it again takes me to the list if subscriptions. Volume up raises the volume as usual.

I'm using a Nexus 5 running Android 5.1, not rooted.

**Comment by Lenoxus** [comment]
Wait, this seems to be deliberate behavior. Well it caught me off guard, what can I say.

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by noinnion** [comment]
Closed for now, if it still happens in latest version 5.1.2, please reopen it again. Thanks
