### ISSUE TITLE
Can't log in via Google

### ISSUE THREAD

**Issue by nikolayg** [noinnion/greader#301]
On Android, I can no longer login to Feedly (which uses Google auth). It gives an error about being unable to login from embedded client.

**Comment by bderiso** [comment]
+1

**Comment by bderiso** [comment]
Duplicates of this issue: https://github.com/noinnion/greader/issues/278

Please comment there for increased visibility (although it seems like this project is abandoned anyway).

**Comment by debango** [comment]
This is a big Problem.  Not able to login with Google in Pro version too. Doesn't make sense. Please fix.

**Comment by martinsalaj** [comment]
I saw this problem mentioned on forum already month ago.  Switched to new phone. Can't use anymore.  I have to use temporarily other reader. Please fix this.

**Comment by mx4k** [comment]
Same issue here.

**Comment by pedrom34** [comment]
Had the same issue.
I agree this should be fixed, but here's a workaround:
Create a feedly account login in feedly preferences, and log with it in gReader.

![feedly preferences screenshot](https://i.imgur.com/3dk7Wjn.png)
