### ISSUE TITLE
Weird YouTube bug

### ISSUE THREAD

**Issue by heroldc** [noinnion/greader#302]
If an article contains a YouTube video and I tap it, it pops up. Since I only tap it by accident (because of what happens next), I close it. Then it immediately pops up again. This will continue until I close the article altogether.

**Comment by fatuuse** [comment]
For me to. For like 3 times. Then it stops open it self up.

**Comment by lcasale** [comment]
This issue is very annoying. It also happens when you're scrolling and your initial touch point to begin the scroll is on the YouTube video.

**Comment by InitSIX6** [comment]
Having the same issue on multiple devices. Very annoying that an accidental touch causes the video to play 3 times.

**Comment by yosnoor** [comment]
I'm having this issue, too. I'm sure there will be others. Anyway, this, for me, is the only thing that detracts from an otherwise excellent app. If you fix this bug, I'll give you five stars as I already have pro.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
