### ISSUE TITLE
Can't log in with goole

### ISSUE THREAD

**Issue by mdvl** [noinnion/greader#307]
Error 403. Disallowed user agent

**Comment by mvolz** [comment]
I am experiencing the same issue. I get a 403 user agent disallowed error.

**Comment by mvolz** [comment]
Dupe of issue #278

**Comment by svysik** [comment]
Same issue when trying to sign into Feedly with Google account on the pro version and free version

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
