### ISSUE TITLE
Article list keeps randomly resizing

### ISSUE THREAD

**Issue by tlinsley** [noinnion/greader#308]
As I drag my finger up the screen, to scroll through the article list, the items in the article list randomly resize themselves. At first I thought it was just images loading slowly, but it does it to items even after the image loaded. I checked all my settings and found no obvious offenders.

Is anyone else having this issue? Is it a bug, or a settings issue?

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
