### ISSUE TITLE
Article Holding Link

### ISSUE THREAD

**Issue by monpac** [noinnion/greader#31]
Holding on a link and opening in the browser then prevents from doing the same action with another link on the same (cached) article unless I go back to the listview and load up the article again.

**Comment by abuladeen** [comment]
Similar problem here. Using a link or selecting some text first time after loading an article works fine, but next attempt fails: links act like static text. Have to continually reload the article to get these functions (links, selections) to work again, one at a time.

**Comment by seocamo** [comment]
Samme here, this really bug me, this mean I cant use the app .. Because all my news Got multiple links

**Comment by monpac** [comment]
I think it has been corrected right? That's what it seems from the last update.

**Comment by seocamo** [comment]
i just test this and yes it do work now
