### ISSUE TITLE
Unable to login to Feedly with Google

### ISSUE THREAD

**Issue by robmtx** [noinnion/greader#313]
I just had to install the app on a new phone, and I'm trying to connect my Feedly account.
1. **Open** gReader
2. Click on **Feedly Cloud** as my service
3. Click on **Login** when the Feedly Cloud prompt pops up
4. Click on **Continue with Google** when prompted to Sign In
5. Receive 403. That's an error from Google "Error: disallowed_useragent"
6. Tried the same steps on another phone and got same error.

The full error page is below.

I tested my Feedly login by installing their app and authenticating and it works fine.

Can you please investigate and let me know if this is a bug or something I'm doing wrong?
Thank you,
Rob

![screenshot_20170912-195602](https://user-images.githubusercontent.com/31931850/30388672-5be004ba-987e-11e7-9af8-2edef234a1f7.png)

**Comment by Crilor** [comment]
Same problem with Pro version.
Please help me!

**Comment by dimitrimitrix** [comment]
Same issue

**Comment by sunredsky** [comment]
Same problem.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
