### ISSUE TITLE
Feedly Cloud Google login fail with Pro version

### ISSUE THREAD

**Issue by Crilor** [noinnion/greader#314]
When I try to login in with Google on feedly Cloud I receive an error!
Please help me!

**Comment by wyun96711256** [comment]
I also encountered the same problem

**Comment by elcapitan777** [comment]
I've encountered the same problem - can't login to Feedly using Google account.

**Comment by dimitrimitrix** [comment]
Same issue

**Comment by plettix** [comment]
Same here. Please fix it!
