### ISSUE TITLE
google and feedly login 

### ISSUE THREAD

**Issue by my1sec** [noinnion/greader#317]
I can't able to login. please update.

**Comment by wickets** [comment]
Same

**Comment by wickets** [comment]
403. That’s an error.

Error: disallowed_useragent

This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browsers are permitted to make authorization requests to Google. We offer several libraries and samples for native apps to perform authorization requests in the browser.

Learn more

Request Details
That’s all we know.

**Comment by serjo77** [comment]
Same

**Comment by dimitrimitrix** [comment]
Same issue

**Comment by wickets** [comment]
I downgraded to Android 7 and even that doesn't work....please update ASAP....thanks

**Comment by charlesroper** [comment]
Same here.

**Comment by bikerp** [comment]
Same here. Please fix it as soon as possible. I had to reinstall my phone and I can use the app any more. Thanks

**Comment by andrazkopac** [comment]
Is it possible that a bug preventing people to log in remains open for almost a month? Please fix this already. Or provide an alternative way to log in.
403. That’s an error.
Error: disallowed_useragent

**Comment by dimitrimitrix** [comment]
On the feedly website you can add a feedly login option, then get back to
greader and use login via feedly.

**Comment by wickets** [comment]
> On the feedly website you can add a feedly login option, then get back to
> greader and use login via feedl

Very nice workaround...thanks.  Theres also palabre which is a decent reader.

**Comment by andrazkopac** [comment]
Thank you, this worked for me.

**Comment by takacsot** [comment]
Thank you. Workaround is working to me too.

**Comment by csilker** [comment]
Same issue and error as reported by wicket above. Yes, there seems to be a workaround, but please fix the issue...

**Comment by UltraSalem** [comment]
Installed a new ROM and now also hitting this issue when setting my phone back up.

**Comment by PACMAN49** [comment]
Same issue. Please fix it

**Comment by Rambalac** [comment]
Funny that I posted about this security bug in greater several years ago, when Google reader got closed, and it was just ignored.

**Comment by epkugelmass** [comment]
Same issue
