### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by dimitrimitrix** [noinnion/greader#319]
Hi, since a couple of days I have scrolling issues in the reading view, when I swipe down fast-ish the reading view goes down and "bounces" back up. No problem in article list view. Ive got a galaxy s7 with android 7. Let me know if you need more details.

**Comment by Taochok** [comment]
Here the same. If it's a fast scroll, like you want to get to the end of the reading, it goes up... It's so annoying I skip the news... It started since last update i think

**Comment by nemesisonline** [comment]
This happens to me too, since a few days ago. Makes greader really hard to use. Galaxy S7, Android 7.

**Comment by dimitrimitrix** [comment]
Update to say its also an issue on my galaxy tab s

**Comment by Taochok** [comment]
Yes, my Galaxy Tab Pro too.... Are these guys recoding the swipe gesture?. This could be the reason their scroll never went smooth...

**Comment by fabgo** [comment]
I also have the same issue, on my Galaxy S2. Makes the app unusable really.

**Comment by Taochok** [comment]
I'm so annoyed I'm starting to look for a replace... I just hate how it does exactly the opposite I'm asking when I swipe...

**Comment by dimitrimitrix** [comment]
I've switched to feedly...

**Comment by 23rdf** [comment]
Same here on LG G4 (H815). App is barely usable at the moment as reading an article is almost impossible. Please fix it soon and let me know if you need any details or logs.

**Comment by dwincort** [comment]
I'm experiencing the same problem on a Moto X Pure running Android 6.

**Comment by ilektron** [comment]
Same on Pixel XL. Different feeds seem to behave normally while a number bounce backaking it impossible to scroll

**Comment by privateuly** [comment]
Same here. On Samsung Galaxy A5.  Worked well until recently.

**Comment by albertotb** [comment]
Same here on a Motorola G4

**Comment by pebbe** [comment]
Same problem on Samsung Galaxy S5 Neo

**Comment by Taochok** [comment]
I wish i could uninstall the update... I've paid the pro version.

On my Galaxy tab pro doesn't happens... This might be a hint for the developer... If they get this info....

**Comment by privatesam** [comment]
Same problem Nexus 6P Oreo 8.1 - had it on Oreo 8.0 and last version of Nougat.

**Comment by DiegoMarchetto** [comment]
Same problem on Moto X Force running Android 7.0

**Comment by robspahr** [comment]
Is this issue being addressed? I have this problem on my Galaxy tab 10.1 2014 edition, LG G4, and LG V20.

**Comment by DenizSa** [comment]
I had the same issue with the S8. Turning on hardware acceleration in "look and feel" seems to fix it.

**Comment by Taochok** [comment]
Deniza, i love you! It really fixes it!!!!!

**Comment by pulsar14** [comment]
Huawei M3
If the device goes in standby (lock screen) the Article page freeze.
It's necessary to back to the Articles feed and open the Article again.

**Comment by noinnion** [comment]
Duplicate #378 
https://github.com/noinnion/greader/tree/master/apk/beta
