### ISSUE TITLE
1st alinea missing 

### ISSUE THREAD

**Issue by berkens** [noinnion/greader#32]
When viewing an article in Feed mode, the first alinea is missing. 
In Web view I can see the alinea.

**Comment by noinnion** [comment]
What is alinea?

**Comment by berkens** [comment]
I'm sorry (Dutch word).

I meant the first "paragraph" is not shown.

Greetings, Ben
Op 15 jul. 2015 07:35 schreef "noinnion" <notifications@github.com>:

> What is alinea?

**Comment by noinnion** [comment]
could you tell me the feed url? and a screenshot?

**Comment by berkens** [comment]
I tried several options / settings in greater, now only the 1st paragraph
is shown.

Looking in gReader where the feeds are listed. It is website www.fd.nl and
www.luchtvaartnieuws.nl.

Here some screenshot.

Greetings Ben
Op 18 jul. 2015 13:57 schreef "noinnion" <notifications@github.com>:

> could you tell me the feed url? and a screenshot?
>

**Comment by noinnion** [comment]
Closed for now, if it still happens in latest version 5.1.2, please reopen it again. Thanks
