### ISSUE TITLE
gReader cannot manage 10ths of streams?

### ISSUE THREAD

**Issue by liar666** [noinnion/greader#322]
i'm using greader to read a few 10ths of RSS text streams, in offline mode. I.e. I connect on wifi@home , force refresh of streams, disconnect then leave home and read articles in subway, then come back home and loop this process.

very quickly (even if i remove the app, reinstall it and import my opml again), most of the streams are not updated anymore, even if new articles are published for sure.
removing cache (through the app option or the os) also does not solve the problem.
only work around is to unsubscribe the stream (loosing all starred articles) then subscribing again. a few times later the problem occurs again...
this is a very painful situation...

An example of opml file that makes gReader go lazy is available here:
https://mega.nz/#!4ENnlISa!LwtD4Nh0cRmoKyKEnVbu4oOECwxNfo_1tpetItuseBc

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
