### ISSUE TITLE
Strage problem with phpBB3

### ISSUE THREAD

**Issue by stoertie** [noinnion/greader#326]
Hi from Germany,

I have a phpBB3 board (vers. 3.2.1) that includes an extension named "Smartfeed". Smartfeed creates an customised ATOM, RSS 2.0 or RSS 1.0 link to use it as a feed. 
When I paste this link into gReader it works perfect, all posts I want to have are shown. Also the non-public posts are shown. 
But then nothing more happend. When tip to refresh gReader refreshes, but it doesn't show any new post anymore. Is that normal? ;)

Here is a sample RSS 2.0 link, I created for you for testing:
http://forum.z1-nordlichter.de/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Do you have any idea to solve this problem?

Best rergards
Michael

**Comment by stoertie** [comment]
OK, it seemed, that there is no support by the App-Programmer anymore!

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
