### ISSUE TITLE
Google login is not work now.

### ISSUE THREAD

**Issue by tak9-n** [noinnion/greader#328]
When I login with my google account, the app shows an error page. It says I can't  login with the embeded browser and can use google's library.

**Comment by thinsoldier** [comment]
I'm having the same problem.

Chose Feedly Cloud.

Pressed login.

Chose "Continue with Google"

Got "Google - 403. That's an error. Error: disallowed_useragent"

**Comment by thinsoldier** [comment]
Found a solution.

On your laptop/desktop log in to Feedly.com via your google account.

Click you avatar image in the top right. A menu will open.

Click profile.

A panel will open allowing you to edit your first and last name. Close that panel.

You will now see a page titled "Manage Account". It will also say "Logged in as you@your.com using Google". On this page there are several boxes. One of the boxes says "Logins". Click that box.

Click the "Add Login" button.

Click "Add a Feedly Login"

Enter your e-mail address and create a password.

Now go to gReader on your mobile device and use the e-mail address and password you just created.

**Comment by tak9-n** [comment]
It works. Thank you.
But it's not a good solution. I hope the developer use a google's library to resolve the problem.

**Comment by plettix** [comment]
Please fix the login problem. Google says there are some libs for that issue...

**Comment by Smile4ever** [comment]
https://radekzahradnik.cz/blog/2018/10/alternative-for-greader-pro-feedly-greader-pro/

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
