### ISSUE TITLE
Authentication Google credentials error

### ISSUE THREAD

**Issue by pintasart** [noinnion/greader#329]
O can't connect with Google credentials. I have this error:

403. That’s an error.

Error: disallowed_useragent

This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browsers are permitted to make authorization requests to Google. We offer several libraries and samples for native apps to perform authorization requests in the browser.

Android 6.0.1,. Bq Aquaris M5

**Comment by koshspam** [comment]
I am also getting this error.

**Comment by dekuhn** [comment]
Same issue with web view login restriction. Please fix or can't use the product.

**Comment by slolife** [comment]
Same here. Bought the pro version but I cannot login to get my feeds

**Comment by newfolder666** [comment]
+1. Seems that the issue us related to Google authentication policy change. Google doesn't allow non-browser useragents to login.

Please check if it's possible to change useragent to pretend this is a normal browser

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
