### ISSUE TITLE
Keep Unread articles still marked as read on Feedly

### ISSUE THREAD

**Issue by evansd** [noinnion/greader#33]
I use gReader with Feedly. My usual workflow is to scan through my feeds on gReader and mark interesting articles as Keep Unread, then mark everything as read once I reach the bottom, leaving just the interesting articles. However this marks all articles as read on Feedly, even the once which I've selected to Keep Unread.

I've also noticed that sometimes, after I've read one of these articles on my phone and marked it as read, it reappears as unread on Feedly. I can't reliably reproduce this unfortunately, but it does point to something being slightly buggy in the feedly sync.

Still one of my most useful apps though, so thanks!

**Comment by noinnion** [comment]
Keep Unread only works locally.
