### ISSUE TITLE
greader does not update

### ISSUE THREAD

**Issue by LarryLuciano** [noinnion/greader#330]
Hello,

Greader does not update, since I purchased it in November I am requesting a refund.

**Comment by LarryLuciano** [comment]
Hello,

Greader does not update, since I purchased it in November I am requesting a refund.

**Comment by MrMoxy** [comment]
Log out. Then at log in on the initial screen BEFORE selecting a source click on the bread crumbs (top left) and uncheck the optimize sync box. It is broken and stops loading.  That fixed it  for me!

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
