### ISSUE TITLE
Opens a youtube link unexpected

### ISSUE THREAD

**Issue by AKSSINC** [noinnion/greader#332]
Opens a youtube link in external browser when i scroll content down. Should not open any links external, not autoplay any video. Annoying.

**Comment by mahesham22** [comment]
Yes, and it opens 3 times.

**Comment by williamjamir** [comment]
This issue is really annoying for me, when a feed has some video embedded on it I cannot read the entire news without close the youtube 3 times.

**Comment by yugabe** [comment]
Yes, the app opens inline YouTube videos either with the awful inapp player (no full screen support) or out of the app. 3 times for each video embedded in the article... Please give an option to disable autoplaying videos.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
