### ISSUE TITLE
Feedly login via Google no longer works

### ISSUE THREAD

**Issue by DavidLGCrawford** [noinnion/greader#338]
Google has changed their Oauth login and now it is impossible to login to a feedly account in the gReader app.

**Comment by pruthisith** [comment]
Yeah I also have the same issue. I hope the developer can fix this.

**Comment by Schlueter00** [comment]
Same issue here

**Comment by newfolder666** [comment]
+1. Seems that the issue us related to Google authentication policy change. Google doesn't allow non-browser useragents to login.

Please check if it's possible to change useragent to pretend this is a normal browser

**Comment by JulesBrookfield** [comment]
Same problem...  So frustrating.  I use to use this everyday!

**Comment by jasonimani** [comment]
I had the same problem. What I did to resolve this is to export my rss feeds (opml) from Feedly and create an account on Feedly without Google. Import opml files, and then login from Greader with your new account.

Alternatively, in your account settings in Feedly, you can link accounts and create a login. I noticed this feature after I had already done the above. If someone could try it and let us know.

**Comment by klausw** [comment]
FYI, I created a new Feedly account, signed out, signed back in using Google auth, then linked the Feedly account. This fixed the "disallowed user agent" error, but I'm now stuck at the ":status header not present" network error from issue #344.

**Comment by jasonimani** [comment]
@klausw Have you tried signing back in without using Google auth? Login using your Feedly creds.

**Comment by klausw** [comment]
Yes, I tried logging in with the feedly creds, that didn't work and got me
a "expected :status header not present" error after entering my
credentials. See #344.

**Comment by jasonimani** [comment]
@klausw Bummer...sorry it's not working. What if you create a new account and import your opml feed? Sorry just grasping for ideas to help.

**Comment by pspierce** [comment]
I still have issues with oAuth and google.  I don't get an error, just the "you've been authenticated and will redirect" screen, but nada.  Refreshing the original page doesn't work either.

**Comment by Smile4ever** [comment]
https://radekzahradnik.cz/blog/2018/10/alternative-for-greader-pro-feedly-greader-pro/
