### ISSUE TITLE
Cache view CSS is not loaded any more, since Android System Webview updated

### ISSUE THREAD

**Issue by jimbobmcgee** [noinnion/greader#339]
Android System Webview updated today on my device, and now Cache View does not seem to load CSS.  

Uninstalling updates to Android System Webview makes cached content appear correct again, but this is not desirable -- Android is going to keep trying to update this system component and the only option I have is to uninstall all updates, not the most-recent one.

I'm running gReader v4.3.1_pro, and the full content format is set to 'Normal page'.  The working version of Android System Webview that 'Uninstall updates' gets me back to is v45.0.2454.95.  The version that my device is trying to force me to update to is v64.0.3282.137.

Appreciate that this may not be a gReader-specific issue, but is it possible that the Webview component has changed the way the base URL of links/resources is applied, and gReader needs to compensate?

With ASWV v64.0.3282.137
![screenshot_2018-02-02-23-32-11](https://user-images.githubusercontent.com/12205864/35759601-85495a0e-0872-11e8-82ae-e07b469600ed.png)

With ASWV v45.0.2454.95:
![screenshot_2018-02-02-23-34-42](https://user-images.githubusercontent.com/12205864/35759602-85a2d89a-0872-11e8-8616-6e1eea7a9933.png)

**Comment by philippebriard** [comment]
I have exactly the same problem and that's very frustrating. I thank anybody that can solve this problem.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
