### ISSUE TITLE
Cache auto cleanup not cleaning up

### ISSUE THREAD

**Issue by stangrinberg** [noinnion/greader#34]
It seems the cache auto cleanup is not actually cleaning up read items after 1 day, per set settings. Eventually, after 1-2 weeks of usage it takes up all the remaining storage space on the device and requires "Clear Cache". Once the clear cache is done manually, free storage is reclaimed. Device is Nexus 5.

Before clear cache, available: 3.87GB
After clear cache, available: 6.02GB

**Comment by noinnion** [comment]
what service do you use?

**Comment by stangrinberg** [comment]
Are you referring to "Services" within greader? If yes, then commenting on articles and translate.

**Comment by rnc** [comment]
I see this as well (although my cache is on the SD card)

**Comment by noinnion** [comment]
Please try latest version, otherwise reopen the issue
