### ISSUE TITLE
Hacker news feed broken

### ISSUE THREAD

**Issue by adam515** [noinnion/greader#340]
It works the first time I add it but the next day it doesn't show any new content even after manual refresh

**Comment by Locash** [comment]
You need to clear the apps data in app settings. Then re setup Greader, when selecting the local rss method you need to Un✓ optimized sync.
![quickmemo _2018-05-31-12-28-36](https://user-images.githubusercontent.com/30946440/40820498-7e51eb74-6526-11e8-90e1-d9357ee8a74a.png)

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
