### ISSUE TITLE
Can't login using Google account

### ISSUE THREAD

**Issue by Schlueter00** [noinnion/greader#343]
When selecting Feedly Cloud to sign in and then clicking to sign in by Google I get the error below. Any thoughts?

403. That’s an error.

Error: disallowed_useragent

This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browsers are permitted to make authorization requests to Google. We offer several libraries and samples for native apps to perform authorization requests in the browser.

Learn more

Request Details
That’s all we know.

**Comment by newfolder666** [comment]
+1. Seems that the issue us related to Google authentication policy change. Google doesn't allow non-browser useragents to login.

Please check if it's possible to change useragent to pretend this is a normal browser

**Comment by jasonimani** [comment]
I had the same problem. What I did to resolve this is to export my rss feeds (opml) from Feedly and create an account on Feedly without Google. Import opml files, and then login from Greader with your new account.

Alternatively, in your account settings in Feedly, you can link accounts and create a login. I noticed this feature after I had already done the above. If someone could try it and let us know.

**Comment by klausw** [comment]
FYI, I created a new Feedly account, signed out, signed back in using Google auth, then linked the Feedly account. This fixed the "disallowed user agent" error, but I'm now stuck at the ":status header not present" network error from issue #344.

**Comment by lisiyu** [comment]
I have the same issue

**Comment by rgreid** [comment]
You can add a Feedly login and password to your existing account [here: https://feedly.com/i/account/logins](https://feedly.com/i/account/logins). 

Confirming what @jasonimani suggested: this will let you log in without Google oauth.

**Comment by newfolder666** [comment]
Suggestion from **rgreid** helped me.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
