### ISSUE TITLE
Expected status header not present

### ISSUE THREAD

**Issue by hughpratt** [noinnion/greader#347]
While using Greader, out of nowhere, 
I got this network error: "expected status header not present". Now,  I'm getting no feeds in Greader.

**Comment by newfolder666** [comment]
Having the same issue

**Comment by c8c8** [comment]
You can bypass this by logging out and then logging back into Feedly again but this time click the 3 dots in the upper right corner and uncheck the "https" sign-in option.  The good news is that everything will work again.  The bad news is that your login is no longer secure.  Sadly, it looks like the beginning of the end for this once great but now dead for years project.  Time to start looking for something comparable.  There sure aren't a lot of quality choices.

**Comment by newfolder666** [comment]
I've tried it. Unfortunately it doesn't work for me because now I cannot login to Feedly source using my google account :smiley:

**Comment by hughpratt** [comment]
c8c8, that worked!  Thank you!
