### ISSUE TITLE
Add option to move the circular Check button (mark as read button) to the left (or hide it all together)

### ISSUE THREAD

**Issue by unformatt** [noinnion/greader#35]
I accidentally press this button all the time while scrolling. I even select Mark All As Read (double check) by accident sometimes which is frustrating as there is no undo.

**Comment by noinnion** [comment]
have you tried to move it to other locations?
Menu->Reading Preferences->Mark all as read?

**Comment by unformatt** [comment]
Not sure how I missed this. You rule!
