### ISSUE TITLE
Starred items never clear

### ISSUE THREAD

**Issue by sneakerboots** [noinnion/greader#351]
I have starred items in my list from way back in 2012 because I can't get them to clear. I remove the star and the article goes away temporary but always comes back. It is not starred on the Feedly feed which I sync to, as far as I can tell. 
![screenshot_20180225-101049](https://user-images.githubusercontent.com/36822513/36644879-4ea3991a-1a15-11e8-8625-b68adbe8588b.png)
This is across multiple tablets, so it isn't a cache issue. I've also unchecked the option to cache starred items. Each time the articles come back.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
