### ISSUE TITLE
Mistake

### ISSUE THREAD

**Issue by IGHG** [noinnion/greader#352]
Hi.
Some days I have mistake in gReader 
When I refresh data from mobile inet - all good
But from any Wi-Fi connection I have error - Expected ':status' header not present

**Comment by Locash** [comment]
If using Feedly or old reader you need to clear the apps data and set up again. When entering your account info you need to Uncheck the https option. ( Most likely)
If using the local rss option  Uncheck the "Optimized sync" option. This causes a ALOT off issues for people  when using the local rss option.
![quickmemo _2018-05-31-12-28-36](https://user-images.githubusercontent.com/30946440/40797623-76de182a-64ce-11e8-84b5-407662ff88d8.png)

![quickmemo _2018-05-31-12-26-46](https://user-images.githubusercontent.com/30946440/40797524-0fc11d4a-64ce-11e8-824d-4e8a90dd7bf5.png)

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
