### ISSUE TITLE
Cannot add a xml podcast url to gReader

### ISSUE THREAD

**Issue by zavjah** [noinnion/greader#355]
Hi,

at the site https://www.treffpunkt-leben.org/cms/predigten there is a rss link at the bottom, which I cannot add to gReader.

This is what I've tried without success
a) click on the rss link opens it in the browser
b) copy the link and go to add resources in gReader and paste ii in the podcast section
c) paste the page url in podcast section and hot search

How cannot I add this podcast to my reader?

Thanks,
Zavjah

**Comment by Locash** [comment]
You need to click the plus+ put the address in the search section were it says"Keywords or Url" 
NOT In the podcast search section or where it says "Topic"
I could only listen to it if I downloaded it. Streaming did not work. I think that is a device issue on my end.

![quickmemo _2018-05-31-12-04-34](https://user-images.githubusercontent.com/30946440/40796506-e7b9a2b6-64ca-11e8-997c-f37b96b11d11.png)
