### ISSUE TITLE
list layout padding

### ISSUE THREAD

**Issue by bladelores123** [noinnion/greader#358]
the list layout could look so much better if you made it "breathe" a little. there is no padding around the text and this makes it look so cluttered. (dunno if it matters but this is on a galaxy 7 with android 7)

**Comment by bladelores123** [comment]
example:

![unnamed](https://user-images.githubusercontent.com/38396545/38778674-8e749944-40bd-11e8-9290-c14a81fb40f3.png)

![unnamed2](https://user-images.githubusercontent.com/38396545/38778675-90ec7cdc-40bd-11e8-8241-1ac8cbb72cb4.png)

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
