### ISSUE TITLE
Only upper half of the article shown

### ISSUE THREAD

**Issue by OLLI-S** [noinnion/greader#36]
Hello,

sometimes gReader Pro (also the current version) shows only the upper half of the article.
When I switch to an other article, the page is displayed correctly.
See attached example.

Greetings

OLLI
![screenshot_2015-07-21-11-31-51](https://cloud.githubusercontent.com/assets/8037790/8811355/d558f4c6-2ff5-11e5-8d39-0aeb7b22d47b.png)
![screenshot_2015-07-21-11-31-59](https://cloud.githubusercontent.com/assets/8037790/8811359/d80c8746-2ff5-11e5-9d50-b6fdc08ec7f9.png)

**Comment by noinnion** [comment]
do you have Android Webview app installed on your device? could you try to
disable it

**Comment by OLLI-S** [comment]
I have it installed and disabled it.
The problem occurred only very seldom (2 times per month), so it is hard to re-test...

**Comment by noinnion** [comment]
seems to be a problem with Android System Webview
