### ISSUE TITLE
GReader pro does not update feeds

### ISSUE THREAD

**Issue by guidonzolo** [noinnion/greader#364]
I've purchased gReader pro. I have installed it on Huawei P20pro with Android 8.1. The first time that it loads feeds all it's ok but if i mark all articles of a feed as read then that feed Will never be updated. That is the feeds are updated only one time.

**Comment by guidonzolo** [comment]
Thanks you.
Not it works fine.
Guido

Il 31 maggio 2018 18:26:16 CEST, Locash <notifications@github.com> ha scritto:
>Best way to fix this issue is to use Feedly as a result cloud. The
>updates just fine on Oreo. Just use a email address to sign up for
>Feedly and NOT Google login.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/noinnion/greader/issues/364#issuecomment-393590942

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
