### ISSUE TITLE
Error 403 on login with google

### ISSUE THREAD

**Issue by efraimmachado** [noinnion/greader#371]
It is not possible to login with Google

**Comment by obygyv** [comment]
403. That’s an error.

Error: disallowed_useragent

This user-agent is not permitted to make an OAuth authorization request to Google as it is classified as an embedded user-agent (also known as a web-view). Per our policy, only browsers are permitted to make authorization requests to Google. We offer several libraries and samples for native apps to perform authorization requests in the browser.

**Comment by makpufterpup** [comment]
I have the same issue with Google login. I can't use the app.

**Comment by obygyv** [comment]
I had a backup of this app with the personal data (and saved account). I could restore it and I still can use it, but for those who haven't this chance, it's bad.

**Comment by KUTlime** [comment]
Solution: https://github.com/noinnion/greader/issues/373#issuecomment-427557271

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
