### ISSUE TITLE
Store configuration / parameter to Google server / service 

### ISSUE THREAD

**Issue by sangorys** [noinnion/greader#372]
When installing a new phone or a new ROM, gReader is automatically installed but the configuration / parameters are lost.

We need to parameter again the application. 

Google offers a service to store the parameters / configuration / data in Google Play. Can you please use this feature? 

Thank you in advance for your help 😊

**Comment by Mahaldo** [comment]
I think it's a good idea. Whenever I change phones I have to configure many parameters that I have been optimizing for years.

**Comment by noinnion** [comment]
Do you habe a link for me?

In gReader you can backup your settings in Settings -> Backup/Restore

**Comment by Mahaldo** [comment]
I tried again a few minutes ago to be able to confirm you.
in Settings -> Backup / Restore.
I made a backup of my configuration, cleaned all the data in the app and tried to restore again and it does not work.
it keeps the theme settings and various other parameters that I modify.

Now to reconfigure XD

**Comment by noinnion** [comment]
Sorry about that, will look into it.

**Comment by meseer** [comment]
If my read of the original request is correct, then I'd say this is a missing feature, not a bug. It can be implement with [Auto Backup](https://developer.android.com/guide/topics/data/autobackup) and would be of amazing value. I've changed many phones and it has always been a struggle to restore my app and per-feed configuration that is hand optimized for best readability.

One thing to keep in mind is that configuration will need to be versioned and the new versions of the app will need to be able to handle old versions of the configuration.

**Comment by Mahaldo** [comment]
Hi meseer, The error is in the function that already exists a long time in the application.
And what you say about automatic copy every time it is modified would be good too. I usually make a copy every time I am satisfied with my customization.
Although I think it would be better to use google services to save said copy.
