### ISSUE TITLE
Greader Pro has been removed from playstore

### ISSUE THREAD

**Issue by imqqmi** [noinnion/greader#373]
Greader Pro can't be found in the playstore anymore and when running the ad version and going to menu and upgrade to Pro it lands on a page not found. And you can't login with your Google account in reedy anymore.

All this leads me to believe something fishy is going on. Either the device has abandoned it or sold it to an advertising company and may be similar to the stylish plug in on Firefox, which ended up blocked from the plug in page. Very sad.

Please prove me wrong and fix the issues!

**Comment by otrapersona** [comment]
Logged out and using a VPN I couldn't find the Pro version on the store ( https://play.google.com/store/apps/details?id=com.noinnion.android.greader.readerpro ) on many countries. I think it has been completely removed and not just for a certain device/country.

**Comment by otrapersona** [comment]
greader also disappeared https://play.google.com/store/apps/developer?id=noinnion

**Comment by JuuEi2018** [comment]
Any information what has happened? Luckily gReader Pro seems to working ok? But it call home or why it is removed? Any information is appreciated.

On http://noinnion.com/ gReader still are on top of list.

**Comment by maver1ck** [comment]
I think it's time to move to official feedly app.

Bug with logging to feedly via google is open for one year.

It's the only app I need to restore from backup. 
It's time to say goodbye.

**Comment by munichhilton** [comment]
I want my money back!

**Comment by JuuEi2018** [comment]
I wonder what has happened, any information about that?

I do not want money back, software has work very well years and **gReader still work very well**.  But if it do something illegal or something like that, i do not know. :-(

**Comment by maver1ck** [comment]
For me gReader is not working because I can't login to feedly using google account.

I send refund request to google... I'm curious what would happen.

**Comment by imqqmi** [comment]
Feedly does work, just not using a google account. Register a new feedly account with its own user/password and use the direct account in greader. Search this github for a more clear instruction. I've used an app that can transfer the greader pro apk to the sd card sonI can use it on my new tablet. I don't need the playstore to install the app. I've paid for it so I don't feel bad about it.

The free version stillm runs ads so someone is receiving money for it I guess.

**Comment by rico-chet** [comment]
I purchased gReader Pro a few years ago and have been using it since and despite a few inconveniences, it worked good for me and I'd hate to see it go.

So like @imqqmi did, I extracted the APK from my mobile (7662784 bytes) and installed it on my new 10" tablet and it works fine so far (with Feedly login instead of Google, of course).

**Comment by virtualdj** [comment]
I think this is the best RSS reader out of there and still I cannot understand why the developer abandoned this great piece of software. I also tried to email him but unfortunately he never replied.

Sad, sad news.

**Comment by aistvan** [comment]
Anyone can send me the "Pro" APK?
I bought it, I have rights to use it.

**Comment by LinuxfarmerHH** [comment]
Have used it for many years in pro version, nice especially that you can use it without google and feedly.
But now in times of announced narratives from government and so called quality media, the censorship of greader was expected. With RSS you can book every news from every news agency on whole planet, or did someone believe censorship stops with A.J.?

**Comment by Hevgen** [comment]
Link to gReader 4.2 Pro apk is at Codes: https://github.com/noinnion/greader/blob/master/apk/gReader_420_pro.apk

**Comment by aistvan** [comment]
Thanks for the link, but I have 4.3.1_pro installed, so I looking for that version if it possible.

**Comment by Hevgen** [comment]
4.3.1 pro is beta only: https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.1_pro-beta.apk

**Comment by KUTlime** [comment]
[This solves the gReader problem with the Feedly authorization by Google account.](https://radekzahradnik.cz/blog/2018/10/alternative-for-greader-pro-feedly-greader-pro/)
gReader can be happily used again.

**Comment by rjpaulsen** [comment]
I believe it has been replaced with News+ by the same developer. Different icon and requires a plugin for Feedly, but it's the app we know and love.

**Comment by JuuEi2018** [comment]
> I believe it has been replaced with News+ by the same developer. Different icon and requires a plugin for Feedly, but it's the app we know and love.

Really? News+ is last updated January 20 2015 (and Feedly extension for News+ May 29, 2014).

**Comment by rjpaulsen** [comment]
> Really? News+ is last updated January 20 2015 (and Feedly extension for News+ May 29, 2014).

I tried several other options and they kind of all suck. News+ hasn't been updated, but it's clearly the same, it works, and doesn't require any side loading. Sure doesn't sound good though :(

**Comment by drorata** [comment]
Indeed News+ feels very much the same like gReader. The problem is that I had gReader Pro and now, with News+ I get ads again 👎

**Comment by Smile4ever** [comment]
I use Feed Me now. https://play.google.com/store/apps/details?id=com.seazon.feedme

**Comment by capitaladot** [comment]
Have pro version installed through sideload, but the damn widget is locked.

**Comment by LinuxfarmerHH** [comment]
The 4.3.1_pro APK works well on LineageOS and Droid on Time here. Can be installed after install from untrusted sources is allowed in the settings. Works inclusive it's widget, but remind to not activate 'optimized transfer' at first start, this seems to be messed up.

**Comment by udegbunamchuks** [comment]
Oh wow. No wonder I haven't gotten an update notification in months. I always reinstall apps via apk backups when I switch phones thus I didn't notice this.

I'm so not liking the alternative of switching to feedly

**Comment by gcadoret** [comment]
Yes its sad. I moved to inoreader.

**Comment by JuuEi2018** [comment]
> Yes its sad. I moved to inoreader.
Quite expensive, what I read from comment at Google Play. No way. And luckily I still have my gReader Pro (backup too). It simply the best. I wonder why anyone do something similar simplicity layout for news listing? I do not want thumbnails, only text in news listing.

**Comment by gcadoret** [comment]
its free on android device and for web version, ads can be hide with adblock. 
for you question, perhaps because inoreader exists and is the best. yes its not totaly free ( but as i said , its totaly usable in free version) but everything cannot be free and hard work must be rewarded

**Comment by virtualdj** [comment]
IMHO nothing beats gReader Pro, even years after its retirement. I don't like Inoreader because it's pretty magazine-styled while gReader is/was list-styled. And the checkboxes on the right to quickly mark as read/unread is unbeatable.

**Comment by sandimschuh** [comment]
Hi @noinnion, it would be great to bring gReader back to life. So can you please upload the source code so we can create a fork and revive this great reader? Thanks a lot.

**Comment by Matth7878** [comment]
+1 @sandimschuh
Imho you should create an issue (if not already existing? I haven't search) to make greader code available to the community.
Right now there is no app as good. 😞

**Comment by gcadoret** [comment]
> +1 @sandimschuh
> Imho you should create an issue (if not already existing? I haven't search) to make greader code available to the community.
> Right now there is no app as good.

yeah it already exists  : https://github.com/noinnion/greader/issues/377

**Comment by TGeRi** [comment]
The developers account is back on Gplay! I started noticing that I get ads. But no updates, no nothing. What do you think?

**Comment by virtualdj** [comment]
> I started noticing that I get ads. But no updates, no nothing.

Did you mean on the non-pro version? Because I don't see any ads on the Pro (which I still have on the smartphone as it is working still well).

I dream an updated version with the Google login fixed (even though you can circumvent it with Feedly) and Disqus working. But gReader Pro is still the best!

**Comment by TGeRi** [comment]
Once I did buy the pro but when I changed my phone I could only find the non-pro apk, so now I'm using 4.3.3 non-pro. I would be very happy to user the newest pro. Do you think it is possible to get it.

**Comment by virtualdj** [comment]
> Do you think it is possible to get it.

As long as you have the old phone available, there are plenty of apps you can use to backup the original APK on your old phone and move it to the new one.

**Comment by TGeRi** [comment]
Sadly, I didn't think of that then. I don't have that phone anymore. :(

**Comment by gcadoret** [comment]
now i use inoreader free version, its very good

**Comment by KUTlime** [comment]
> 
> 
> Sadly, I didn't think of that then. I don't have that phone anymore. :(

How about use [Google](https://www.google.com/search?q=gReader+pro+v4.3.1+Pro+apk+download), hmm?

**Comment by JuuEi2018** [comment]
> But gReader Pro is still the best!
It's amazing that there is no better feed reader than gReader, it is still best. All new readers seem to waste screen space. I like simple listings of titles (no images, no overview in a listing). This allows you to see a large number of titles at a glance. New readers fill the screen with a few titles, for example with "nice" square with title, image and overview etc.

**Comment by Matth7878** [comment]
I migrated to feedme long ago and I think it's the best alternative. It's the most similar to what was GReader.

I didn't search but I also believe there was a link in an issue for GReader pro apk so user could install it without having to rely on play store.

**Comment by TGeRi** [comment]
I will give feedme a try! Thx!

**Comment by TGeRi** [comment]
(Can feedme sync with Feedly?)

**Comment by Matth7878** [comment]
> (Can feedme sync with Feedly?)

Yes it is. Actually I am not sure you can use it without having a Feedly account.

**Comment by virtualdj** [comment]
Too much space wasted in Feedme, IMHO. I like the compactness of the articles list in gReader Pro and I cannot live without the checkboxes to skim down quickly the ones I don't wish to read.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue

**Comment by timea-techgirl** [comment]
> Thanks for using Pro version. Unfortunately we need to make some decision related to PRO version. You can read it here https://www.androidpolice.com/2021/02/15/we-spoke-to-the-developer-behind-greader-and-heres-whats-happening/ .
> 
> For Legacy Pro users you still can find the latest Pro version in Github. You can also get a Promo Code for 1 year free Premium as a reparation. Please write to [noinnion@gmail.com](mailto:noinnion@gmail.com)

I'm fine with the older pro version but the widget doesn't work, can you upload the fixed legacy pro version instead?
