### ISSUE TITLE
Interested in selling the rights to gReader? 

### ISSUE THREAD

**Issue by kanetik** [noinnion/greader#374]
I'd be interested in talking over development of gReader, if you are done with it. Let me know if you want to talk price.

**Comment by cll00** [comment]
agree

i think greader app is the best

**Comment by virtualdj** [comment]
I really hope noinnion (the developer) will sooner or later read those discussions or its emails from GitHub and think about it.
If all those people here are praying for having a working version (and no one asks for UI changes, just be able to use it as they used in the past!) of the BEST RSS reader in the Android world... well, there has to be a reason and I would be extremely happy to be its developer!

**Comment by noinnion** [comment]
Development will be continued
