### ISSUE TITLE
gReader source?

### ISSUE THREAD

**Issue by tesa237** [noinnion/greader#377]
Hi there!

Perhaps this has been asked before... But it would be awesome if we could get our hands on the source code of gReader and make it an open source project. 

Feel free to get in touch with me directly if someone has details or questions. 

Yes, I am a software engineer with quite a bit of experience.

**Comment by dpshelio** [comment]
Cann't the `apk` files can be extracted? Nevertheless, I don't know about open sourcing something which it doesn't contains a license. Even when it's openly available on the web still the copyright is owned by the author.

**Comment by tedsamuelsson** [comment]
They probably can. But I want to get the source from the original developer.  What I want is to continue this project in an official capacity, not as an underground thing, for me this would be an official thing or nothing at all. And yes, I am willing to hold the reins on this project and steer it to something useful.

**Comment by tedsamuelsson** [comment]
It seems that the original developer isn't responding, for what ever reason, at all anymore.

I'll see what can be done.

**Comment by virtualdj** [comment]
Having this app open sourced would be a dream, at least for me.
But dreams rarely come true!

**Comment by cll00** [comment]
i agree with the option to obtain the source code from the apk... sadly the author of greader has disapear and the only way of improve greader is share the source code

**Comment by outlogic** [comment]
gReader is the best RSS app I have ever tried. No other app is even close to it. Since it has disappeared from Google Play I really hope the developer releases the source code.
