### ISSUE TITLE
Scrolling issue

### ISSUE THREAD

**Issue by CoderLaure** [noinnion/greader#378]
When reading an article, I can slowly scroll down but if I try to "quickly scroll down" to go lower in the article (or to the bottom), it scrolls back up !! 

It makes reading cumbersome, especially since the behavior is normal when viewing a list of articles. 

It looks like the two ways of scrolling (the Apple vs the old way are mixed).

**Comment by noinnion** [comment]
Please update to the latest Android System WebView.

**Comment by noinnion** [comment]
please try latest beta https://github.com/noinnion/greader/tree/master/apk/beta

**Comment by noinnion** [comment]
fixed in v5.1.4
