### ISSUE TITLE
Feedly login with Google doesn't work

### ISSUE THREAD

**Issue by maliparsa** [noinnion/greader#379]
Google throws error 403 when trying to login with Google on feedly in the app.

**Comment by Tichij** [comment]
There are workaround for it:
https://github.com/noinnion/greader/issues/338
https://github.com/noinnion/greader/issues/328

**Comment by Smile4ever** [comment]
https://radekzahradnik.cz/blog/2018/10/alternative-for-greader-pro-feedly-greader-pro/

**Comment by noinnion** [comment]
Please try latest version 5.x.x
