### ISSUE TITLE
Codificação do texto 

### ISSUE THREAD

**Issue by wenesga** [noinnion/greader#38]
Olá boa tarde! 

 por que os caracteres fica desconfigurado nas notícias do olhar Digita?? 

É alguma configuração do app ou é do site olhar Digital? 

Exemplo de palavras descodificada: 

usuÃ¡rios  
verificaÃ§Ã£o 
seguranÃ§a
novidade Ão
opÃ§Ãµes 
utilizÃ¡-las

Tem como você me ajudar a resolver isso? Muito obrigado. 

Att. WENES.

**Comment by noinnion** [comment]
could you send me the feed url?

2015-07-30 18:54 GMT+02:00 Wenes Gomes Aquino <notifications@github.com>:

**Comment by wenesga** [comment]
são em todas noticias do OLHAR DIGITAL

Em 2 de agosto de 2015 02:34, noinnion <notifications@github.com> escreveu:

> could you send me the feed url?
>
> 2015-07-30 18:54 GMT+02:00 Wenes Gomes Aquino <notifications@github.com>:
>
> > Olá boa tarde!
> >
> > por que os caracteres fica desconfigurado nas notícias do olhar Digita??
> >
> > É alguma configuração do app ou é do site olhar Digital?
> >
> > Exemplo de palavras descodificada:
> >
> > usuÃ¡rios
> >
> > verificaÃ§Ã£o
> > seguranÃ§a
> > novidade Ão
> > opÃ§Ãµes
> > utilizÃ¡-las
> >
> > Tem como você me ajudar a resolver isso? Muito obrigado.
> >
> > Att. WENES.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/noinnion/greader/issues/38>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/noinnion/greader/issues/38#issuecomment-126990583>.
>



-- 
Wenes

**Comment by noinnion** [comment]
could you send me a screenshot?

2015-08-03 3:22 GMT+02:00 Wenes Gomes Aquino <notifications@github.com>:

**Comment by wenesga** [comment]
continua com mesmo problema
![screenshot_2015 08 07 11 26 24](https://cloud.githubusercontent.com/assets/13321239/9241925/6efb3e52-4150-11e5-9727-3ddfbe8a90fe.png)

**Comment by wenesga** [comment]
Bible- Life.Church

On more than 250 million devices around the world, people are reading,  
listening to, watching, and sharing the Bible using the #1 rated Bible  
App—completely free. 1,400+ Bible versions, 1,000+ languages. Listen to  
audio Bibles. Thousands of Reading Plans &amp; Devotionals, in 40+  
languages...

Install application via  
https://j794q.app.goo.gl/i/201895780642-801d9a1b-7217-44ad-ad78-e774979479e0

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
