### ISSUE TITLE
GReader dropping last Character on Feed Links

### ISSUE THREAD

**Issue by jwbradley** [noinnion/greader#380]
There are many time when I experience an issue with a link on a feed where the very last letter of the URL isn't there when I share the link to buffer. I have tried to report this before and the developer said they couldn't reproduce. The following feed gives me this issue almost every single time I try to share the links:

https://www.google.com/alerts/feeds/04852459464937538736/1277946705449884927

**Comment by Locash** [comment]
@jwbradley This might help not sure though.
You can change what data is copyied  when clicking copy in "share" (link- summary- title or any variation of the three) It might help if less "info" is copied and pasted.

*in-app settings-->Services--> customize share content 
----------------------------------------------------------------
This might help also in chaging if you use app or the systems share feature.
(It gives me more options to what apps I share to, if I use the devices system share feature Instead. When it is ☑)

*in-app settings-->Services-->internal share dialog
  


![quickmemo _2019-02-05-13-10-41](https://user-images.githubusercontent.com/30946440/52298439-9246ac00-2948-11e9-9a70-1ebb8f2f203b.png)
