### ISSUE TITLE
Why can't I read Tim Bray's 'ongoing' blog?

### ISSUE THREAD

**Issue by abcoates** [noinnion/greader#381]
Every time I try to add Tim Bray's 'ongoing' blog, it doesn't get added. I can't understand why. He has an Atom feed, not RSS, but in particular Tim was the creator of the Atom spec, so if you can't read his Atom feed, then your Atom feed handling might be borked.

Thanks, Cheers, Tony.

**Comment by tedsamuelsson** [comment]
FYI: Author hasn't responded to many issues in a long time. Commit history says no commits in over 2 years.
