### ISSUE TITLE
Articles not loading on Android 10

### ISSUE THREAD

**Issue by guyvzero** [noinnion/greader#382]
Well, this might finally be it...been working great for years without any dev updates, but now after going to Android 10 articles fail to load after you scroll through 5-10 of them.

You can force close the app and they will load again, but obviously that's not much of a solution. Uninstalling and reinstalling the 4.3.1 beta doesn't fix it either. 

Really sad, because somehow this is STILL the only great reader out there. Just tried all the competitors again (inoreader, feedlot, feed me, palabre, etc) and all of them really don't stack up to this. Oh well, probably going to have to go with one of those anyway....

**Comment by whimboo** [comment]
Note that this also happens on older versions of Android. As such I assume a recent change in WebView might have caused this problem. @guyvzero would you mind updating the title of the issue if you have the permissions?

**Comment by whimboo** [comment]
Note that there was another bugfix release of WebView yesterday. And I actually haven't seen this problem again since the update. So maybe this got fixed already.

**Comment by outlogic** [comment]
Same problem on Android 4.2.2

**Comment by noinnion** [comment]
please try latest gReader v5.1.2

**Comment by guyvzero** [comment]
Yup, it was something with Android web services, that updated after a couple months and then it was good to go.

Glad to see you're back to updating, hope for a reinstatement of the Pro version! Would gladly pay for it again on a non-subscription model!

**Comment by noinnion** [comment]
So your problem has been solved?

**Comment by guyvzero** [comment]
Yup, closed. Thank you!
