### ISSUE TITLE
MLB feed newly broken

### ISSUE THREAD

**Issue by xidbhonaker** [noinnion/greader#385]
Hi Noin,

I keep trying to add a feed to URL , https://www.mlb.com/rangers/feeds/news/rss.xml.  It adds, and downloads articles. But subsequent resfresh attempts always fail with this error:
![Screenshot_20200709-174300_gReader](https://user-images.githubusercontent.com/22203855/87098279-8b425e00-c20c-11ea-8e81-138a56e9c206.jpg) 

Can you provide me any clues?

**Comment by noinnion** [comment]
what feed service do you use?

**Comment by xidbhonaker** [comment]
For this feed, I am using links provided from this ‘mlb.com’ site:

 

https://www.mlb.com/rangers/feeds/news/rss.xml

 

They have rearranged the feeds many times since I posted the question.  It continued to fail, so I stopped using it.


When you released the (very nice!) updates lately to gReader, I added the ‘Rangers News’ feed to your app, and so far it’s behaving itself.

 

So either they fixed something or your latest release did.  Maybe something in their XML generator or your XML class library.  I’ll keep monitoring it, but for now you can consider this as ‘fixed’.

 

Again, thanks for all you do, the enhancements are pretty good!  (The only thing I’ve noticed is that new posts on the feeds don’t update the widget, and the app doesn’t update the notifications area, until I click on the widget to open the app.  Then, it vibrates to notify me it’s doing something (whether or not it finds anything) That’s a minor thing but thought I’d share so you’re aware.


Bill
