### ISSUE TITLE
Broken Synchronization 

### ISSUE THREAD

**Issue by fazlimnor** [noinnion/greader#386]
The synchronization seems broken since i updated to latest version. I tried every sync interval and yet it does not work. I am not getting any new items and have to synch manually.

Version used 5.0.1

**Comment by BMWBig6** [comment]
Where do we get Version 5.0.1?  I thought the latest version was 4.3.1.

**Comment by fazlimnor** [comment]
Noinnion just released new version on Google Play store. You might want to check it.

New version comes with subscription based premium

**Comment by BMWBig6** [comment]
Thanks.  I wonder if previous "Pro" users are grandfathered in to Premium.

**Comment by dstutzman1** [comment]
> Thanks. I wonder if previous "Pro" users are grandfathered in to Premium.

Nope.

**Comment by noinnion** [comment]
Unfortunately we the Pro version was pulled off Play Store by Google because it needed some updates. Therefore we have decided to support only 1 app. With the income of the Premium version we want to finance the development of the app. For users who bought the Pro version could write us an Email with they could get the annual subscription with 1 YEAR FREE TRIAL.

**Comment by willwhitworth** [comment]
This was fixed in gReader-5.1.1-321-release.apk, but broke again in Version 5.1.2-325.

**Comment by noinnion** [comment]
@willwhitworth could you please describe what is not working now? Thanks

**Comment by undertow25** [comment]
@noinnion background sync is not working, app syncs only when it's opened. Background data is enabled for it in Android settings. Pixel 3a on Android 11.

**Comment by fazlimnor** [comment]
From my observation, if gReader is included in background data control access or it is being monitored under background process, the sync will not work.

If gReader is excluded from the  Background data restriction then the synch process works.

My phone is OnePlus 5T and I have excluded gReader from "Battery Optimization" (similar to background data control access) and the synchronization is now working

**Comment by d4niel-P** [comment]
Can confirm on Samsung S10+ and S21+. Battery "optimization" is very aggressive on Samsung's phones with Android 11 and One UI 3.x and it looks that gReader background update priority is too low for it.

**Comment by noinnion** [comment]
please try latest beta https://github.com/noinnion/greader/tree/master/apk/beta

**Comment by d4niel-P** [comment]
On S10+ sytem battery optimization still kills background updates.

**Comment by undertow25** [comment]
Version 5.1.3-356 / Android 11 / Pixel 3a; battery optimisation disabled,
background data enabled and unrestricted data usage enabled; it looks like
sync is working, but the notification icon disappears right away when sync
is complete - so basically I don't see that there are new items until I
open the app.

**Comment by noinnion** [comment]
Here is a new try 
could you please gReader-5.1.3-360-release.apk

**Comment by d4niel-P** [comment]
On S10+ synchronization works in latest beta with battery optimization. Thanks.
