### ISSUE TITLE
[feature request] Additional swipe actions and action for opening in browser

### ISSUE THREAD

**Issue by sir-harlekin** [noinnion/greader#388]
Hi there,

great to see you back!

I hope these two suggetions are possible:

1. If one has more feed-groups can you add right/left swipe to select the next/previous group (under look and feel -> quick actions -> swipe actions (beta)? This makes navigating much more fluid (no opening the hamburger menu every time). Maybe this would also or better fit unter Look and feel -> Quick actions (for article list)
Can we also get the option to skip the group menu when "going back", exiting the app straight away. Or just show the menu, if the user is at the most left? at the moment when i am scrolling through my groups and just want to exit the app, menu always shows up when hitting back button.

2. can you make it possible (in addition to look and feel -> quick actions ->left and right action -> open in browser) to open the article "in browser" by just tapping everywhere from the artice list (-> skip internal view). for UI/UX experience its a bit fiddly to click the quick action buttons.

If you have any questions if I was not clear enough, just shoot.

Thanks.

**Comment by noinnion** [comment]
1. quick action -> swipe actions is used with article items, how do we jump to the next group with it? Could you also describe the "going back" request. Right now, if you mark all as read in a group, in automatically jump to the next tag/group/feed
2. there is Option in left/right action with Open in Browser

**Comment by sir-harlekin** [comment]
First off all, please excuse if i mixed up some describtions, i am new to greader. 
I will try to explain with pictures.

1.

Lets say i have groups like this:

![groups](https://user-images.githubusercontent.com/20474014/107870896-018ef900-6e9d-11eb-9163-9b242b31cb80.jpeg)

What i misunderstood, that at the moment swipe actions are for article view only.

Can it be possible to swipe left group in group view to get to the next/prev group without using the side menu to select a different group (its swipe "back" to trigger the menu, then selecting a different group atm).

![swipe](https://user-images.githubusercontent.com/20474014/107870921-3e5af000-6e9d-11eb-811b-de2c2b4f5436.jpeg)

It would feel a lot more natural with today default swipe navigations.

2.

I know the left/right action with Open in Browser. Can it be made optional, to whole article space to directly react with open in browser when tapped. I one does not want to use the internal viewer at all, it kind of frustrating to aim for the small left/right action buttons.

![browser](https://user-images.githubusercontent.com/20474014/107870978-e53f8c00-6e9d-11eb-9af4-98190ed64059.jpeg)


If you have any further questions, i will try my best to explain further.

**Comment by noinnion** [comment]
Unfortunately is not easy to implement about swiping through different groups.  I don't think we could do it.
About open in browser for swiping we could discuss in another issue? Would you be kind to create a new issue? Thanks
