### ISSUE TITLE
Long posts are incorrectly show 

### ISSUE THREAD

**Issue by MarMarAba** [noinnion/greader#39]
For example this post:
http://feeds.weblogssl.com/~r/elblogsalmon2/~3/-gPknM3oh9U/el-acuerdo-de-grecia-con-sus-acreedores-europeos

At the end of the post a white layer covers the last part of the article

**Comment by noinnion** [comment]
could you please send me a screenshot?

**Comment by MarMarAba** [comment]
I didn't investigated about the problem when I posted the problem into
github.

It was hard to reproduce the issue but I have now a more clear idea about
it.

I have installed gReader 4.1.2. The post with which I can reproduce the
problem is located in the following RSS feed
http://www.elblogsalmon.com/atom.xml
. The post is the one with date July 14 and titled "El acuerdo de Grecia
con sus acreedores europeos".

The steps to reproduce the problem:

1. Open gReader
2. Open the Elblogsalmon RSS list
3. Open the said post
4. Change application and open gReader again / Press home button and open
gReader again / Force onPause() - onResume()
5. Scroll to the last part of the post, it should be covered by a white
opaque layer

* In other situations (I don't know exactly when but should be a related
issue) the white layer is in the top part of the post.

I attach a pair of screenshots. One is with the layer in the top part, the
other one is at the end of the post where you can see the scrollbar
position in the right  part of the screen.

Best regards

--

Mario Martínez Abad
Ingeniero Informático
Tel: 668.876.054

**Comment by MarMarAba** [comment]
It can also be related with the following problem:

1. With device in portrait mode with auto rotation enabled, open any post
and wait to be completely loaded (web or channel view)
2. Force onPause() - onResume()
3. Tilt your device to switch to landscape mode

[1st. Issue: the post view does not switch automatically go landscape mode
until you scroll up or down the post]

4. So... scroll the post to force switching view
5. Tilt your device again for switch to portrait

[2nd. Issue: at this point the post viewing mode is not reloaded to show
correctly in portrait mode even if you scroll the screen.]

Best regards

* If you need beta testers I would help you.

--

Mario Martínez Abad
Ingeniero Informático
Tel: 668.876.054

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by MarMarAba** [comment]
It looks fine in the first tests. The global impression for the new version is good.
Thanks!
Closing...
