### ISSUE TITLE
Can't change widget colours at Premium versión !!

### ISSUE THREAD

**Issue by luisvalino** [noinnion/greader#392]
![Screenshot_20210210_210301_com noinnion android greader reader](https://user-images.githubusercontent.com/8470180/107565468-0e34f800-6be4-11eb-8b6a-694f228381ae.jpg)

**Comment by luisvalino** [comment]
Are you going yo fix this issue, please ???

**Comment by noinnion** [comment]
Please try the beta https://github.com/noinnion/greader/tree/master/apk/beta

**Comment by luisvalino** [comment]
Hi, can't install it. Show me a message -> "Reading package apk error".

**Comment by noinnion** [comment]
Could you try to uninstall the current version?  
or try this https://medium.com/@GuruTechnolabs/how-to-fix-problem-parsing-the-package-error-in-android-c2fca91673cb

**Comment by luisvalino** [comment]
I can't do it ... seems you apk file is not compatible or is corrupted. Could you upload a stable version to the Play Store to download it ??

**Comment by noinnion** [comment]
There is a beta channel, you could join it.

**Comment by luisvalino** [comment]
How can I join it? And how can I download apk files? On the other hand ... I uploaded a new bug thread -> 'Greader enables me an alarm icon on my phone' ... please, read it.

**Comment by noinnion** [comment]
Go to play store and search for gReader, click on it and scroll down to 

![image](https://user-images.githubusercontent.com/4679216/107861210-a0d3d200-6e44-11eb-89b6-42a4ab1c2408.png)

end click on Join
