### ISSUE TITLE
Automatic sync not working

### ISSUE THREAD

**Issue by darrenthedad** [noinnion/greader#393]
Premium version. Custom automatic sync set to 15 minutes but it's not working.

**Comment by noinnion** [comment]
Have you tried the latest version 5.1.0 or the beta https://github.com/noinnion/greader/tree/master/apk/beta

**Comment by darrenthedad** [comment]
Beta fixed it. Best news reader ever period. Thank you!


-Darren

Darren Fisher
414.234.0555
darrenthedad@gmail.com
