### ISSUE TITLE
Greader enables me an alarm icon on my phone.

### ISSUE THREAD

**Issue by luisvalino** [noinnion/greader#394]
Greader enables me an alarm on my phone. 
Every time I access the app, the alarm icon on my phone enables me, I have it on the desktop clock widget, and the upper right corner: I surround it with a red circle. 
Why? 
How is it disabled?

![Screenshot_20210213_210910](https://user-images.githubusercontent.com/8470180/107860675-df678d80-6e40-11eb-876d-191fcbb6b267.jpg)

**Comment by noinnion** [comment]
The new android api has some restrictions for alarms. We will look into it.

**Comment by noinnion** [comment]
Please try latest beta https://github.com/noinnion/greader/tree/master/apk/beta

**Comment by noinnion** [comment]
please try latest version 5.1.3
