### ISSUE TITLE
Inoreader should support innoreader.com base url

### ISSUE THREAD

**Issue by noinnion** [noinnion/greader#396]
For users in china, Inoreader does not work with the official base url https://inoreader.com
It should also support https://innoreader.com

**Comment by noinnion** [comment]
please try https://github.com/noinnion/greader/tree/master/apk/beta

![image](https://user-images.githubusercontent.com/4679216/107886584-f40b5a80-6f00-11eb-97c7-d25526d94a86.png)

**Comment by GGboomers** [comment]
> please try https://github.com/noinnion/greader/tree/master/apk/beta
> 
> ![image](https://user-images.githubusercontent.com/4679216/107886584-f40b5a80-6f00-11eb-97c7-d25526d94a86.png)

This version completely solves all the problems before this. I can use it normally, refreshing quickly.👍🏼
Thank you very much! You are my savior
