### ISSUE TITLE
Descodificado

### ISSUE THREAD

**Issue by wenesga** [noinnion/greader#40]
http://olhardigital.uol.com.br/checar.php?materia=/noticia/nova-geracao-do-google-glass-ja-esta-sendo-testada/50174

**Comment by noinnion** [comment]
could you send me a screenshot?

On Mon, Aug 3, 2015 at 3:24 AM, Wenes Gomes Aquino <notifications@github.com

**Comment by wenesga** [comment]
![screenshot_2015 08 07 11 26 24](https://cloud.githubusercontent.com/assets/13321239/9138414/0a4072f2-3cfa-11e5-8370-941b653cf853.png)
![screenshot_2015 08 07 11 26 40](https://cloud.githubusercontent.com/assets/13321239/9138415/0a4b97cc-3cfa-11e5-8f5c-7d661ad28781.png)
![screenshot_2015 08 07 11 26 51](https://cloud.githubusercontent.com/assets/13321239/9138416/0a504a4c-3cfa-11e5-98fe-06671f10cb84.png)

**Comment by wenesga** [comment]
Entendeu agora amigo?

**Comment by wenesga** [comment]
2015-08-07 10:35 GMT-03:00 noinnion <notifications@github.com>:

> could you send me a screenshot?
>
> On Mon, Aug 3, 2015 at 3:24 AM, Wenes Gomes Aquino <
> notifications@github.com
> > wrote:
>
> >
> >
> http://olhardigital.uol.com.br/checar.php?materia=/noticia/nova-geracao-do-google-glass-ja-esta-sendo-testada/50174
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/noinnion/greader/issues/40>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/noinnion/greader/issues/40#issuecomment-128700025>.
>



-- 
Wenes

**Comment by wenesga** [comment]
ENTEDEU AGORA AMIGO?

2015-08-07 12:00 GMT-03:00 # WeiDroid <wenesga@gmail.com>:

>
>
> 2015-08-07 10:35 GMT-03:00 noinnion <notifications@github.com>:
>
>> could you send me a screenshot?
>>
>> On Mon, Aug 3, 2015 at 3:24 AM, Wenes Gomes Aquino <
>> notifications@github.com
>> > wrote:
>>
>> >
>> >
>> http://olhardigital.uol.com.br/checar.php?materia=/noticia/nova-geracao-do-google-glass-ja-esta-sendo-testada/50174
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <https://github.com/noinnion/greader/issues/40>.
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/noinnion/greader/issues/40#issuecomment-128700025>.
>>
>
>
>
> --
> Wenes
>



-- 
Wenes

**Comment by wenesga** [comment]
Bible- Life.Church

On more than 250 million devices around the world, people are reading,  
listening to, watching, and sharing the Bible using the #1 rated Bible  
App—completely free. 1,400+ Bible versions, 1,000+ languages. Listen to  
audio Bibles. Thousands of Reading Plans &amp; Devotionals, in 40+  
languages...

Install application via  
https://j794q.app.goo.gl/i/201895780642-93e5ec69-f812-4090-a83d-6e912476c017

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
