### ISSUE TITLE
dark mode isnt working (snafu on my behalve)

### ISSUE THREAD

**Issue by Wandelstock** [noinnion/greader#400]
Android9 (ChromeOS kukui)

![Screenshot 2021-02-16 at 22.23.10.png](https://user-images.githubusercontent.com/58773587/108123201-c7447800-70a5-11eb-81d7-0f94d95796c1.png)

**Comment by Wandelstock** [comment]
looks like this device hasnt a darkmode, some apps do a timed dark mode. (in app setting for instance : dark mode from 18:00 till 06:00)

**Comment by noinnion** [comment]
Unfortunately it will only work if your your device have dark mode. It would be complex to also support this. Sorry I have to reject.
