### ISSUE TITLE
Sync dosn'r work (Inoreader)

### ISSUE THREAD

**Issue by IngoBN** [noinnion/greader#403]
Sync dosn'r work (Inoreader).
Take a look at the Screenshot 
Thanks!

![Screenshot_20210217-213746_gReader](https://user-images.githubusercontent.com/7857615/108286044-ac96ff80-7188-11eb-95d1-65711c3ec8a5.jpg)

**Comment by noinnion** [comment]
could you try latest beta https://github.com/noinnion/greader/tree/master/apk/beta

**Comment by fraight1** [comment]
Im facing this bug now (april 10th). Any solution?
*im using greader 5.2.1 from playstore
![Screenshot_20210410-035548_gReader](https://user-images.githubusercontent.com/48590651/114239750-ae26bc00-99b0-11eb-9b42-8ea97fcf3e4b.jpg)

**Comment by noinnion** [comment]
does it still happen?
