### ISSUE TITLE
Automatic sync doesnt work

### ISSUE THREAD

**Issue by Wandelstock** [noinnion/greader#404]
After i inserted the redeemcode the automatic sync stopped working.

On ChromeOS Kukui and ChromeOS Coral

**Comment by noinnion** [comment]
That's strange. will investigate it.

**Comment by noinnion** [comment]
Please try latest beta https://github.com/noinnion/greader/tree/master/apk/beta

**Comment by Wandelstock** [comment]
the link says: could not resolve file more than 10mb


is it in the play store? i have participated in the beta programm. On a chromebook is it hard to sideload

**Comment by noinnion** [comment]
please try latest version 5.1.3 in Play Store
