### ISSUE TITLE
Feedly Cloud Login not work

### ISSUE THREAD

**Issue by Yashimaru-snm** [noinnion/greader#405]
The login to Feedly Cloud does not work when opening the browser and logging in. The link "greader://feedly?code=XXXXX" requests the login again. 
![d0cb569f-4638-47e6-abf6-674de7a1528e](https://user-images.githubusercontent.com/63490946/108532939-2a592900-72b7-11eb-859a-8995bae2bd4d.jpg)

**Comment by noinnion** [comment]
could you please use Chrome for logging in?

**Comment by Yashimaru-snm** [comment]
For some reason it doesn't give me the option to do it with chrome only with firefox. Copying the link and opening it in chrome I was able to log in. Thanks
