### ISSUE TITLE
Access the app settings before making the first login.

### ISSUE THREAD

**Issue by Mahaldo** [noinnion/greader#409]
It would be nice if the configuration menu can be accessed before logging in.

I use many different settings than the one that comes by default.
When I log in to Feedly, it does not download all the news because it exceeds the default limit.
Then I have to configure the parameters, log out and log in again with the configuration.

**Comment by noinnion** [comment]
please try latest beta https://github.com/noinnion/greader/tree/master/apk/beta

**Comment by Mahaldo** [comment]
Excuse me, I speak Spanish and I'm using google translator
I liked that I can already configure the parameters before login. Also new splash window at startup.

The import is still not in progress. 
Video no public in youtube https://youtu.be/cYSkT8QO69A

00:00 Configuration my way.
03:20 Export.
03:44 import cannot find files.
04:34 Login feedly.
04:57 Import Finds files, but does not load configuration.
05:20 second attempt with the same result.
05:36 Restoration of the copy made with v 5.1.3-356-release.apk, Restores some parameters, but not all, Then I checked and it will not subtract some appearance settings .

**Comment by noinnion** [comment]
Added in v5.1.4

![image](https://user-images.githubusercontent.com/4679216/109410432-f8248700-799a-11eb-8a5b-eaf6b5b1c7d4.png)
