### ISSUE TITLE
Old items keep returning

### ISSUE THREAD

**Issue by cjrjscgallo** [noinnion/greader#41]
Every day old read items keep returning to my unread items list.

**Comment by noinnion** [comment]
have you tried the FAQ?

**Comment by cjrjscgallo** [comment]
Sorry... I had scanned the headings, but didn't see one that matched. After looking again I have read "Why do articles become unread again?" But, "Auto cleanup read items" was already set to 2 weeks.

**Comment by noinnion** [comment]
are you using Local service? could you set the date to 4 weeks?

**Comment by cjrjscgallo** [comment]
I have set the data to 4 weeks. I'm not sure what you mean by Local. I'm reading on my phone and I do not have 2-way sync enabled.

**Comment by noinnion** [comment]
what service do you use? Feedly? The Old Reader? Local?
could you turned on 2 way sync?

**Comment by cjrjscgallo** [comment]
Oh! I haven't thought about that since I installed gReader on my new phone. I am Local. I will turn on 2-way sync.

**Comment by noinnion** [comment]
are there any feeds that always turn to unread?

**Comment by cjrjscgallo** [comment]
All of them were. It would be a couple of articles, and a couple of feeds, at a time and several times a day. Since changing to 4 weeks and 2-way sync, it hasn't happened. But it hasn't been very long, yet.

**Comment by noinnion** [comment]
I just update the beta with the fix
could you pls try it http://noinnion.com/greader/updates

**Comment by cjrjscgallo** [comment]
I have installed it. It installed gReaderPro. I had been using gReader. Also, since making the changes to settings yesterday, I have not had any read items reappearing in gReader. Thanks for your help. Is there anything else I can do to help you test this?

**Comment by noinnion** [comment]
you can observe if the beta is running fine.
thanks for testing
