### ISSUE TITLE
Crash on A11

### ISSUE THREAD

**Issue by sick13** [noinnion/greader#413]
Constantly Crashes when entering settings on Android 11 (Samsung s10+ Oneui 3.0)
App Version any 5.x.x the 4.x.x version works ok

**Comment by d4niel-P** [comment]
I have the same phone, both official release and latest beta work without issue. Do you have settings backup? If so, try to clear application data and try to start it then.

**Comment by sick13** [comment]
i tried restoring the backup and without,also cleared data same story,just cant get whats going on will try the 5.1.3 see if that helps as it fixed some crashes maybe that's it

**Comment by noinnion** [comment]
what feed service do you use? have you tried v5.1.3?

**Comment by sick13** [comment]
Feedly,but also happened with local rss opml,but that was on 5.0.x

**Comment by sick13** [comment]
@noinnion 5.1.3 has fixed the issue for me,you can close this! :)
