### ISSUE TITLE
Login to feedly doesn't work with version 5.1.3

### ISSUE THREAD

**Issue by ajoe** [noinnion/greader#414]
Login dialog opens, but again and again and again. It doesn't store that.

**Comment by noinnion** [comment]
what brower do you use? please try with Chrome

**Comment by ajoe** [comment]
I use Firefox Beta as default Browser.
I know a workaround:
The dialogue is show in an embedded Browser window.
1. Click on the three point on the right above corner.
2. Select "Open with Firefox Beta"
3. The complete Firefox will be displayed. 
4. Login to freely. Now greader will use and store this Login.

**Comment by noinnion** [comment]
Thanks for the workaround. I didn't know this.
