### ISSUE TITLE
feedly sync

### ISSUE THREAD

**Issue by umbm** [noinnion/greader#417]
I can't sync with feedly anymore. 
Android app v 4.3.1_pro
![Screenshot_20210316-224854](https://user-images.githubusercontent.com/22610039/111384660-10d6b180-86aa-11eb-8cd1-34d3cd3e74da.jpg)

**Comment by nweightman** [comment]
Also having same issue, using 4.3.1_pro

**Comment by ruggio81** [comment]
Same problem. Version 5.1.4-382 premium.

**Comment by Pentaphon** [comment]
Looks like all Greader versions are affected. I'm guessing everybody is using a free Feedly account?

**Comment by TGeRi** [comment]
Same here. I'm also using Feedly account.

**Comment by johno4444** [comment]
I also have the same issue on the latest beta version

**Comment by Andy-ZA** [comment]
Same problem. Version 5.1.4-382 premium.

**Comment by d4niel-P** [comment]
Looks like feedly made some (unintentional?) changes to api.

**Comment by ndorigatti** [comment]
Have the same issue, but this should not be a big issue in code, the http response is 204, which means success but no response content. There should be a fix on check response as success if the code is in the class 2XX

**Comment by huLter** [comment]
Same issue.can sync again after log out and re-login.

**Comment by umbm** [comment]
Ok, works for me again after deleting all data of the app and reconfigure it.

**Comment by ndorigatti** [comment]
> Ok, works for me again after deleting all data of the app and reconfigure it.

Do we really need to reconfigure the whole app? I can't reconfigure from scratch, there are a lot of options... 🥴

**Comment by umbm** [comment]
Maybe you can get it run again after cleaning app-cache only. Give it a try.

**Comment by ndorigatti** [comment]
> Maybe you can get it run again after cleaning app-cache only. Give it a try.

Deleting app cache does not work. I managed to make some sync work after deleting cache INSIDE the app, but after 1 correct sync i got again the issue. Don't know if reconfiguring the app will solve forever.

**Comment by umbm** [comment]
Delete the cache inside android system I meant, not inside the reader only

**Comment by ndorigatti** [comment]
> Delete the cache inside android system I meant, not inside the reader only

Yeah, sorry my message was not clear:
- I deleted android app cache and it did not solve
- I deleted standard cache INSIDE the app, it did ONE sync and then showed the issue
- I deleted FULL cache INSIDE the app, it did all the sync tries up to now (10 times at least)

So, instead of reconfiguring the whole app, I would suggest to go inside the app, overflow menu, clear cache, FULL.

It worked for me this way. 👍

**Comment by Juraj-Masiar** [comment]
I think Feedly is working on it. Because I didn't do anything and now it works now again.
All I did was check if my Feedly account works from my desktop and I don't think that's related.
