### ISSUE TITLE
Inverse Page Broken WSJ

### ISSUE THREAD

**Issue by darrenthedad** [noinnion/greader#418]
Inverse page view broken on Wall Street Journal paste. See attachment. It starts out correct, but then changes. 
![Screenshot_20210317-072645](https://user-images.githubusercontent.com/78966205/111467264-3ab3c680-86f2-11eb-85af-41d5f97e9aa9.png)

![Screenshot_20210317-072345](https://user-images.githubusercontent.com/78966205/111467125-1657ea00-86f2-11eb-893a-58b9c7093f26.png)

**Comment by noinnion** [comment]
Unfortunately inverse page does not work properly for all pages.

**Comment by darrenthedad** [comment]
Cool. Thanks for the heads-up!


-Darren

Darren Fisher
414.234.0555
***@***.***
