### ISSUE TITLE
Stop working today on redmi note 8t.

### ISSUE THREAD

**Issue by MichaelGirch** [noinnion/greader#419]
Bug report:
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/willow_ru/willow:9/PKQ1.190616.001/V11.0.5.0.PCXRUXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 20570, tid: 20570, name: .greader.reader  >>> com.noinnion.android.greader.reader <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
Cause: null pointer dereference
    x0  0000000000000000  x1  000000704b1441ec  x2  7265646f63654400  x3  726f7463656c6553
    x4  0000000000000000  x5  0000000000000000  x6  716e7362646b6452  x7  7f7f7f7f7f7f7f7f
    x8  0101010101010101  x9  000000704aea1000  x10 0000006c00027458  x11 000000704b144488
    x12 00000000ffffffff  x13 0000000000000000  x14 4b3d092f234ec266  x15 cae6c696f68e9634
    x16 000000704f1ea0f0  x17 00000070e7fac810  x18 000000001311de48  x19 0000000000000003
    x20 0000000000000000  x21 0000006c0001ff40  x22 0000007fc66a3bc8  x23 0000006c00027458
    x24 0000006c00027468  x25 0000000000000000  x26 0000007fc66a3e60  x27 0000000000000000
    x28 0000006c000b8270  x29 0000007fc66a3b20
    sp  0000007fc66a3af0  lr  000000704e1759dc  pc  000000704e1759dc

backtrace:
    #00 pc 00000000034529dc  /data/app/com.android.chrome-pJliQn97GVOB5vdENSG0-w==/base.apk (offset 0xa0f000)

**Comment by noinnion** [comment]
There is a bug in Google System Webview app
https://www.theverge.com/2021/3/22/22345696/google-android-apps-crashing-fix-system-webview

**Comment by d4niel-P** [comment]
Webview 89.0.4389.105 fixes the issue. You can find it on APKMirror if there is no update in the store yet.
