### ISSUE TITLE
Tags and filters 

### ISSUE THREAD

**Issue by pchris7489** [noinnion/greader#424]
Hello,
When we want to follow one subject via multiple sources (typical for scientific research, there are multiple sources that can publish one important subject)

There is a need to have filters and tags. For exemples, a Regex filter or basic search filter that would search in all the feeds and output the source where it found the results

This should not be hard to implement, it is just a search to do while parsing the feeds? Anyways this will be very very handy for managing feeds,

**Comment by pchris7489** [comment]
Sorry, I didn't see this until last week because it is not very promoted in gReader (even on the premium landing page)

Because gReader already have a 'tag' feature, you must click on "search", type a search string then press on a button to add a new 'search tag'

So very very good and great. Nothing to say.

**Comment by noinnion** [comment]
You can also search with & (AND), | (OR) or ! (NOT)
