### ISSUE TITLE
gReader appears to be using http instead of https

### ISSUE THREAD

**Issue by nqhitchens** [noinnion/greader#433]
When I first add the feed view-source:https://feeds.arstechnica.com/arstechnica/index , gReader is able to load 20 articles without issue. Subsequent updates fail however, it's trying to load an http URL from Google which includes the http version of the Arstechnica URL as a parameter.

**Comment by noinnion** [comment]
Which feed service are you using?

**Comment by npdbharris** [comment]
I'm pretty sure I tried both

**Comment by noinnion** [comment]
Unfortunately we are using the URL that our search service provides for us and that is http.
