### ISSUE TITLE
Voice Reading with Bluetooth actions

### ISSUE THREAD

**Issue by noinnion** [noinnion/greader#51]
Support Voice Reading with 
- bluetooth actions like Play, Pause, Next, Previous.
- Pause on incomming call

**Comment by vincentj7** [comment]
I'd also like to see these features implemented.

**Comment by MrLizzam** [comment]
1. Can the app read the titles and we can use voice command to real the whole article or skip.

2. When there's other audio running in the background (e.g. music), the music volume lower and then the voice reading starts, like in most navigation system.

**Comment by MrLizzam** [comment]
Also, can the app create a playlist so that i can list down articles i want to listen when i'm driving. Right now i can only initiate a voice read article, and append the next article into the list.

**Comment by raaarTrex** [comment]
also would love to see this. huge fan of the app. thanks for all your hard work!
