### ISSUE TITLE
Back navigation support in Web view

### ISSUE THREAD

**Issue by lukashinsch** [noinnion/greader#54]
It would be very helpful to allow back navigation in article web view. I often find myself opening links in articles I'm reading and navigating back (both the left arrow on the top and android back)  gets me back to the article list instead of the article.

**Comment by bjoldenbork** [comment]
I cannot stress enough how enormously helpful that feature would be. It's the one function I'm really missing. I can't believe it's not implemented yet, seeing the large bundle of functions and options. Maybe it's a hidden feature that can be switched on somewhere? Either way, I would love to use a back button in web view. Thanks.

**Comment by wl2776** [comment]
You can return back to the article from web view using curved arrow button on the menu, appearing in lower right corner on tap. This menu also has button for switching on/off full screen.

Agree that using good old device' s "Back" button for the purpose of returning into article would be much more intuitive and convenient.

**Comment by bjoldenbork** [comment]
Nice. I must have disabled that menu some time ago and forgotten about it. Thanks.
