### ISSUE TITLE
Reading mode is always turned on by default

### ISSUE THREAD

**Issue by wl2776** [noinnion/greader#55]
Galaxy note 10.1 2014 edition, official firmware with root (Android 4.4.2)
When reading articles, loaded into cache for offline reading, the reading mode (letter R in rectangle) always turns on. The letter appears on white background, and the article's styles are not used for rendering.
I have to always turn off this mode either with double tap or with a tap on that letter R in article menu.

**Comment by wenesga** [comment]
continuar com mesmo problema

**Comment by wl2776** [comment]
Tried removing application cache and data and configuring everything again from scratch. The problem seems to have disappeared. Will look for this further.
The respective items in settings have appeared again.

**Comment by wl2776** [comment]
Everything works, like a charm. Closing.
