### ISSUE TITLE
Request: Privacy Tools

### ISSUE THREAD

**Issue by github-monkey** [noinnion/greader#57]
I'd like to see the inclusion of simple privacy options, to prevent (super) cookies being set in gReader's internal browser and clear the internal browser's cache, including (super) cookies.

**Comment by noinnion** [comment]
do you have any idea?

**Comment by github-monkey** [comment]
Not really. I do not know what browser you use. If it's open source there
may well be discussion on this topic to be found online. I haven't used
gReader in a long time. If you're looking for projects to pick up, recent
comments in the play store have some recurring themes.
