### ISSUE TITLE
Refresh data on application load

### ISSUE THREAD

**Issue by champs777** [noinnion/greader#60]
Android 5.1 cyanogen
Sprint
Galaxy s5

If I kill greader or hit back to exit the application, when I reopen the app, I get an auto refresh of my articles

If I leave the application, and reopen it, no refresh is forced. I have to manually refresh. 

Sync on startup is enabled. 

Shouldn't greader force a refresh every time I open it? 

Thanks for your assistance.

**Comment by medico89** [comment]
Yes os correct!

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
