### ISSUE TITLE
 [Bug report] Articles trimmed in reading mode by double tap

### ISSUE THREAD

**Issue by sunstream** [noinnion/greader#61]
![screenshot_2015-10-17-10-19-07](https://cloud.githubusercontent.com/assets/3416701/10557531/5d1c2510-74b9-11e5-8fe1-adf0d61262dd.png)
Precondition: subscribe to a feed which matches 2 conditions:
1. Pages loaded in feed view contain only article summary, not its full text.
2. Page layout in web version is not mobile-friendly (e.g. livejournal).
Steps to reproduce:
1. Open an article as described above. You will see the summary.
2. Double-tap on the article text to load reading mode.
3. Scroll down.

Expected result: the article is fully loaded.
Observed result: the end of article is absent, the page is just trimmed, and the rest of the article is replaces with blank grey area.

Note: this is often reproduced with relatively large articles. I can send you a link to such article which is always trimmed, but it is in Russian: http://med-history.livejournal.com/17716.html

Environment:
gReader version: latest by Aug 22, pro version.
OS: Android 5.0.1
Device: Motorola Moto G (2013)
Update: attached a screenshot.
Please let me know if I can provide more details.

**Comment by watercrossing** [comment]
I have this issue too. On any long, cached article greader misses off the lower part.

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
