### ISSUE TITLE
Widget is missing

### ISSUE THREAD

**Issue by donnergretel** [noinnion/greader#63]
The gReader widget, displaying the Nummer of unread articels, is missing.
gReader 4.2.0
Sony Xperia z2
Android 5.1.1
Language german.

**Comment by 8BitBitch** [comment]
No gReader widgets have been loaded to my device. What can I do to secure them? 

gReader Pro 4.2.0
Samsung-SM-G900A 
Android 5.0

**Comment by noinnion** [comment]
Try reinstalling the app.

**Comment by funtomas** [comment]
same here missing widgets

**Comment by noinnion** [comment]
have you tried the FAQ?
http://noinnion.com/greader/faq/

also please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true
