### ISSUE TITLE
Error message pops up when feed is imported

### ISSUE THREAD

**Issue by pfrenssen** [noinnion/greader#65]
Often when this feed is imported an error message appears. I cannot read or copy the message since it appears in an overlay that disappears when I tap it. It might be related to SQL. Perhaps the feed is not valid. 

https://www.elitedangerous.com/en/galnet-rss

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by pfrenssen** [comment]
Installed the 4.3.0 beta. So far so good, have no error messages. Will keep an eye on it in the coming days.

Thanks a lot!
