### ISSUE TITLE
Links broken when coming back to article

### ISSUE THREAD

**Issue by Mateopato** [noinnion/greader#66]
While reading an article, if I turn the screen off and back on again (with the power button or after the phone's sleep delay) or switch to another app and back to gReader, links within articles no longer work. Clicking links makes the loading bar appear at the top of the screen, but nothing ever loads. 

Note 4, Android 5.0.1

**Comment by jedfonner** [comment]
I'm having the same issue on my Moto X 2013, Android 5.1

**Comment by jedfonner** [comment]
@noinnion FYI - this is a real issue, not spam!

**Comment by mepants** [comment]
I get the same issue on my Galaxy S6. I also get a seemingly related problem where after waking,  scrolling down only goes so far before the page content runs out and the remainder of the page is a plain grey rectangle. 

My guess is that going to sleep somehow replaces the live Web page with a rasterised bitmap of a region of the page. Obviously,  the page doesn't respond to input,  and the scrolling issue happens when scrolling outside the region of the page that has been rendered into the bitmap.

**Comment by dgmitchal** [comment]
Same problem even without putting the phone to sleep or even switching apps.

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by mepants** [comment]
Thanks - I've given it a quick test and it looks like it's fixed that bug.

Being a beta,  it now seems to be showing another bug - every time I exit
via the home button then launch from the icon in the app launcher,  the app
starts as if it has been relaunched from scratch - showing the article list
with no sign of the article that I was reading.  If I go back in from the
task switcher, it is fine.

I appreciate your effort in fixing these bugs.

Thanks,

Craig

**Comment by noinnion** [comment]
do you have any apps that clean memory in the background?

**Comment by mepants** [comment]
No, it's a reasonably vanilla Galaxy S6,  running the Google Now Launcher.

Funnily enough,  I just tested again and it seems fine now,  so it may be
intermittent, or related to initial installation.

On 1 Apr 2016 22:35, "noinnion" <notifications@github.com> wrote:
>
> do you have any apps that clean memory in the background?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
<https://github.com/noinnion/greader/issues/66#issuecomment-204572260>
