### ISSUE TITLE
Issue with links and a weird black box on bottom half of article that blocks the view

### ISSUE THREAD

**Issue by dewdkorn6969** [noinnion/greader#67]
Having an issue with anytime I use another app and then switch back to greader... basically if I share a link or open up another app and then switch back to greader the article I'm reading has a black box on the bottom half of the screen that blocks my view and all links are disabled I can't tap anything nor play any videos.. it also seems to happen after watching a video using the pop-up YouTube player built into the app.. after the video is done same issues apear.. only way to get rid of the black box is if I press back to go to article list and reload the article.. (issue persists even if I swipe left or right to other articles from different feeds) I'm running lollipop 5.1.1 on a note 5

**Comment by dewdkorn6969** [comment]
Just want to clarify I can't interact with the page at all but the app is still responsive I can switch to Web or feed view and all other controls still work but all interaction with the Web page stops working besides scrolling and zooming

**Comment by dewdkorn6969** [comment]
OK after more testing it doesn't happen 100% of the time with most apps but it happens pretty consistently with textra and just about every time when using the video player it disables any links and it also has the black box show up around every 4th or 5th time weather I use the in app player or the regular YouTube app

**Comment by noinnion** [comment]
I will investigate the issue.

**Comment by noinnion** [comment]
fixed in v4.3.0
