### ISSUE TITLE
Volume Button preference not taking

### ISSUE THREAD

**Issue by ipkh** [noinnion/greader#68]
My volume up and down keys still move through the article list even though this feature is disabled in settings. I changed the setting to "none" as I listen to music/podcasts while reading and like to adjust the volume while in greader.  It worked fine on my Note 3.
I have a Galaxy Note 5.

**Comment by noinnion** [comment]
Try reinstalling the app.

**Comment by ipkh** [comment]
I reinstalled the app and the setting still does not work.
I reinstalled, changed the setting and tested it.  The volume buttons still advanced to the next article.  I then cleared the cache and relaunched and the behaviour had not changed.  The setting comes up as none correctly in the settingsame menu.

**Comment by noinnion** [comment]
i will investigate the issue.

**Comment by daddydave** [comment]
I have this issue as well. I have a Moto G 2015 with Lollipop. I do have the free version if that makes a difference.

**Comment by Hobb** [comment]
Also happening here, I'm using the free version on lollipop (CM12.1) with a S4.

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

**Comment by ipkh** [comment]
Is this the same build I downloaded a few days ago?

**Comment by noinnion** [comment]
the file is always updated

please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true

Settings->Reading Preferences->Article Controls

**Comment by ipkh** [comment]
Fixed.
