### ISSUE TITLE
Feature request: JWPlayer playlist RSS feed format for podcasts

### ISSUE THREAD

**Issue by psxitt** [noinnion/greader#71]
The very commonly embedded audio and video player JWPlayer offers an RSS-based playlist format. These playlists are sometimes used on media websites (for instance radio channels) as a way to provide podcast-like functionality on the websites (integrated to the website's CMS), even though not supporting and publishing the common podcast RSS format.

It is currently possible to subscribe to these playlists through GReader Pro, even though the media file is not detected (because of the specific XML entity name). It would be great if it was.

A sample of such a playlist can be found at http://ns227996.ovh.net:8080/rcj/rest/pl/jwp/latest

**Comment by noinnion** [comment]
you can add it in Feedly or TOR. local RSS does not support it right now

**Comment by psxitt** [comment]
Unfortunately the RSS is properly parsed but the media file is not detected so these RSS feeds can not be considered as podcasts by GReader Pro - the entity syntax is <jwplayer:file>URL</jwplayer:file> in an <item> element instead of <enclosure url="..." />
