### ISSUE TITLE
Request for uncorrupted image

### ISSUE THREAD

**Issue by anonaisu** [noinnion/greader#72]
There are many image sites such as tumblr and etc, but the images are listed with curroption. I need to open the article one by one to see the entire image.

Could it be uncorrupted so I could see entire images for all of them in list?

Thanks!

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue

**Comment by anonaisu** [comment]
Thank you so much for your support!

I tried by myself, but I cannot figure out how to see the entire image. Shall I have to look into the settings?

**Comment by noinnion** [comment]
could you send me an example?

**Comment by anonaisu** [comment]
Here you can see that images are cropped.

![Screenshot_20210227-193120](https://user-images.githubusercontent.com/13214752/109384771-87498480-7932-11eb-95b4-c3e1d2f03ddd.jpg)
