### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by dewdkorn6969** [noinnion/greader#77]
Having an issue with alot of articles from kinja sites(io9,gizmodo,kotaku).. in feed view or cached view it only loads the first 3 pictures of the article and the rest stay blank.. if I press and hold where the picture should be I'm getting a url that says 

data:img/svg+xml 

With a bunch of characters after that but it never loads even when pressing view image...

**Comment by noinnion** [comment]
Try to clear the cache.

**Comment by dewdkorn6969** [comment]
Tried that did a complete wipe.. even went so far as to clear app data and cache from app manager with no luck then uninstalled and reinstalled thinking some setting was glitched from my import but that didn't help either

**Comment by dewdkorn6969** [comment]
This might be related to issues 67 and 66 as well.. something weird going on with Webkit never had this problem with my s4 on kitkat

**Comment by noinnion** [comment]
please try the latest beta v4.3.1_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.1_pro-beta.apk?raw=true

Change log: https://github.com/noinnion/greader/tree/master/beta
- "3D Touch" for thumbnails (long tap on thumbnails to show them immediately, release will close it)
- Improved list item swiping
- Improved article view, prevent duplicate images, gif issue
