### ISSUE TITLE
Android 6 performance 

### ISSUE THREAD

**Issue by pentago** [noinnion/greader#83]
Wow often, when new feed/folder is marked as read app hungs and should be force killed and restarted to work again. Android 6/Nexus 5

**Comment by cpinter** [comment]
Same device and OS. After locking the phone scrolling breaks. Instead if the usual smooth panning it goes to an unpredictable jump. Maybe related to Marshmallow doze feature?

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true
