### ISSUE TITLE
"Linux.org.ru:Новости" feed bugs

### ISSUE THREAD

**Issue by omgiafs** [noinnion/greader#84]
Hi!

Known bugs:
1. Often instead of news text displays one of the commentary.
2. News duplicated. One comes from feedproxy.google.com, another from www.linux.org.ru.
And both news - it's the same comment :disappointed:

**Comment by noinnion** [comment]
what service do you use? Feedly, The Old Reader or Local?

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
