### ISSUE TITLE
Please add the ability to navigate to web site by holding tgread

### ISSUE THREAD

**Issue by alliedcvil** [noinnion/greader#86]
When navigating the list of threads from a feed I commonly find one or two that I know I'll need to open in my browser. Instead of having to open the thread and then open the browser can an option be added when you tap and hold the thread to launch the thread in a browser. I know you can add a quick action to perform this step on the left or right side, but that tends to open at times inadvertantly.

**Comment by virtualdj** [comment]
+1 it would be useful!
