### ISSUE TITLE
Problem with displaying source code samples

### ISSUE THREAD

**Issue by torpederos** [noinnion/greader#89]
There is some issue with displaying blog postd which contain source code samples, like this one: http://www.c-sharpcorner.com/UploadFile/8a67c0/singleton-design-pattern-vs-static-class/ 
When article is displayed in Google Chrome everything works OK but in greader internal browser I can't scroll fields with long code samples.

**Comment by whimboo** [comment]
Looks like this is the same problem as what I have reported a couple of months ago:
https://github.com/noinnion/greader/issues/13
