### ISSUE TITLE
Non-standard share icon

### ISSUE THREAD

**Issue by arcresu** [noinnion/greader#9]
Currently the share icon looks like this (dot with two outward arrows):

![gReader share icon](http://i.imgur.com/JWt8jjA.png)

Whereas the most usual share icon [recommended by the android docs](http://developer.android.com/design/style/iconography.html) is the three-node graph icon:

![android share icon](http://i.imgur.com/ZUfH21F.png)

It would be great for consistency with android design if the standard icon provided by android (at the above link) could be used instead.

**Comment by noinnion** [comment]
Closed for now, if it still happens in latest version 5.1.2, please reopen it again. Thanks
