### ISSUE TITLE
Can not sync in China

### ISSUE THREAD

**Issue by naore** [noinnion/greader#90]
When i use the free version, there was no problem, and I love that app. But now I've buy this pro version, and I found it cannot sync RSS. Is there any solution?

**Comment by ZephanXiao** [comment]
Yes! I have the same problem!  I spent  a lot of time in searcing an easy-to-use rss app, finally i found greader.   I was so happy then. And now this problem drive me mad. Please fix it. It is the best rss app i have ever met.

**Comment by noinnion** [comment]
what service (Feedly, TOR, Local) do you use? is it because China blocks the sources?

**Comment by alexchan420** [comment]
There are some responses some times ago about China sometimes block feedly even over HTTPS.
I bet it is network problem instead of app problem.
