### ISSUE TITLE
Can't disable new list view

### ISSUE THREAD

**Issue by steveinflow** [noinnion/greader#91]
The new list view doesn't show the name of the article's source. That is important information.

I chose this app because articles were presented in a simple textual list, unlike the flashier alternatives.

I've turned off the rich article list item in settings, but it has not reverted to the simple list.

**Comment by noinnion** [comment]
could you send a screenshot?

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
