### ISSUE TITLE
Message "Please logout and login again"

### ISSUE THREAD

**Issue by mzguy** [noinnion/greader#93]
Since I updated my Android OS version, I am getting a frequent toast message at the bottom of my screen: "Please logout and login again!".

A search online shows several posts indicating that Greader is generating this message. Could that be the case? Is there a way to stop the message? Greader seems to work fine, and logging out and back into Greader did not cause the message to go away.

**Comment by zwn** [comment]
:+1: I have the same problem.

**Comment by mzguy** [comment]
Have you been able to confirm that Greader is causing this?

**Comment by zwn** [comment]
Well, I have uninstalled greader (and the other news reader from noinnion just to be sure) because I haven't had the time to do anything else. I have not seen that message since.

**Comment by mzguy** [comment]
Thanks for the info. I have now uninstalled as well, and can confirm the message is gone. I've switched to a different reader.

As much as I like Greader, it has been getting a little buggy. Furthermore, complete inactivity from the developer on the forums, over email, and web (noinnion.com has been down), leads me to believe it has been abandoned.

**Comment by ajoe** [comment]
GReader is DEAD!  
Developer doesn't answer to mails. Website http://noinnion.com/greader is down since a couple months (03/2016). I liked it, but there is no source code public available. 
My alternatives that I found good:

Palabre - RSS-Reader (2,40 € to remove Add's)
https://play.google.com/store/apps/details?id=com.levelup.palabre

Antennapod - Podcast (OSS - Open Source Software)
https://play.google.com/store/apps/details?id=de.danoeh.antennapod

**Comment by noinnion** [comment]
please try the latest beta v4.3.1_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.1_pro-beta.apk?raw=true

Change log: https://github.com/noinnion/greader/tree/master/beta
- 3D Touch for thumbnails (long tap on thumbnails to show them immediately, release will close it)
- Improved list item swiping
- Improved article view, prevent duplicate images

**Comment by Divi** [comment]
The message is still here on `v4.3.1_pro`.

**Comment by brendonrapp** [comment]
Oh my god, this is where that stupid message is coming from!

At least change the message to indicate what app is making the message. I've gotten that message while using a dozen apps that are all not gReader. Absurd.

**Comment by noinnion** [comment]
Please try latest version or beta https://github.com/noinnion/greader/tree/master/apk/beta, 
otherwise reopen the issue
