### ISSUE TITLE
Pages won't load

### ISSUE THREAD

**Issue by itinj30** [noinnion/greader#95]
After opening a few articles, the blue bar page load status just get about 15%, and nothing happens.  I can still

**Comment by itinj30** [comment]
Oops.  I can still open in browser, but less than efficient.

**Comment by itinj30** [comment]
Happens in both released and in beta

**Comment by itinj30** [comment]
![screenshot_2015-11-10-19-31-24](https://cloud.githubusercontent.com/assets/15793042/11081583/7dbe328a-87e3-11e5-95e6-e890c48cdd8a.png)

**Comment by noinnion** [comment]
please try the latest beta v4.3.0_beta
https://github.com/noinnion/greader/blob/master/beta/gReader-4.3.0_pro-beta.apk?raw=true
